// packages/react/src/components/color-area/thumb/ColorAreaThumb.tsx
import { forwardRef, useCallback, useEffect, useRef, type ComponentPropsWithoutRef } from "react";
import { convertValueToPercentage } from "../../../utils";
import { useColorAreaContext } from "../root/ColorAreaRootContext";

export interface ColorAreaThumbProps extends ComponentPropsWithoutRef<"span"> {
  /** The thumb index (for multi-thumb scenarios). Defaults to 0. */
  index?: number;
}

export const ColorAreaThumb = forwardRef<HTMLSpanElement, ColorAreaThumbProps>(
  function ColorAreaThumb({ index = 0, style, children, ...props }, ref) {
    const ctx = useColorAreaContext();
    const elRef = useRef<HTMLSpanElement>(null);

    useEffect(() => {
      const el = elRef.current;
      if (el) ctx.thumbRef.current = el;
      return () => {
        if (ctx.thumbRef.current === el) ctx.thumbRef.current = null;
      };
    }, [ctx]);

    const value = ctx.currentModelValue[index];
    const percentX = value !== undefined ? convertValueToPercentage(value[0] ?? 0, ctx.minX, ctx.maxX) : 0;
    const percentY = value !== undefined ? convertValueToPercentage(value[1] ?? 0, ctx.minY, ctx.maxY) : 0;

    const handleFocus = useCallback(() => {
      ctx.setValueIndexToChange(index);
    }, [ctx, index]);

    return (
      <span
        ref={(el) => {
          elRef.current = el;
          if (typeof ref === "function") ref(el);
          else if (ref) ref.current = el;
        }}
        role="slider"
        tabIndex={ctx.disabled ? undefined : 0}
        aria-roledescription="2D slider"
        aria-valuenow={value ? value[0] : undefined}
        aria-valuemin={ctx.minX}
        aria-valuemax={ctx.maxX}
        data-disabled={ctx.disabled ? "" : undefined}
        onFocus={handleFocus}
        style={{
          transform: "var(--reka-slider-area-thumb-transform)",
          position: "absolute",
          [ctx.isSlidingFromLeft ? "left" : "right"]: `${percentX}%`,
          [ctx.isSlidingFromTop ? "top" : "bottom"]: `${percentY}%`,
          ...style,
        }}
        {...props}
      >
        {children}
      </span>
    );
  },
);

// packages/vue/src/components/ColorArea/ColorAreaThumb.vue
<script lang="ts">
import type { PrimitiveProps } from "reka-ui";
export interface ColorAreaThumbProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
}
</script>

<script setup lang="ts">
import { useMounted } from "@vueuse/core";
import { computed, onMounted, onUnmounted } from "vue";
import { Primitive, useForwardExpose } from "reka-ui";
import { injectColorAreaRootContext } from "./ColorAreaRoot.vue";
import { convertValueToPercentage, getLabel, getThumbInBoundsOffset, useCollection, useSize } from "./utils";
defineOptions({
  inheritAttrs: false,
});

withDefaults(defineProps<ColorAreaThumbProps>(), {
  as: "span",
});

const rootContext = injectColorAreaRootContext();
const { forwardRef, currentElement: thumbElement } = useForwardExpose();
const { CollectionItem, getItems } = useCollection();

const index = computed(() => thumbElement.value ? getItems(true).findIndex(i => i.ref === thumbElement.value) : -1);

const value = computed(() => rootContext.modelValue?.value?.[index.value]);
const percentX = computed(() => value.value === undefined ? 0 : convertValueToPercentage(value.value[0] ?? 0, rootContext.minX.value ?? 0, rootContext.maxX.value ?? 100));
const percentY = computed(() => value.value === undefined ? 0 : convertValueToPercentage(value.value[1] ?? 0, rootContext.minY.value ?? 0, rootContext.maxY.value ?? 100));
const label = computed(() => getLabel(index.value, rootContext.modelValue?.value?.length ?? 0));

const size = useSize(thumbElement);
const thumbInBoundsOffsetX = computed(() => {
  if (rootContext.thumbAlignment.value === "overflow" || !size.width.value)
    return 0;
  return getThumbInBoundsOffset(size.width.value, percentX.value, rootContext.isSlidingFromLeft.value ? 1 : -1);
});
const thumbInBoundsOffsetY = computed(() => {
  if (rootContext.thumbAlignment.value === "overflow" || !size.height.value)
    return 0;
  return getThumbInBoundsOffset(size.height.value, percentY.value, rootContext.isSlidingFromTop.value ? 1 : -1);
});

const isMounted = useMounted();

onMounted(() => {
  if (thumbElement.value)
    rootContext.thumbRef.value = thumbElement.value;
});
onUnmounted(() => {
  if (rootContext.thumbRef.value === thumbElement.value)
    rootContext.thumbRef.value = undefined;
});
</script>

<template>
  <CollectionItem>
    <Primitive
      v-bind="$attrs"
      :ref="forwardRef"
      role="slider"
      :tabindex="rootContext.disabled.value ? undefined : 0"
      :aria-label="($attrs['aria-label'] as string) || label"
      :aria-valuenow="value ? value[0] : undefined"
      :aria-valuemin="rootContext.minX.value"
      :aria-valuemax="rootContext.maxX.value"
      :data-disabled="rootContext.disabled.value ? '' : undefined"
      aria-roledescription="2D slider"
      :as-child="asChild"
      :as="as"
      :style="{
        transform: 'var(--reka-slider-area-thumb-transform)',
        position: 'absolute',
        [rootContext.isSlidingFromLeft.value ? 'left' : 'right']: `calc(${percentX}% + ${thumbInBoundsOffsetX}px)`,
        [rootContext.isSlidingFromTop.value ? 'top' : 'bottom']: `calc(${percentY}% + ${thumbInBoundsOffsetY}px)`,
        display: !isMounted && value === undefined ? 'none' : undefined,
      }"
      @focus="() => {
        rootContext.valueIndexToChangeRef.value = index
      }"
    >
      <slot />
    </Primitive>
  </CollectionItem>
</template>
