// packages/react/src/components/ColorArea/ColorAreaThumbY.tsx
import { forwardRef, useCallback, useEffect, useRef, type ComponentPropsWithoutRef } from "react";
import { useColorAreaContext, useColorAreaThumbContext } from "./ColorAreaContext";

export interface ColorAreaThumbYProps extends ComponentPropsWithoutRef<"span"> {}

export const ColorAreaThumbY = forwardRef<HTMLSpanElement, ColorAreaThumbYProps>(
  function ColorAreaThumbY(props, ref) {
    const ctx = useColorAreaContext();
    const thumbCtx = useColorAreaThumbContext();
    const elRef = useRef<HTMLSpanElement>(null);

    useEffect(() => {
      const el = elRef.current;
      if (el) ctx.thumbYElements.current.push(el);
      return () => {
        const i = ctx.thumbYElements.current.indexOf(el!);
        if (i >= 0) ctx.thumbYElements.current.splice(i, 1);
      };
    }, [ctx]);

    const value = ctx.currentModelValue[thumbCtx.index];

    const handleFocus = useCallback(() => {
      ctx.setValueIndexToChange(thumbCtx.index);
      ctx.setActiveDirection("y");
    }, [ctx, thumbCtx.index]);

    return (
      <span
        ref={(el) => {
          (elRef as React.MutableRefObject<HTMLSpanElement | null>).current = el;
          if (typeof ref === "function") ref(el);
          else if (ref) ref.current = el;
        }}
        role="slider"
        tabIndex={ctx.disabled ? undefined : (ctx.activeDirection === "y" ? 0 : -1)}
        data-disabled={ctx.disabled ? "" : undefined}
        aria-orientation="vertical"
        aria-valuenow={value ? value[1] : undefined}
        aria-valuemin={ctx.minY}
        aria-valuemax={ctx.maxY}
        onFocus={handleFocus}
        style={{ position: "absolute", display: "block", width: "100%", height: "100%" }}
        {...props}
      />
    );
  },
);

// packages/vue/src/components/ColorArea/ColorAreaThumbY.vue
<script lang="ts">
import type { PrimitiveProps } from "reka-ui";
export interface ColorAreaThumbYProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
}
</script>

<script setup lang="ts">
import { computed, onMounted, onUnmounted } from "vue";
import { Primitive, useForwardExpose } from "reka-ui";
import { injectColorAreaRootContext } from "./ColorAreaRoot.vue";
import { injectColorAreaThumbContext } from "./utils";

withDefaults(defineProps<ColorAreaThumbYProps>(), {
  as: "span",
});

const rootContext = injectColorAreaRootContext();
const thumbContext = injectColorAreaThumbContext();
const { forwardRef, currentElement: thumbElement } = useForwardExpose();

const value = computed(() => rootContext.modelValue?.value?.[thumbContext.index.value]);

onMounted(() => {
  if (thumbElement.value)
    rootContext.thumbYElements.value.push(thumbElement.value);
});
onUnmounted(() => {
  const i = rootContext.thumbYElements.value.findIndex(el => el === thumbElement.value);
  if (i >= 0)
    rootContext.thumbYElements.value.splice(i, 1);
});
</script>

<template>
  <Primitive
    :ref="forwardRef"
    role="slider"
    :tabindex="rootContext.disabled.value ? undefined : (rootContext.activeDirection.value === 'y' ? 0 : -1)"
    :data-disabled="rootContext.disabled.value ? '' : undefined"
    aria-orientation="vertical"
    :aria-valuenow="value ? value[1] : undefined"
    :aria-valuemin="rootContext.minY.value"
    :aria-valuemax="rootContext.maxY.value"
    :as-child="asChild"
    :as="as"
    :style="{
      position: 'absolute',
      display: 'block',
      width: '100%',
      height: '100%',
    }"
    @focus="() => {
      rootContext.valueIndexToChangeRef.value = thumbContext.index.value
      rootContext.activeDirection.value = 'y'
    }"
  >
    <slot />
  </Primitive>
</template>
