// packages/vue/src/components/ColorTriangle/ColorTriangleThumb.vue
<script lang="ts">
import type { PrimitiveProps } from "reka-ui";

export interface ColorTriangleThumbProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
}
</script>

<script setup lang="ts">
import { computed } from "vue";
import { Primitive, useForwardExpose } from "reka-ui";
import { barycentricToCartesian } from "@urcolor/core";
import { injectColorTriangleRootContext } from "./ColorTriangleRoot.vue";

withDefaults(defineProps<ColorTriangleThumbProps>(), { as: "span" });

const rootContext = injectColorTriangleRootContext();
useForwardExpose();

const thumbPosition = computed(() => {
  const xVal = rootContext.currentXValue.value;
  const yVal = rootContext.currentYValue.value;
  const xMin = rootContext.xMin.value;
  const xMax = rootContext.xMax.value;
  const yMin = rootContext.yMin.value;
  const yMax = rootContext.yMax.value;
  const xRange = xMax - xMin;
  const yRange = yMax - yMin;

  let u: number, v: number, w: number;

  if (rootContext.isThreeChannel.value) {
    // 3-channel: v0→(xMax,yMin,zMin), v1→(xMin,yMax,zMin), v2→(xMin,yMin,zMax)
    const zVal = rootContext.currentZValue.value;
    const zMin = rootContext.zMin.value;
    const zMax = rootContext.zMax.value;
    const zRange = zMax - zMin;
    const rawU = xRange === 0 ? 0 : (xVal - xMin) / xRange;
    const rawV = yRange === 0 ? 0 : (yVal - yMin) / yRange;
    const rawW = zRange === 0 ? 0 : (zVal - zMin) / zRange;
    // Normalize so they sum to 1
    const sum = rawU + rawV + rawW || 1;
    u = rawU / sum;
    v = rawV / sum;
    w = rawW / sum;
  } else {
    // 2-channel: v0→(xMax,yMax), v1→(xMin,yMax), v2→(xMin,yMin)
    u = xRange === 0 ? 0 : (xVal - xMin) / xRange;
    w = yRange === 0 ? 0 : 1 - (yVal - yMin) / yRange;
    v = Math.max(0, 1 - u - w);
  }

  const [v0, v1, v2] = rootContext.vertices.value;
  const pos = barycentricToCartesian(u, v, w, v0, v1, v2);

  return {
    left: `${pos.x * 100}%`,
    top: `${pos.y * 100}%`,
  };
});
</script>

<template>
  <Primitive
    role="slider"
    tabindex="0"
    aria-roledescription="2D slider"
    :aria-valuenow="rootContext.currentXValue.value"
    :aria-valuemin="rootContext.xMin.value"
    :aria-valuemax="rootContext.xMax.value"
    :aria-disabled="rootContext.disabled.value"
    :data-disabled="rootContext.disabled.value ? '' : undefined"
    :as-child="asChild"
    :as="as"
    :style="{
      position: 'absolute',
      left: thumbPosition.left,
      top: thumbPosition.top,
      transform: 'translate(-50%, -50%)',
    }"
  >
    <slot />
  </Primitive>
</template>

// packages/react/src/components/ColorTriangle/ColorTriangleThumb.tsx
import { forwardRef, useMemo, useEffect, type ComponentPropsWithoutRef } from "react";
import { barycentricToCartesian } from "@urcolor/core";
import { useColorTriangleContext } from "./ColorTriangleContext";

export interface ColorTriangleThumbProps extends ComponentPropsWithoutRef<"span"> {}

export const ColorTriangleThumb = forwardRef<HTMLSpanElement, ColorTriangleThumbProps>(
  function ColorTriangleThumb({ style, children, ...props }, ref) {
    const ctx = useColorTriangleContext();

    // Register thumb element
    useEffect(() => {
      if (ref && typeof ref === "object" && ref.current) {
        ctx.thumbElement.current = ref.current;
      }
    });

    const thumbPosition = useMemo(() => {
      const xVal = ctx.currentXValue;
      const yVal = ctx.currentYValue;
      const xRange = ctx.xMax - ctx.xMin;
      const yRange = ctx.yMax - ctx.yMin;

      let u: number, v: number, w: number;

      if (ctx.isThreeChannel) {
        const zVal = ctx.currentZValue;
        const zRange = ctx.zMax - ctx.zMin;
        const rawU = xRange === 0 ? 0 : (xVal - ctx.xMin) / xRange;
        const rawV = yRange === 0 ? 0 : (yVal - ctx.yMin) / yRange;
        const rawW = zRange === 0 ? 0 : (zVal - ctx.zMin) / zRange;
        const sum = rawU + rawV + rawW || 1;
        u = rawU / sum;
        v = rawV / sum;
        w = rawW / sum;
      } else {
        u = xRange === 0 ? 0 : (xVal - ctx.xMin) / xRange;
        w = yRange === 0 ? 0 : 1 - (yVal - ctx.yMin) / yRange;
        v = Math.max(0, 1 - u - w);
      }

      const [v0, v1, v2] = ctx.vertices;
      const pos = barycentricToCartesian(u, v, w, v0, v1, v2);

      return {
        left: `${pos.x * 100}%`,
        top: `${pos.y * 100}%`,
      };
    }, [ctx.currentXValue, ctx.currentYValue, ctx.currentZValue, ctx.xMin, ctx.xMax, ctx.yMin, ctx.yMax, ctx.zMin, ctx.zMax, ctx.isThreeChannel, ctx.vertices]);

    return (
      <span
        ref={(el) => {
          if (el) ctx.thumbElement.current = el;
          if (typeof ref === "function") ref(el);
          else if (ref) ref.current = el;
        }}
        aria-roledescription="2D slider"
        aria-disabled={ctx.disabled}
        data-disabled={ctx.disabled ? "" : undefined}
        style={{
          position: "absolute",
          left: thumbPosition.left,
          top: thumbPosition.top,
          transform: "translate(-50%, -50%)",
          ...style,
        }}
        {...props}
      >
        {children}
      </span>
    );
  },
);
