// packages/svelte/src/lib/components/color-field/decrement/ColorFieldDecrement.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLButtonAttributes } from "svelte/elements";
  import type { ChildSnippetArgs } from "../../../shared/child.js";

  export interface ColorFieldDecrementProps extends HTMLButtonAttributes {
    /** Replaces the default element; receives the props it would have received. */
    child?: Snippet<[ChildSnippetArgs]>;
  }
</script>

<script lang="ts">
  import { createAttachmentKey } from "svelte/attachments";
  import { DATA_DISABLED, DATA_PRESSED } from "@urcolor/primitives";
  import type { ChildProps } from "../../../shared/child.js";
  import { colorFieldContext } from "../root/context.svelte.js";

  /** Delay before a held button starts repeating, then the repeat interval. */
  const HOLD_DELAY = 400;
  const REPEAT_INTERVAL = 60;

  let { class: className, style, children, child, ...rest }: ColorFieldDecrementProps = $props();

  const context = colorFieldContext.get();

  const isDisabled = $derived(context.disabled || context.readOnly || context.isDecreaseDisabled);

  let pressed = $state(false);
  /** Plain, non-reactive: only the hold loop reads it. */
  let timeout: ReturnType<typeof setTimeout> | undefined;

  /** Steps once, then schedules itself so a held button keeps stepping. */
  function startPress(delay: number): void {
    if (timeout !== undefined) clearTimeout(timeout);
    if (isDisabled) return;
    context.handleDecrease();
    timeout = setTimeout(() => startPress(REPEAT_INTERVAL), delay);
  }

  const attachmentKey = createAttachmentKey();

  /**
   * The button's behaviour attachment: press-and-hold stepping.
   *
   * It travels inside the props object under a `Symbol` key, so a consumer
   * spreading those props onto their own `<button>` — or onto another component
   * — gets the full interaction, which an `onpointerdown` prop bag could not do.
   * The release listeners live on `window` so a pointer that leaves the button
   * before lifting still ends the hold.
   */
  function interaction(node: HTMLButtonElement): () => void {
    const stop = (): void => {
      pressed = false;
      if (timeout !== undefined) clearTimeout(timeout);
      timeout = undefined;
      window.removeEventListener("pointerup", stop);
      window.removeEventListener("pointercancel", stop);
    };
    const onPointerDown = (event: PointerEvent): void => {
      if (event.button !== 0 || isDisabled) return;
      event.preventDefault();
      pressed = true;
      startPress(HOLD_DELAY);
      window.addEventListener("pointerup", stop);
      window.addEventListener("pointercancel", stop);
    };
    const onContextMenu = (event: Event): void => event.preventDefault();

    node.addEventListener("pointerdown", onPointerDown);
    node.addEventListener("contextmenu", onContextMenu);

    return () => {
      node.removeEventListener("pointerdown", onPointerDown);
      node.removeEventListener("contextmenu", onContextMenu);
      stop();
    };
  }

  const elementProps = $derived<ChildProps>({
    ...rest,
    // The input owns the field's tab stop; the steppers are pointer affordances.
    "type": "button",
    "tabindex": -1,
    "aria-label": rest["aria-label"] ?? "Decrease",
    "disabled": isDisabled || undefined,
    "class": className,
    "style": style,
    [DATA_PRESSED]: pressed ? "" : undefined,
    [DATA_DISABLED]: isDisabled ? "" : undefined,
    [attachmentKey]: interaction,
  });
</script>

{#if child}
  {@render child({ props: elementProps })}
{:else}
  <button {...elementProps}>{@render children?.()}</button>
{/if}

// packages/angular/src/components/color-field/decrement/color-field-decrement.ts
import {
  computed,
  DestroyRef,
  Directive,
  HostAttributeToken,
  inject,
  signal,
} from "@angular/core";
import { DATA_DISABLED, DATA_PRESSED } from "@urcolor/primitives";
import { ColorFieldRoot } from "../root/color-field-root";

/** Delay before a held button starts repeating, then the repeat interval. */
const HOLD_DELAY = 400;
const REPEAT_INTERVAL = 60;

/**
 * Steps the field down, applied to a native `<button>`.
 *
 * Holding the button repeats: one step immediately, then a step every
 * `REPEAT_INTERVAL` ms after an initial `HOLD_DELAY` pause. The release
 * listeners live on `window` so a pointer that leaves the button before lifting
 * still ends the hold.
 */
@Directive({
  selector: "button[urcColorFieldDecrement]",
  exportAs: "urcColorFieldDecrement",
  host: {
    "[attr.type]": "'button'",
    "[attr.tabindex]": "'-1'",
    "[attr.aria-label]": "label",
    "[disabled]": "isDisabled()",
    [`[attr.${DATA_PRESSED}]`]: "pressed() ? '' : null",
    [`[attr.${DATA_DISABLED}]`]: "isDisabled() ? '' : null",
    "(pointerdown)": "onPointerDown($event)",
    "(contextmenu)": "onContextMenu($event)",
  },
})
export class ColorFieldDecrement {
  private readonly root = inject(ColorFieldRoot);
  private readonly destroyRef = inject(DestroyRef);

  /** A consumer's own `aria-label` wins; "Decrease" is only a fallback. */
  protected readonly label
    = inject(new HostAttributeToken("aria-label"), { optional: true }) ?? "Decrease";

  private readonly pressedState = signal(false);

  /** True while the button is held down. */
  protected readonly pressed = this.pressedState.asReadonly();

  /** The input owns the field's tab stop; the steppers are pointer affordances. */
  protected readonly isDisabled = computed(
    () => this.root.isDisabled() || this.root.isReadOnly() || this.root.isDecreaseDisabled(),
  );

  /** Plain, non-reactive: only the hold loop reads it. */
  private timeout: ReturnType<typeof setTimeout> | undefined;

  constructor() {
    this.destroyRef.onDestroy(() => this.stop());
  }

  protected onPointerDown(event: PointerEvent): void {
    if (event.button !== 0 || this.isDisabled()) return;
    event.preventDefault();
    this.pressedState.set(true);
    this.startPress(HOLD_DELAY);
    if (typeof window === "undefined") return;
    window.addEventListener("pointerup", this.stop);
    window.addEventListener("pointercancel", this.stop);
  }

  protected onContextMenu(event: Event): void {
    event.preventDefault();
  }

  /** Steps once, then schedules itself so a held button keeps stepping. */
  private startPress(delay: number): void {
    if (this.timeout !== undefined) clearTimeout(this.timeout);
    if (this.isDisabled()) return;
    this.root.handleDecrease();
    this.timeout = setTimeout(() => this.startPress(REPEAT_INTERVAL), delay);
  }

  /** An arrow property so it detaches by identity from the `window` listeners. */
  private readonly stop = (): void => {
    this.pressedState.set(false);
    if (this.timeout !== undefined) clearTimeout(this.timeout);
    this.timeout = undefined;
    if (typeof window === "undefined") return;
    window.removeEventListener("pointerup", this.stop);
    window.removeEventListener("pointercancel", this.stop);
  };
}
