// docs/components/react/demo/ColorFieldHex.tsx
import "internationalized-color/css";
import {
  ColorFieldRoot,
  ColorFieldInput,
  useColor,
} from "@urcolor/react";

export default function ColorFieldHex() {
  const { color, setColor } = useColor("hsl(210, 80%, 50%)");

  return (
    <div className="flex items-center gap-3">
      <ColorFieldRoot
        value={color}
        onValueChange={setColor}
        colorSpace="hex"
        channel="hex"
        format="hex"
        className="
          flex h-8 items-center overflow-hidden rounded-md border
          border-[var(--vp-c-divider)] bg-[var(--vp-c-bg)] px-3
        "
      >
        <ColorFieldInput
          className="
            min-w-0 flex-1 border-none bg-transparent px-3 py-1.5 font-mono
            text-[13px] text-[var(--vp-c-text-1)] outline-none
          "
        />
      </ColorFieldRoot>
    </div>
  );
}

// docs/components/vue/demo/ColorFieldHex.vue
<script setup lang="ts">
import "internationalized-color/css";
import {
  ColorFieldRoot,
  ColorFieldInput,
  useColor,
} from "@urcolor/vue";

const { color } = useColor("hsl(210, 80%, 50%)");
</script>

<template>
  <div class="flex items-center gap-3">
    <ColorFieldRoot
      v-model="color"
      color-space="hex"
      channel="hex"
      format="hex"
      class="
        flex h-8 items-center overflow-hidden rounded-md border
        border-(--vp-c-divider) bg-(--vp-c-bg) px-3
      "
    >
      <ColorFieldInput
        class="
          min-w-0 flex-1 border-none bg-transparent px-3 py-1.5 font-mono
          text-[13px] text-(--vp-c-text-1) outline-none
        "
      />
    </ColorFieldRoot>
  </div>
</template>
