// packages/vue/src/components/ColorWheel/ColorWheelGradient.vue
<script lang="ts">
import type { PrimitiveProps } from "reka-ui";
import type { GradientRenderer } from "@urcolor/shared";

export interface ColorWheelGradientProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
  /**
   * Which painter to use.
   * - `"auto"` (default) — CSS when an exact recipe exists, canvas otherwise
   * - `"css"` — force CSS; falls back to the canvas with a dev warning if none exists
   * - `"canvas"` — force the canvas painter
   */
  renderer?: GradientRenderer;
  channelOverrides?: Record<string, number> | false;
}
</script>

<script setup lang="ts">
import { ref } from "vue";
import { useForwardExpose, Primitive } from "reka-ui";
import { cssWheelPolar, getChannelConfig, samplePolarGrid } from "@urcolor/shared";
import { applyChannelOverrides, renderToCanvas, useGradientCanvas } from "../../shared/useGradientCanvas";
import { CSS_GRADIENT_ROOT_STYLE, cssLayerStyle, useCssGradient } from "../../shared/useCssGradient";
import { CHECKERBOARD_BACKGROUND } from "../../shared/checkerboard";
import { injectColorWheelRootContext } from "./ColorWheelRoot.vue";

const props = withDefaults(defineProps<ColorWheelGradientProps>(), {
  as: "span",
  renderer: "auto",
  channelOverrides: () => ({ alpha: 1 }),
});

const rootContext = injectColorWheelRootContext();
useForwardExpose();

const canvasRef = ref<HTMLCanvasElement | null>(null);

// The circle is cut here, as it is on the canvas, and for the same reason: the
// root's own `border-radius` alone would leave the corners of the square
// gradient showing.
const CSS_LAYERS_STYLE = { ...CSS_GRADIENT_ROOT_STYLE, clipPath: "circle(50%)" };

const cssLayers = useCssGradient({
  renderer: () => props.renderer,
  name: "ColorWheelGradient",
  build: () => {
    const colorSpace = rootContext.colorSpace.value;
    const baseColor = rootContext.colorRef.value;
    if (!baseColor) return null;

    const overriddenBase = applyChannelOverrides(baseColor, colorSpace, props.channelOverrides);
    return cssWheelPolar(
      overriddenBase, colorSpace,
      rootContext.angleChannelKey.value, rootContext.radiusChannelKey.value,
      rootContext.startAngle.value,
    );
  },
});

function paint(canvas: HTMLCanvasElement) {
  const colorSpace = rootContext.colorSpace.value;
  const baseColor = rootContext.colorRef.value;
  if (!baseColor) return;

  const overriddenBase = applyChannelOverrides(baseColor, colorSpace, props.channelOverrides);
  const angleCfg = getChannelConfig(colorSpace, rootContext.angleChannelKey.value);
  const radiusCfg = getChannelConfig(colorSpace, rootContext.radiusChannelKey.value);
  if (!angleCfg || !radiusCfg) return;

  const aMin = angleCfg.nativeMin ?? angleCfg.min;
  const aMax = angleCfg.nativeMax ?? angleCfg.max;
  const rMin = radiusCfg.nativeMin ?? radiusCfg.min;
  const rMax = radiusCfg.nativeMax ?? radiusCfg.max;

  const sampleSize = 128;
  const pixels = samplePolarGrid(
    overriddenBase, colorSpace,
    rootContext.angleChannelKey.value, rootContext.radiusChannelKey.value,
    aMin, aMax, rMin, rMax,
    sampleSize, sampleSize,
    rootContext.startAngle.value,
  );
  renderToCanvas({ canvas, pixels, sampleWidth: sampleSize, sampleHeight: sampleSize });
}

useGradientCanvas({
  canvas: canvasRef,
  sources: () => [
    props.channelOverrides,
    rootContext.colorSpace.value, rootContext.angleChannelKey.value, rootContext.radiusChannelKey.value,
    rootContext.colorRef.value, rootContext.startAngle.value,
  ],
  paint,
  isDragging: rootContext.isDragging,
});
</script>

<template>
  <Primitive
    :as-child="asChild"
    :as="as"
    :style="{ background: CHECKERBOARD_BACKGROUND, borderRadius: '50%' }"
    :data-disabled="rootContext.disabled.value ? '' : undefined"
  >
    <span
      v-if="cssLayers"
      :style="CSS_LAYERS_STYLE"
    >
      <span
        v-for="(layer, i) in cssLayers"
        :key="i"
        :style="cssLayerStyle(layer)"
      />
    </span>
    <canvas
      v-else
      ref="canvasRef"
      :style="{ position: 'absolute', inset: '0', width: '100%', height: '100%', pointerEvents: 'none', clipPath: 'circle(50%)' }"
    />
    <slot />
  </Primitive>
</template>

// packages/react/src/components/color-wheel/gradient/ColorWheelGradient.tsx
import { forwardRef, useCallback, useEffect, useRef, type ComponentPropsWithoutRef } from "react";
import { Color } from "@urcolor/core";
import { cssWheelPolar, getChannelConfig, renderToCanvas, samplePolarGrid, type GradientRenderer } from "@urcolor/shared";
import { useColorWheelContext } from "../root/ColorWheelRootContext";
import { CHECKERBOARD_BACKGROUND } from "../../../utils";
import { CssGradientLayers, resolveCssGradient } from "../../../cssGradient";

export interface ColorWheelGradientProps extends ComponentPropsWithoutRef<"span"> {
  /**
   * Which painter to use.
   * - `"auto"` (default) - CSS when an exact recipe exists, canvas otherwise
   * - `"css"` - force CSS; falls back to the canvas with a dev warning if none exists
   * - `"canvas"` - force the canvas painter
   */
  renderer?: GradientRenderer;
  channelOverrides?: Record<string, number> | false;
}

export const ColorWheelGradient = forwardRef<HTMLSpanElement, ColorWheelGradientProps>(
  function ColorWheelGradient({ renderer = "auto", channelOverrides = { alpha: 1 }, style, children, ...props }, ref) {
    const ctx = useColorWheelContext();
    const canvasRef = useRef<HTMLCanvasElement | null>(null);

    function applyOverrides(color: Color): Color {
      if (!channelOverrides) return color;
      let result = color;
      const updates: Record<string, number> = {};
      for (const [k, v] of Object.entries(channelOverrides)) {
        if (k === "alpha") result = result.withAlpha(v);
        else if (getChannelConfig(ctx.colorSpace, k)) updates[k] = v;
      }
      if (Object.keys(updates).length > 0) result = result.with({ space: ctx.colorSpace, ...updates });
      return result;
    }

    const cssLayers = resolveCssGradient(renderer, "ColorWheelGradient", () => {
      if (!ctx.colorRef) return null;
      return cssWheelPolar(
        applyOverrides(ctx.colorRef), ctx.colorSpace,
        ctx.angleChannelKey, ctx.radiusChannelKey, ctx.startAngle,
      );
    });

    const render = useCallback(() => {
      const canvas = canvasRef.current;
      if (!canvas || !ctx.colorRef) return;
      let baseColor = ctx.colorRef;
      if (channelOverrides) {
        const updates: Record<string, number> = {};
        for (const [k, v] of Object.entries(channelOverrides)) {
          if (k === "alpha") baseColor = baseColor.withAlpha(v);
          else if (getChannelConfig(ctx.colorSpace, k)) updates[k] = v;
        }
        if (Object.keys(updates).length > 0) baseColor = baseColor.with({ space: ctx.colorSpace, ...updates });
      }

      const angleCfg = getChannelConfig(ctx.colorSpace, ctx.angleChannelKey);
      const radiusCfg = getChannelConfig(ctx.colorSpace, ctx.radiusChannelKey);
      if (!angleCfg || !radiusCfg) return;

      const aMin = angleCfg.nativeMin ?? angleCfg.min;
      const aMax = angleCfg.nativeMax ?? angleCfg.max;
      const rMin = radiusCfg.nativeMin ?? radiusCfg.min;
      const rMax = radiusCfg.nativeMax ?? radiusCfg.max;

      const size = 128;
      const pixels = samplePolarGrid(
        baseColor, ctx.colorSpace,
        ctx.angleChannelKey, ctx.radiusChannelKey,
        aMin, aMax, rMin, rMax,
        size, size, ctx.startAngle,
      );
      renderToCanvas({ canvas, pixels, sampleWidth: size, sampleHeight: size });
    }, [ctx.colorRef, ctx.colorSpace, ctx.angleChannelKey, ctx.radiusChannelKey, ctx.startAngle, ctx.isDragging, channelOverrides]);

    useEffect(() => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      if (!ctx.isDragging) render();
      const observer = new ResizeObserver(() => render());
      observer.observe(canvas);
      return () => observer.disconnect();
    }, [render, ctx.isDragging]);

    useEffect(() => { if (!ctx.isDragging) render(); }, [ctx.isDragging]);

    useEffect(() => () => {
      const canvas = canvasRef.current;
      if (canvas) { const gl = canvas.getContext("webgl"); if (gl) gl.getExtension("WEBGL_lose_context")?.loseContext(); }
    }, []);

    return (
      <span ref={ref} data-disabled={ctx.disabled ? "" : undefined} style={{ background: CHECKERBOARD_BACKGROUND, borderRadius: "50%", ...style }} {...props}>
        {/* The disc shape is cut here rather than inside `renderToCanvas`: the
            sampled grid fills its whole square, and clipping in-canvas as well
            as on the element leaves a seam along the boundary. Matches the Vue
            implementation. */}
        {cssLayers
          ? <CssGradientLayers layers={cssLayers} style={{ clipPath: "circle(50%)" }} />
          : <canvas ref={canvasRef} style={{ position: "absolute", inset: "0", width: "100%", height: "100%", pointerEvents: "none", clipPath: "circle(50%)" }} />}
        {children}
      </span>
    );
  },
);
