// packages/angular/src/components/color-wheel/thumb/color-wheel-thumb.ts
import { computed, Directive, HostAttributeToken, inject } from "@angular/core";
import {
  channelLabel,
  DATA_DISABLED,
  DATA_DRAGGING,
  formatChannelValue,
} from "@urcolor/shared";
import { ColorWheelRoot } from "../root/color-wheel-root";

/**
 * The single combined handle. One thumb drives both axes, so it is only a
 * focus target and an ARIA surface — every value change is owned by the root,
 * whose `keydown` listener sees the events that bubble up from here.
 *
 * `aria-valuenow` can only carry one number; the angular axis owns it and
 * `aria-valuetext` announces the pair.
 */
@Directive({
  selector: "[urcColorWheelThumb]",
  exportAs: "urcColorWheelThumb",
  host: {
    "role": "slider",
    "aria-roledescription": "Color thumb",
    "[attr.tabindex]": "tabIndex()",
    "[attr.aria-label]": "label()",
    "[attr.aria-valuenow]": "root.angleValue()",
    "[attr.aria-valuemin]": "root.angleMin()",
    "[attr.aria-valuemax]": "root.angleMax()",
    "[attr.aria-valuetext]": "valueText()",
    "[attr.aria-disabled]": "root.isDisabled() ? 'true' : null",
    [`[attr.${DATA_DISABLED}]`]: "root.isDisabled() ? '' : null",
    [`[attr.${DATA_DRAGGING}]`]: "root.dragging() ? '' : null",
    "[style.position]": "'absolute'",
    "[style.top]": "'50%'",
    "[style.left]": "'50%'",
    "[style.transform-origin]": "'0 0'",
    "[style.transform]": "transform()",
  },
})
export class ColorWheelThumb {
  protected readonly root = inject(ColorWheelRoot);

  /** A consumer's own `aria-label` wins; the channel pair is only a fallback. */
  private readonly ariaLabelAttr = inject(new HostAttributeToken("aria-label"), { optional: true });

  /** Position on the wheel, in degrees clockwise from 12 o'clock. */
  private readonly angleDeg = computed(() => {
    const min = this.root.angleMin();
    const range = this.root.angleMax() - min;
    if (range === 0) return this.root.startAngle();
    return ((this.root.angleValue() - min) / range) * 360 + this.root.startAngle();
  });

  /**
   * Distance from the centre, as a percentage of the container's smaller side.
   * The wheel's radius is half that side, hence the 50 rather than 100.
   */
  private readonly radiusPercent = computed(() => {
    const min = this.root.radiusMin();
    const range = this.root.radiusMax() - min;
    if (range === 0) return 0;
    return ((this.root.radiusValue() - min) / range) * 50;
  });

  private readonly angleLabel = computed(() =>
    channelLabel(this.root.colorSpace(), this.root.angleChannelKey()),
  );

  private readonly radiusLabel = computed(() =>
    channelLabel(this.root.colorSpace(), this.root.radiusChannelKey()),
  );

  protected readonly tabIndex = computed(() => (this.root.isDisabled() ? null : 0));

  protected readonly label = computed(
    () => this.ariaLabelAttr ?? `${this.angleLabel()}, ${this.radiusLabel()}`,
  );

  protected readonly valueText = computed(() => {
    const colorSpace = this.root.colorSpace();
    const angle = formatChannelValue(colorSpace, this.root.angleChannelKey(), this.root.angleValue());
    const radius = formatChannelValue(
      colorSpace,
      this.root.radiusChannelKey(),
      this.root.radiusValue(),
    );
    return `${this.angleLabel()} ${angle}, ${this.radiusLabel()} ${radius}`;
  });

  protected readonly transform = computed(
    () =>
      `rotate(${this.angleDeg()}deg) translateY(-${this.radiusPercent()}cqmin) translate(-50%, -50%)`,
  );
}

// packages/vue/src/components/ColorWheel/ColorWheelThumb.vue
<script lang="ts">
import type { PrimitiveProps } from "reka-ui";

export interface ColorWheelThumbProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
}
</script>

<script setup lang="ts">
import { computed, onMounted, onUnmounted } from "vue";
import { Primitive, useForwardExpose } from "reka-ui";
import { channelLabel, formatChannelValue } from "../../shared/channel-labels";
import { injectColorWheelRootContext } from "./ColorWheelRoot.vue";

withDefaults(defineProps<ColorWheelThumbProps>(), { as: "span" });

const rootContext = injectColorWheelRootContext();
const { forwardRef, currentElement: thumbElement } = useForwardExpose();

onMounted(() => {
  if (thumbElement.value)
    rootContext.thumbElement.value = thumbElement.value;
});
onUnmounted(() => {
  if (rootContext.thumbElement.value === thumbElement.value)
    rootContext.thumbElement.value = undefined;
});

const angleDeg = computed(() => {
  const range = rootContext.angleMax.value - rootContext.angleMin.value;
  if (range === 0) return rootContext.startAngle.value;
  const normalized = (rootContext.currentAngleValue.value - rootContext.angleMin.value) / range;
  return normalized * 360 + rootContext.startAngle.value;
});

const radiusPercent = computed(() => {
  const range = rootContext.radiusMax.value - rootContext.radiusMin.value;
  if (range === 0) return 0;
  return (rootContext.currentRadiusValue.value - rootContext.radiusMin.value) / range * 50;
});

const angleLabel = computed(() => channelLabel(rootContext.colorSpace.value, rootContext.angleChannelKey.value));
const radiusLabel = computed(() => channelLabel(rootContext.colorSpace.value, rootContext.radiusChannelKey.value));
const ariaLabel = computed(() => `${angleLabel.value}, ${radiusLabel.value}`);
const ariaValueText = computed(() => {
  const space = rootContext.colorSpace.value;
  const a = formatChannelValue(space, rootContext.angleChannelKey.value, rootContext.currentAngleValue.value);
  const r = formatChannelValue(space, rootContext.radiusChannelKey.value, rootContext.currentRadiusValue.value);
  return `${angleLabel.value} ${a}, ${radiusLabel.value} ${r}`;
});
</script>

<template>
  <Primitive
    :ref="forwardRef"
    role="slider"
    :tabindex="rootContext.disabled.value ? undefined : 0"
    :aria-label="($attrs['aria-label'] as string) || ariaLabel"
    :aria-valuenow="rootContext.currentAngleValue.value"
    :aria-valuemin="rootContext.angleMin.value"
    :aria-valuemax="rootContext.angleMax.value"
    :aria-valuetext="ariaValueText"
    aria-roledescription="Color thumb"
    :aria-disabled="rootContext.disabled.value || undefined"
    :data-disabled="rootContext.disabled.value ? '' : undefined"
    :as-child="asChild"
    :as="as"
    :style="{
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: `rotate(${angleDeg}deg) translateY(-${radiusPercent}cqmin) translate(-50%, -50%)`,
      transformOrigin: '0 0',
    }"
  >
    <slot />
  </Primitive>
</template>
