// packages/react/src/components/color-wheel/thumb/ColorWheelThumb.tsx
import { forwardRef, useEffect, useMemo, useRef, type ComponentPropsWithoutRef } from "react";
import { channelLabel, formatChannelValue } from "@urcolor/shared";
import { useColorWheelContext } from "../root/ColorWheelRootContext";

export interface ColorWheelThumbProps extends ComponentPropsWithoutRef<"span"> {}

export const ColorWheelThumb = forwardRef<HTMLSpanElement, ColorWheelThumbProps>(
  function ColorWheelThumb({ style, children, ...props }, ref) {
    const ctx = useColorWheelContext();
    const elRef = useRef<HTMLSpanElement | null>(null);

    useEffect(() => {
      ctx.thumbElement.current = elRef.current ?? undefined;
      return () => {
        if (ctx.thumbElement.current === elRef.current) ctx.thumbElement.current = undefined;
      };
    }, [ctx]);

    const angleDeg = useMemo(() => {
      const range = ctx.angleMax - ctx.angleMin;
      if (range === 0) return ctx.startAngle;
      return ((ctx.currentAngleValue - ctx.angleMin) / range) * 360 + ctx.startAngle;
    }, [ctx.currentAngleValue, ctx.angleMin, ctx.angleMax, ctx.startAngle]);

    const radiusPercent = useMemo(() => {
      const range = ctx.radiusMax - ctx.radiusMin;
      if (range === 0) return 0;
      return ((ctx.currentRadiusValue - ctx.radiusMin) / range) * 50;
    }, [ctx.currentRadiusValue, ctx.radiusMin, ctx.radiusMax]);

    const angleLabelText = channelLabel(ctx.colorSpace, ctx.angleChannelKey);
    const radiusLabelText = channelLabel(ctx.colorSpace, ctx.radiusChannelKey);
    const ariaLabel = `${angleLabelText}, ${radiusLabelText}`;
    const ariaValueText
      = `${angleLabelText} ${formatChannelValue(ctx.colorSpace, ctx.angleChannelKey, ctx.currentAngleValue)}, `
        + `${radiusLabelText} ${formatChannelValue(ctx.colorSpace, ctx.radiusChannelKey, ctx.currentRadiusValue)}`;

    return (
      <span
        ref={(el) => {
          elRef.current = el;
          if (typeof ref === "function") ref(el);
          else if (ref) ref.current = el;
        }}
        role="slider"
        tabIndex={ctx.disabled ? undefined : 0}
        aria-label={ariaLabel}
        aria-valuenow={ctx.currentAngleValue}
        aria-valuemin={ctx.angleMin}
        aria-valuemax={ctx.angleMax}
        aria-valuetext={ariaValueText}
        aria-roledescription="Color thumb"
        aria-disabled={ctx.disabled || undefined}
        data-disabled={ctx.disabled ? "" : undefined}
        style={{
          position: "absolute",
          top: "50%",
          left: "50%",
          transform: `rotate(${angleDeg}deg) translateY(-${radiusPercent}cqmin) translate(-50%, -50%)`,
          transformOrigin: "0 0",
          ...style,
        }}
        {...props}
      >
        {children}
      </span>
    );
  },
);

// packages/vue/src/components/ColorWheel/ColorWheelThumb.vue
<script lang="ts">
import type { PrimitiveProps } from "reka-ui";

export interface ColorWheelThumbProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
}
</script>

<script setup lang="ts">
import { computed, onMounted, onUnmounted } from "vue";
import { Primitive, useForwardExpose } from "reka-ui";
import { channelLabel, formatChannelValue } from "../../shared/channel-labels";
import { injectColorWheelRootContext } from "./ColorWheelRoot.vue";

withDefaults(defineProps<ColorWheelThumbProps>(), { as: "span" });

const rootContext = injectColorWheelRootContext();
const { forwardRef, currentElement: thumbElement } = useForwardExpose();

onMounted(() => {
  if (thumbElement.value)
    rootContext.thumbElement.value = thumbElement.value;
});
onUnmounted(() => {
  if (rootContext.thumbElement.value === thumbElement.value)
    rootContext.thumbElement.value = undefined;
});

const angleDeg = computed(() => {
  const range = rootContext.angleMax.value - rootContext.angleMin.value;
  if (range === 0) return rootContext.startAngle.value;
  const normalized = (rootContext.currentAngleValue.value - rootContext.angleMin.value) / range;
  return normalized * 360 + rootContext.startAngle.value;
});

const radiusPercent = computed(() => {
  const range = rootContext.radiusMax.value - rootContext.radiusMin.value;
  if (range === 0) return 0;
  return (rootContext.currentRadiusValue.value - rootContext.radiusMin.value) / range * 50;
});

const angleLabel = computed(() => channelLabel(rootContext.colorSpace.value, rootContext.angleChannelKey.value));
const radiusLabel = computed(() => channelLabel(rootContext.colorSpace.value, rootContext.radiusChannelKey.value));
const ariaLabel = computed(() => `${angleLabel.value}, ${radiusLabel.value}`);
const ariaValueText = computed(() => {
  const space = rootContext.colorSpace.value;
  const a = formatChannelValue(space, rootContext.angleChannelKey.value, rootContext.currentAngleValue.value);
  const r = formatChannelValue(space, rootContext.radiusChannelKey.value, rootContext.currentRadiusValue.value);
  return `${angleLabel.value} ${a}, ${radiusLabel.value} ${r}`;
});
</script>

<template>
  <Primitive
    :ref="forwardRef"
    role="slider"
    :tabindex="rootContext.disabled.value ? undefined : 0"
    :aria-label="($attrs['aria-label'] as string) || ariaLabel"
    :aria-valuenow="rootContext.currentAngleValue.value"
    :aria-valuemin="rootContext.angleMin.value"
    :aria-valuemax="rootContext.angleMax.value"
    :aria-valuetext="ariaValueText"
    aria-roledescription="Color thumb"
    :aria-disabled="rootContext.disabled.value || undefined"
    :data-disabled="rootContext.disabled.value ? '' : undefined"
    :as-child="asChild"
    :as="as"
    :style="{
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: `rotate(${angleDeg}deg) translateY(-${radiusPercent}cqmin) translate(-50%, -50%)`,
      transformOrigin: '0 0',
    }"
  >
    <slot />
  </Primitive>
</template>
