// packages/vue/src/components/ColorWheel/ColorWheelThumbX.vue
<script lang="ts">
import type { PrimitiveProps } from "reka-ui";
export interface ColorWheelThumbXProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
}
</script>

<script setup lang="ts">
import { computed, onMounted, onUnmounted } from "vue";
import { Primitive, useForwardExpose } from "reka-ui";
import { injectColorWheelRootContext } from "./ColorWheelRoot.vue";

withDefaults(defineProps<ColorWheelThumbXProps>(), {
  as: "span",
});

const rootContext = injectColorWheelRootContext();
const { forwardRef, currentElement: thumbElement } = useForwardExpose();

onMounted(() => {
  if (thumbElement.value)
    rootContext.thumbXElement.value = thumbElement.value;
});
onUnmounted(() => {
  if (rootContext.thumbXElement.value === thumbElement.value)
    rootContext.thumbXElement.value = undefined;
});
</script>

<template>
  <Primitive
    :ref="forwardRef"
    role="slider"
    :tabindex="rootContext.disabled.value ? undefined : (rootContext.activeDirection.value === 'x' ? 0 : -1)"
    :data-disabled="rootContext.disabled.value ? '' : undefined"
    aria-orientation="horizontal"
    aria-label="angle"
    :aria-valuenow="rootContext.currentAngleValue.value"
    :aria-valuemin="rootContext.angleMin.value"
    :aria-valuemax="rootContext.angleMax.value"
    :as-child="asChild"
    :as="as"
    :style="{
      position: 'absolute',
      display: 'block',
      width: '100%',
      height: '100%',
    }"
    @focus="() => {
      rootContext.activeDirection.value = 'x'
    }"
  >
    <slot />
  </Primitive>
</template>

// packages/react/src/components/ColorWheel/ColorWheelThumbX.tsx
import { forwardRef, useCallback, useEffect, useRef, type ComponentPropsWithoutRef } from "react";
import { useColorWheelContext } from "./ColorWheelContext";

export interface ColorWheelThumbXProps extends ComponentPropsWithoutRef<"span"> {}

export const ColorWheelThumbX = forwardRef<HTMLSpanElement, ColorWheelThumbXProps>(
  function ColorWheelThumbX(props, ref) {
    const ctx = useColorWheelContext();
    const elRef = useRef<HTMLSpanElement>(null);

    useEffect(() => {
      if (elRef.current) ctx.thumbXElement.current = elRef.current;
      return () => { if (ctx.thumbXElement.current === elRef.current) ctx.thumbXElement.current = undefined; };
    }, [ctx]);

    const handleFocus = useCallback(() => ctx.setActiveDirection("x"), [ctx]);

    return (
      <span
        ref={(el) => { (elRef as React.MutableRefObject<HTMLSpanElement | null>).current = el; if (typeof ref === "function") ref(el); else if (ref) ref.current = el; }}
        role="slider" tabIndex={ctx.disabled ? undefined : (ctx.activeDirection === "x" ? 0 : -1)}
        aria-orientation="horizontal" aria-valuenow={ctx.currentAngleValue}
        aria-valuemin={ctx.angleMin} aria-valuemax={ctx.angleMax}
        data-disabled={ctx.disabled ? "" : undefined}
        onFocus={handleFocus}
        style={{ position: "absolute", display: "block", width: "100%", height: "100%" }}
        {...props}
      />
    );
  },
);
