// packages/vue/src/components/ColorWheel/ColorWheelThumb.vue
<script lang="ts">
import type { PrimitiveProps } from "reka-ui";

export interface ColorWheelThumbProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
}
</script>

<script setup lang="ts">
import { computed } from "vue";
import { Primitive, useForwardExpose } from "reka-ui";
import { injectColorWheelRootContext } from "./ColorWheelRoot.vue";
import ColorWheelThumbX from "./ColorWheelThumbX.vue";
import ColorWheelThumbY from "./ColorWheelThumbY.vue";

withDefaults(defineProps<ColorWheelThumbProps>(), { as: "span" });

const rootContext = injectColorWheelRootContext();
useForwardExpose();

const angleDeg = computed(() => {
  const range = rootContext.angleMax.value - rootContext.angleMin.value;
  if (range === 0) return rootContext.startAngle.value;
  const normalized = (rootContext.currentAngleValue.value - rootContext.angleMin.value) / range;
  return normalized * 360 + rootContext.startAngle.value;
});

const radiusPercent = computed(() => {
  const range = rootContext.radiusMax.value - rootContext.radiusMin.value;
  if (range === 0) return 0;
  return (rootContext.currentRadiusValue.value - rootContext.radiusMin.value) / range * 50;
});
</script>

<template>
  <Primitive
    aria-roledescription="2D slider"
    :aria-disabled="rootContext.disabled.value"
    :data-disabled="rootContext.disabled.value ? '' : undefined"
    :as-child="asChild"
    :as="as"
    :style="{
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: `rotate(${angleDeg}deg) translateY(-${radiusPercent}cqmin) translate(-50%, -50%)`,
      transformOrigin: '0 0',
    }"
  >
    <ColorWheelThumbX />
    <ColorWheelThumbY />
    <slot />
  </Primitive>
</template>

// packages/react/src/components/ColorWheel/ColorWheelThumb.tsx
import { forwardRef, useMemo, type ComponentPropsWithoutRef } from "react";
import { useColorWheelContext } from "./ColorWheelContext";

export interface ColorWheelThumbProps extends ComponentPropsWithoutRef<"span"> {}

export const ColorWheelThumb = forwardRef<HTMLSpanElement, ColorWheelThumbProps>(
  function ColorWheelThumb({ style, children, ...props }, ref) {
    const ctx = useColorWheelContext();

    const angleDeg = useMemo(() => {
      const range = ctx.angleMax - ctx.angleMin;
      if (range === 0) return ctx.startAngle;
      return ((ctx.currentAngleValue - ctx.angleMin) / range) * 360 + ctx.startAngle;
    }, [ctx.currentAngleValue, ctx.angleMin, ctx.angleMax, ctx.startAngle]);

    const radiusPercent = useMemo(() => {
      const range = ctx.radiusMax - ctx.radiusMin;
      if (range === 0) return 0;
      return ((ctx.currentRadiusValue - ctx.radiusMin) / range) * 50;
    }, [ctx.currentRadiusValue, ctx.radiusMin, ctx.radiusMax]);

    return (
      <span
        ref={ref}
        aria-roledescription="2D slider"
        data-disabled={ctx.disabled ? "" : undefined}
        style={{
          position: "absolute",
          top: "50%",
          left: "50%",
          transform: `rotate(${angleDeg}deg) translateY(-${radiusPercent}cqmin) translate(-50%, -50%)`,
          transformOrigin: "0 0",
          ...style,
        }}
        {...props}
      >
        {children}
      </span>
    );
  },
);
