// packages/vue/src/components/ColorWheel/ColorWheelGradient.vue
<script lang="ts">
import type { PrimitiveProps } from "reka-ui";

export interface ColorWheelGradientProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
  channelOverrides?: Record<string, number> | false;
}
</script>

<script setup lang="ts">
import { ref } from "vue";
import { useForwardExpose, Primitive } from "reka-ui";
import { samplePolarGrid, getChannelConfig } from "@urcolor/core";
import { applyChannelOverrides, renderToCanvas, useGradientCanvas } from "../../shared/useGradientCanvas";
import { injectColorWheelRootContext } from "./ColorWheelRoot.vue";

const props = withDefaults(defineProps<ColorWheelGradientProps>(), {
  as: "span",
  channelOverrides: () => ({ alpha: 1 }),
});

const rootContext = injectColorWheelRootContext();
useForwardExpose();

const canvasRef = ref<HTMLCanvasElement | null>(null);

function paint(canvas: HTMLCanvasElement) {
  const colorSpace = rootContext.colorSpace.value;
  const baseColor = rootContext.colorRef.value;
  if (!baseColor) return;

  const overriddenBase = applyChannelOverrides(baseColor, colorSpace, props.channelOverrides);
  const angleCfg = getChannelConfig(colorSpace, rootContext.angleChannelKey.value);
  const radiusCfg = getChannelConfig(colorSpace, rootContext.radiusChannelKey.value);
  if (!angleCfg || !radiusCfg) return;

  const aMin = angleCfg.nativeMin ?? angleCfg.min;
  const aMax = angleCfg.nativeMax ?? angleCfg.max;
  const rMin = radiusCfg.nativeMin ?? radiusCfg.min;
  const rMax = radiusCfg.nativeMax ?? radiusCfg.max;

  const sampleSize = 128;
  const pixels = samplePolarGrid(
    overriddenBase, colorSpace,
    rootContext.angleChannelKey.value, rootContext.radiusChannelKey.value,
    aMin, aMax, rMin, rMax,
    sampleSize, sampleSize,
    rootContext.startAngle.value,
  );
  renderToCanvas(canvas, pixels, sampleSize, sampleSize);
}

useGradientCanvas({
  canvas: canvasRef,
  sources: () => [
    props.channelOverrides,
    rootContext.colorSpace.value, rootContext.angleChannelKey.value, rootContext.radiusChannelKey.value,
    rootContext.colorRef.value, rootContext.startAngle.value,
  ],
  paint,
  isDragging: rootContext.isDragging,
});
</script>

<template>
  <Primitive :as-child="asChild" :as="as" :data-disabled="rootContext.disabled.value ? '' : undefined">
    <canvas
      ref="canvasRef"
      :style="{ position: 'absolute', inset: '0', width: '100%', height: '100%', pointerEvents: 'none', clipPath: 'circle(50%)' }"
    />
    <slot />
  </Primitive>
</template>

// packages/react/src/components/ColorWheel/ColorWheelGradient.tsx
import { forwardRef, useCallback, useEffect, useRef, type ComponentPropsWithoutRef } from "react";
import { Color } from "internationalized-color";
import { samplePolarGrid, getChannelConfig } from "@urcolor/core";
import { useColorWheelContext } from "./ColorWheelContext";

export interface ColorWheelGradientProps extends ComponentPropsWithoutRef<"span"> {
  channelOverrides?: Record<string, number> | false;
}

function renderToCanvas(canvas: HTMLCanvasElement, pixels: Uint8ClampedArray, size: number) {
  const ctx = canvas.getContext("2d");
  if (!ctx) return;
  const dpr = typeof devicePixelRatio !== "undefined" ? devicePixelRatio : 1;
  const w = Math.round(canvas.clientWidth * dpr);
  const h = Math.round(canvas.clientHeight * dpr);
  if (canvas.width !== w || canvas.height !== h) { canvas.width = w; canvas.height = h; }
  const pixelData = new Uint8ClampedArray(pixels.buffer) as unknown as Uint8ClampedArray<ArrayBuffer>;
  const imageData = new ImageData(pixelData, size, size);
  const offscreen = new OffscreenCanvas(size, size);
  const offCtx = offscreen.getContext("2d");
  if (!offCtx) return;
  offCtx.putImageData(imageData, 0, 0);
  ctx.clearRect(0, 0, w, h);
  const cx = w / 2, cy = h / 2;
  const r = Math.min(cx, cy);
  ctx.save();
  ctx.beginPath();
  ctx.arc(cx, cy, r, 0, Math.PI * 2);
  ctx.clip();
  ctx.imageSmoothingEnabled = true;
  ctx.imageSmoothingQuality = "high";
  ctx.drawImage(offscreen, 0, 0, w, h);
  ctx.restore();
}

export const ColorWheelGradient = forwardRef<HTMLSpanElement, ColorWheelGradientProps>(
  function ColorWheelGradient({ channelOverrides = { alpha: 1 }, style, children, ...props }, ref) {
    const ctx = useColorWheelContext();
    const canvasRef = useRef<HTMLCanvasElement | null>(null);

    const render = useCallback(() => {
      const canvas = canvasRef.current;
      if (!canvas || !ctx.colorRef) return;
      let baseColor = ctx.colorRef;
      if (channelOverrides) {
        const updates: Record<string, number> = {};
        for (const [k, v] of Object.entries(channelOverrides)) {
          if (k === "alpha") baseColor = baseColor.set({ alpha: v });
          else updates[k] = v;
        }
        if (Object.keys(updates).length > 0) baseColor = baseColor.set({ mode: ctx.colorSpace, ...updates });
      }

      const angleCfg = getChannelConfig(ctx.colorSpace, ctx.angleChannelKey);
      const radiusCfg = getChannelConfig(ctx.colorSpace, ctx.radiusChannelKey);
      if (!angleCfg || !radiusCfg) return;

      const aMin = angleCfg.culoriMin ?? angleCfg.min;
      const aMax = angleCfg.culoriMax ?? angleCfg.max;
      const rMin = radiusCfg.culoriMin ?? radiusCfg.min;
      const rMax = radiusCfg.culoriMax ?? radiusCfg.max;

      const size = 128;
      const pixels = samplePolarGrid(
        baseColor, ctx.colorSpace,
        ctx.angleChannelKey, ctx.radiusChannelKey,
        aMin, aMax, rMin, rMax,
        size, size, ctx.startAngle,
      );
      renderToCanvas(canvas, pixels, size);
    }, [ctx.colorRef, ctx.colorSpace, ctx.angleChannelKey, ctx.radiusChannelKey, ctx.startAngle, ctx.isDragging, channelOverrides]);

    useEffect(() => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      if (!ctx.isDragging) render();
      const observer = new ResizeObserver(() => render());
      observer.observe(canvas);
      return () => observer.disconnect();
    }, [render, ctx.isDragging]);

    useEffect(() => { if (!ctx.isDragging) render(); }, [ctx.isDragging]);

    useEffect(() => () => {
      const canvas = canvasRef.current;
      if (canvas) { const gl = canvas.getContext("webgl"); if (gl) gl.getExtension("WEBGL_lose_context")?.loseContext(); }
    }, []);

    return (
      <span ref={ref} data-disabled={ctx.disabled ? "" : undefined} style={style} {...props}>
        <canvas ref={canvasRef} style={{ position: "absolute", inset: "0", width: "100%", height: "100%", pointerEvents: "none" }} />
        {children}
      </span>
    );
  },
);
