// packages/vue/src/components/ColorRing/ColorRingThumb.vue
<script lang="ts">
import type { PrimitiveProps } from "reka-ui";

export interface ColorRingThumbProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
}
</script>

<script setup lang="ts">
import { computed, onMounted, onUnmounted } from "vue";
import { Primitive, useForwardExpose } from "reka-ui";
import { injectColorRingRootContext } from "./ColorRingRoot.vue";

withDefaults(defineProps<ColorRingThumbProps>(), { as: "span" });

const rootContext = injectColorRingRootContext();
const { forwardRef, currentElement: thumbEl } = useForwardExpose();

onMounted(() => {
  if (thumbEl.value)
    rootContext.thumbElement.value = thumbEl.value;
});
onUnmounted(() => {
  if (rootContext.thumbElement.value === thumbEl.value)
    rootContext.thumbElement.value = undefined;
});

const angleDeg = computed(() => {
  const range = rootContext.max.value - rootContext.min.value;
  if (range === 0) return rootContext.startAngle.value;
  const normalized = (rootContext.currentValue.value - rootContext.min.value) / range;
  return normalized * 360 + rootContext.startAngle.value;
});
</script>

<template>
  <Primitive
    :ref="forwardRef"
    role="slider"
    tabindex="0"
    :aria-valuenow="rootContext.currentValue.value"
    :aria-valuemin="rootContext.min.value"
    :aria-valuemax="rootContext.max.value"
    :aria-disabled="rootContext.disabled.value"
    :data-disabled="rootContext.disabled.value ? '' : undefined"
    :as-child="asChild"
    :as="as"
    :style="{
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: `rotate(${angleDeg}deg) translateY(-${(1 + rootContext.innerRadius.value) / 2 * 50}cqmin) translate(-50%, -50%)`,
      transformOrigin: '0 0',
    }"
  >
    <slot />
  </Primitive>
</template>

// packages/react/src/components/color-ring/thumb/ColorRingThumb.tsx
import { forwardRef, useEffect, useMemo, useRef, type ComponentPropsWithoutRef } from "react";
import { useColorRingContext } from "../root/ColorRingRootContext";

export interface ColorRingThumbProps extends ComponentPropsWithoutRef<"span"> {}

export const ColorRingThumb = forwardRef<HTMLSpanElement, ColorRingThumbProps>(
  function ColorRingThumb({ style, ...props }, ref) {
    const ctx = useColorRingContext();
    const elRef = useRef<HTMLSpanElement>(null);

    useEffect(() => {
      if (elRef.current) ctx.thumbElement.current = elRef.current;
      return () => {
        if (ctx.thumbElement.current === elRef.current) ctx.thumbElement.current = undefined;
      };
    }, [ctx]);

    const angleDeg = useMemo(() => {
      const range = ctx.max - ctx.min;
      if (range === 0) return ctx.startAngle;
      const normalized = (ctx.currentValue - ctx.min) / range;
      return normalized * 360 + ctx.startAngle;
    }, [ctx.currentValue, ctx.min, ctx.max, ctx.startAngle]);

    return (
      <span
        ref={(el) => {
          elRef.current = el;
          if (typeof ref === "function") ref(el);
          else if (ref) ref.current = el;
        }}
        role="slider"
        tabIndex={0}
        aria-valuenow={ctx.currentValue}
        aria-valuemin={ctx.min}
        aria-valuemax={ctx.max}
        aria-disabled={ctx.disabled}
        data-disabled={ctx.disabled ? "" : undefined}
        style={{
          position: "absolute",
          top: "50%",
          left: "50%",
          transform: `rotate(${angleDeg}deg) translateY(-${(1 + ctx.innerRadius) / 2 * 50}cqmin) translate(-50%, -50%)`,
          transformOrigin: "0 0",
          ...style,
        }}
        {...props}
      />
    );
  },
);
