// packages/react/src/components/color-ring/gradient/ColorRingGradient.tsx
import { forwardRef, useCallback, useEffect, useRef, type ComponentPropsWithoutRef } from "react";
import { applyChannelOverrides, channelStops, cssConicStops, paintRingSurface, type GradientRenderer } from "@urcolor/shared";
import { useColorRingContext } from "../root/ColorRingRootContext";
import { CHECKERBOARD_STYLE } from "../../../utils";
import { CssGradientLayers, resolveCssGradient } from "../../../cssGradient";

export interface ColorRingGradientProps extends ComponentPropsWithoutRef<"span"> {
  /**
   * Which painter to use.
   * - `"auto"` (default) - CSS when an exact recipe exists, canvas otherwise
   * - `"css"` - force CSS; falls back to the canvas with a dev warning if none exists
   * - `"canvas"` - force the canvas painter
   */
  renderer?: GradientRenderer;
  channelOverrides?: Record<string, number> | false;
}

export const ColorRingGradient = forwardRef<HTMLSpanElement, ColorRingGradientProps>(
  function ColorRingGradient({ renderer = "auto", channelOverrides = { alpha: 1 }, style, children, ...props }, ref) {
    const rootCtx = useColorRingContext();
    const canvasRef = useRef<HTMLCanvasElement | null>(null);

    // The annulus is cut here and nowhere else: the canvas paints the full
    // square and this mask — which applies to the element and every descendant,
    // canvas included — hides the hole and the corners. Clipping the canvas as
    // well used to leave a seam, because the two edges are rasterised
    // independently and their partial coverage multiplies along the boundary.
    //
    // The ±0.5px on the stops is what antialiases the edges: a gradient hard
    // stop (two stops at one position) rasterises without any, so both circles
    // came out visibly stepped.
    const maskP = rootCtx.innerRadius * 100;
    const checkerboardMask = `radial-gradient(circle closest-side at center, transparent calc(${maskP}% - 0.5px), #000 calc(${maskP}% + 0.5px), #000 calc(100% - 0.5px), transparent 100%)`;

    // `sampleConicRing` writes an opaque alpha byte for every pixel, so the CSS
    // stops drop the base color's alpha to match rather than tinting the ring.
    const cssLayers = resolveCssGradient(renderer, "ColorRingGradient", () => {
      const baseColor = rootCtx.colorRef;
      if (!baseColor) return null;
      const overridden = applyChannelOverrides(baseColor, rootCtx.colorSpace, channelOverrides).withAlpha(1);
      const stops = channelStops(overridden, rootCtx.colorSpace, rootCtx.channelKey);
      return stops && cssConicStops(stops, rootCtx.startAngle);
    });

    const render = useCallback(() => {
      const canvas = canvasRef.current;
      if (!canvas || !rootCtx.colorRef) return;
      paintRingSurface({
        canvas,
        color: rootCtx.colorRef,
        colorSpace: rootCtx.colorSpace,
        channel: rootCtx.channelKey,
        startAngle: rootCtx.startAngle,
        overrides: channelOverrides,
      });
      // `innerRadius` is not a dependency: it only moves the mask, and the
      // pixels the canvas paints are the same at every radius.
    }, [rootCtx.colorRef, rootCtx.colorSpace, rootCtx.channelKey, rootCtx.startAngle, channelOverrides]);

    useEffect(() => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      if (!rootCtx.isDragging) render();
      const observer = new ResizeObserver(() => render());
      observer.observe(canvas);
      return () => observer.disconnect();
    }, [render, rootCtx.isDragging]);

    useEffect(() => {
      if (!rootCtx.isDragging) render();
    }, [rootCtx.isDragging]);

    useEffect(() => {
      return () => {
        const canvas = canvasRef.current;
        if (canvas) {
          const gl = canvas.getContext("webgl");
          if (gl) gl.getExtension("WEBGL_lose_context")?.loseContext();
        }
      };
    }, []);

    return (
      <span ref={ref} data-disabled={rootCtx.disabled ? "" : undefined} style={{ ...CHECKERBOARD_STYLE, maskImage: checkerboardMask, WebkitMaskImage: checkerboardMask, ...style }} {...props}>
        {cssLayers
          ? <CssGradientLayers layers={cssLayers} />
          : (
              <canvas
                ref={canvasRef}
                style={{ position: "absolute", inset: "0", width: "100%", height: "100%", pointerEvents: "none" }}
              />
            )}
        {children}
      </span>
    );
  },
);

// packages/svelte/src/lib/components/color-ring/gradient/ColorRingGradient.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { GradientRenderer } from "@urcolor/shared";
  import type { ChildSnippetArgs } from "../../../shared/child.js";

  export interface ColorRingGradientProps extends HTMLAttributes<HTMLSpanElement> {
    /**
     * Lock channels to fixed values in the gradient.
     * - `{ alpha: 1 }` (default) — lock alpha to 1
     * - `false` — no overrides
     */
    channelOverrides?: Record<string, number> | false;
    /**
     * Which painter to use.
     * - `"auto"` (default) — CSS when an exact recipe exists, canvas otherwise
     * - `"css"` — force CSS; falls back to the canvas with a dev warning if none exists
     * - `"canvas"` — force the canvas painter
     */
    renderer?: GradientRenderer;
    /**
     * Replaces the default `<canvas>`; receives its props, including the paint
     * attachment. The checkerboard-and-mask wrapper is always rendered by this part.
     */
    child?: Snippet<[ChildSnippetArgs]>;
  }
</script>

<script lang="ts">
  import { createAttachmentKey } from "svelte/attachments";
  import { applyChannelOverrides, channelStops, CHECKERBOARD_CSS, cssConicStops, DATA_DISABLED, paintRingSurface } from "@urcolor/shared";
  import { CSS_GRADIENT_ROOT_STYLE, cssLayerStyle, resolveCssGradient } from "../../../shared/cssGradient.svelte.js";
  import type { ChildProps } from "../../../shared/child.js";
  import { gradientAttachment } from "../../../shared/gradient.svelte.js";
  import { colorRingContext } from "../root/context.svelte.js";

  let {
    channelOverrides = { alpha: 1 },
    class: className,
    style,
    renderer = "auto",
    children,
    child,
    ...rest
  }: ColorRingGradientProps = $props();

  const context = colorRingContext.get();

  /**
   * The annulus is cut here and nowhere else: the canvas paints the full square
   * and this mask — which applies to the element and every descendant, canvas
   * included — hides the hole and the corners. Clipping the canvas as well left
   * a seam, because the two edges rasterise independently and their partial
   * coverage multiplies along the boundary.
   *
   * The ±0.5px on the stops is what antialiases the edges: a gradient hard stop
   * (two stops at one position) rasterises without any, so both circles came
   * out visibly stepped.
   */
  const mask = $derived.by(() => {
    const p = context.innerRadius * 100;
    return `radial-gradient(circle closest-side at center, transparent calc(${p}% - 0.5px), #000 calc(${p}% + 0.5px), #000 calc(100% - 0.5px), transparent 100%)`;
  });

  /** Applies the alpha and non-alpha overrides to a base colour. */
  function paint(canvas: HTMLCanvasElement): void {
    paintRingSurface({
      canvas,
      color: context.color,
      colorSpace: context.colorSpace,
      channel: context.channel,
      startAngle: context.startAngle,
      overrides: channelOverrides,
    });
  }

  const paintCanvas = gradientAttachment(paint);
  const attachmentKey = createAttachmentKey();

  /**
   * Stable identity, so the attachment is not torn down on every render; it
   * still re-runs whenever the reactive state `paint` reads changes.
   */
  function canvasAttachment(node: HTMLCanvasElement): () => void {
    const cleanup = paintCanvas(node);
    return () => {
      cleanup();
      // WebGL contexts are a capped per-document resource; release ours.
      node.getContext("webgl")?.getExtension("WEBGL_lose_context")?.loseContext();
    };
  }

  // `sampleConicRing` writes an opaque alpha byte for every pixel, so the CSS
  // stops drop the base colour's alpha to match rather than tinting the ring.
  const cssLayers = $derived.by(() => resolveCssGradient(renderer, "ColorRingGradient", !!child, () => {
    const stops = channelStops(
      applyChannelOverrides(context.color, context.colorSpace, channelOverrides).withAlpha(1),
      context.colorSpace,
      context.channel,
    );
    return stops && cssConicStops(stops, context.startAngle);
  }));

  const canvasProps = $derived<ChildProps>({
    style: "position:absolute;inset:0;width:100%;height:100%;pointer-events:none;",
    [attachmentKey]: canvasAttachment,
  });

  const elementProps = $derived<ChildProps>({
    ...rest,
    class: className,
    // The caller's declarations come last so they win the cascade.
    style: `${CHECKERBOARD_CSS}mask-image:${mask};-webkit-mask-image:${mask};${style ?? ""}`,
    [DATA_DISABLED]: context.disabled ? "" : undefined,
  });
</script>

<span {...elementProps}>
  {#if cssLayers}
    <span style={CSS_GRADIENT_ROOT_STYLE}>
      {#each cssLayers as layer, index (index)}
        <span style={cssLayerStyle(layer)}></span>
      {/each}
    </span>
  {:else if child}
    {@render child({ props: canvasProps })}
  {:else}
    <canvas {...canvasProps}></canvas>
  {/if}
  {@render children?.()}
</span>
