// packages/angular/src/components/color-slider/thumb/color-slider-thumb.ts
import { computed, Directive, HostAttributeToken, inject } from "@angular/core";
import {
  channelLabel,
  DATA_DISABLED,
  DATA_DRAGGING,
  DATA_ORIENTATION,
  formatChannelValue,
  sliderAria,
} from "@urcolor/primitives";
import { ColorSliderRoot } from "../root/color-slider-root";

/**
 * The draggable handle. It is only a focus target and an ARIA surface — every
 * value change is owned by the root, whose `keydown` listener sees the events
 * that bubble up from here.
 */
@Directive({
  selector: "[urcColorSliderThumb]",
  exportAs: "urcColorSliderThumb",
  host: {
    "[attr.role]": "role()",
    "[attr.aria-valuenow]": "valueNow()",
    "[attr.aria-valuemin]": "valueMin()",
    "[attr.aria-valuemax]": "valueMax()",
    "[attr.aria-orientation]": "ariaOrientation()",
    "[attr.aria-disabled]": "ariaDisabled()",
    "[attr.aria-label]": "label()",
    "[attr.aria-valuetext]": "valueText()",
    "[attr.tabindex]": "tabIndex()",
    [`[attr.${DATA_ORIENTATION}]`]: "root.orientation()",
    [`[attr.${DATA_DISABLED}]`]: "root.isDisabled() ? '' : null",
    [`[attr.${DATA_DRAGGING}]`]: "root.dragging() ? '' : null",
    "[style.position]": "'absolute'",
    "[style.left]": "left()",
    "[style.top]": "top()",
    "[style.translate]": "'-50% -50%'",
  },
})
export class ColorSliderThumb {
  protected readonly root = inject(ColorSliderRoot);

  /** A consumer's own `aria-label` wins; the channel name is only a fallback. */
  private readonly ariaLabelAttr = inject(new HostAttributeToken("aria-label"), { optional: true });

  private readonly aria = computed(() => sliderAria(this.root.sliderState()));
  private readonly vertical = computed(() => this.root.sliderState().orientation === "vertical");
  private readonly offset = computed(() => `${this.root.position() * 100}%`);

  protected readonly role = computed(() => this.aria().role);
  protected readonly valueNow = computed(() => this.aria()["aria-valuenow"]);
  protected readonly valueMin = computed(() => this.aria()["aria-valuemin"]);
  protected readonly valueMax = computed(() => this.aria()["aria-valuemax"]);
  protected readonly ariaOrientation = computed(() => this.aria()["aria-orientation"]);
  protected readonly ariaDisabled = computed(() => this.aria()["aria-disabled"] ?? null);
  protected readonly tabIndex = computed(() => this.aria().tabindex ?? null);

  protected readonly label = computed(
    () => this.ariaLabelAttr ?? channelLabel(this.root.colorSpace(), this.root.channel()),
  );

  protected readonly valueText = computed(() =>
    formatChannelValue(
      this.root.colorSpace(),
      this.root.channel(),
      this.root.sliderState().value,
    ),
  );

  protected readonly left = computed(() => (this.vertical() ? "50%" : this.offset()));
  protected readonly top = computed(() => (this.vertical() ? this.offset() : "50%"));
}

// packages/svelte/src/lib/components/color-slider/thumb/ColorSliderThumb.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { ChildSnippetArgs } from "../../../shared/child.js";

  export interface ColorSliderThumbProps extends HTMLAttributes<HTMLDivElement> {
    /** Replaces the default element; receives the props it would have received. */
    child?: Snippet<[ChildSnippetArgs]>;
  }
</script>

<script lang="ts">
  import {
    channelLabel,
    DATA_DISABLED,
    DATA_DRAGGING,
    DATA_ORIENTATION,
    formatChannelValue,
    sliderAria,
  } from "@urcolor/primitives";
  import type { ChildProps } from "../../../shared/child.js";
  import { colorSliderContext } from "../root/context.svelte.js";

  let { class: className, style, children, child, ...rest }: ColorSliderThumbProps = $props();

  const context = colorSliderContext.get();

  const state = $derived(context.sliderState);
  const aria = $derived(sliderAria(state));
  const label = $derived(channelLabel(context.colorSpace, context.channel));
  const valueText = $derived(formatChannelValue(context.colorSpace, context.channel, state.value));
  const offset = $derived(context.position * 100);
  const layout = $derived(
    state.orientation === "vertical"
      ? `position:absolute;top:${offset}%;left:50%;translate:-50% -50%;`
      : `position:absolute;left:${offset}%;top:50%;translate:-50% -50%;`,
  );

  const elementProps = $derived<ChildProps>({
    ...rest,
    ...aria,
    // The thumb is only focusable; `keydown` bubbles to the root's attachment,
    // which owns every value change.
    "aria-label": rest["aria-label"] ?? label,
    "aria-valuetext": valueText,
    "class": className,
    // The caller's declarations come last so they win the cascade.
    "style": style ? `${layout}${style}` : layout,
    [DATA_ORIENTATION]: state.orientation,
    [DATA_DISABLED]: state.disabled ? "" : undefined,
    [DATA_DRAGGING]: context.dragging ? "" : undefined,
  });
</script>

{#if child}
  {@render child({ props: elementProps })}
{:else}
  <div {...elementProps}>{@render children?.()}</div>
{/if}
