// packages/angular/src/components/color-field/input/color-field-input.ts
import { Directive, ElementRef, inject } from "@angular/core";
import { DATA_DISABLED, DATA_READONLY } from "@urcolor/shared";
import { ColorFieldRoot } from "../root/color-field-root";

/**
 * The editable text surface, applied to a native `<input>`.
 *
 * It is a `spinbutton` rather than `type="number"`: the field renders suffixed
 * text (`210°`, `50%`, `#ff8800`) that a numeric input would reject, so the
 * stepping keyboard map is provided here instead of by the browser.
 */
@Directive({
  selector: "input[urcColorFieldInput]",
  exportAs: "urcColorFieldInput",
  host: {
    "[attr.type]": "'text'",
    "[attr.role]": "'spinbutton'",
    "[attr.aria-valuenow]": "root.modelValue() ?? null",
    "[attr.autocomplete]": "'off'",
    "[attr.autocorrect]": "'off'",
    "[attr.inputmode]": "'text'",
    "[value]": "root.displayValue()",
    "[disabled]": "root.isDisabled()",
    "[readOnly]": "root.isReadOnly()",
    "[spellcheck]": "false",
    [`[attr.${DATA_DISABLED}]`]: "root.isDisabled() ? '' : null",
    [`[attr.${DATA_READONLY}]`]: "root.isReadOnly() ? '' : null",
    "(input)": "onInput()",
    "(focus)": "onFocus()",
    "(blur)": "onBlur()",
    "(keydown)": "onKeyDown($event)",
  },
})
export class ColorFieldInput {
  protected readonly root = inject(ColorFieldRoot);

  private readonly host = inject<ElementRef<HTMLInputElement>>(ElementRef);

  protected onInput(): void {
    this.root.onInputChange(this.host.nativeElement.value);
  }

  /**
   * Deferred a frame: selecting during `focus` is undone by the click that
   * caused it, so the selection has to outlive the current event loop turn.
   */
  protected onFocus(): void {
    const element = this.host.nativeElement;
    if (typeof requestAnimationFrame === "undefined") {
      element.select();
      return;
    }
    requestAnimationFrame(() => element.select());
  }

  protected onBlur(): void {
    this.root.commitValue(this.root.modelValue());
  }

  protected onKeyDown(event: KeyboardEvent): void {
    if (this.root.isDisabled() || this.root.isReadOnly()) return;
    if (event.key === "Enter") {
      this.root.commitValue(this.root.modelValue());
      return;
    }
    switch (event.key) {
      case "ArrowUp":
        event.preventDefault();
        this.root.handleIncrease();
        break;
      case "ArrowDown":
        event.preventDefault();
        this.root.handleDecrease();
        break;
      case "PageUp":
        event.preventDefault();
        this.root.handleIncrease(10);
        break;
      case "PageDown":
        event.preventDefault();
        this.root.handleDecrease(10);
        break;
      case "Home":
        event.preventDefault();
        this.root.handleMinMaxValue("min");
        break;
      case "End":
        event.preventDefault();
        this.root.handleMinMaxValue("max");
        break;
    }
  }
}

// packages/svelte/src/lib/components/color-field/input/ColorFieldInput.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLInputAttributes } from "svelte/elements";
  import type { ChildSnippetArgs } from "../../../shared/child.js";

  export interface ColorFieldInputProps extends HTMLInputAttributes {
    /** Replaces the default element; receives the props it would have received. */
    child?: Snippet<[ChildSnippetArgs]>;
  }
</script>

<script lang="ts">
  import { createAttachmentKey } from "svelte/attachments";
  import { DATA_DISABLED, DATA_READONLY } from "@urcolor/shared";
  import type { ChildProps } from "../../../shared/child.js";
  import { colorFieldContext } from "../root/context.svelte.js";

  // `children` is pulled out and discarded on purpose: <input> is a void
  // element, so letting it fall through to `...rest` would spread a snippet
  // onto the DOM.
  let { class: className, style, children: _children, child, ...rest }: ColorFieldInputProps = $props();

  const context = colorFieldContext.get();

  const attachmentKey = createAttachmentKey();

  /**
   * The input's behaviour attachment: text editing, blur/Enter commit, and the
   * spinbutton keyboard map.
   *
   * It travels inside the props object under a `Symbol` key, so a consumer
   * spreading those props onto their own `<input>` — or onto another component —
   * gets the full interaction, which an `oninput` prop bag could not do.
   */
  function interaction(node: HTMLInputElement): () => void {
    const onInput = (): void => context.onInputChange(node.value);
    // Deferred a frame: selecting during `focus` is undone by the click that
    // caused it, so the selection has to outlive the current event loop turn.
    const onFocus = (): void => {
      requestAnimationFrame(() => node.select());
    };
    const onBlur = (): void => context.commitValue(context.modelValue);
    const onKeyDown = (event: KeyboardEvent): void => {
      if (context.disabled || context.readOnly) return;
      if (event.key === "Enter") {
        context.commitValue(context.modelValue);
        return;
      }
      switch (event.key) {
        case "ArrowUp":
          event.preventDefault();
          context.handleIncrease();
          break;
        case "ArrowDown":
          event.preventDefault();
          context.handleDecrease();
          break;
        case "PageUp":
          event.preventDefault();
          context.handleIncrease(10);
          break;
        case "PageDown":
          event.preventDefault();
          context.handleDecrease(10);
          break;
        case "Home":
          event.preventDefault();
          context.handleMinMaxValue("min");
          break;
        case "End":
          event.preventDefault();
          context.handleMinMaxValue("max");
          break;
      }
    };

    node.addEventListener("input", onInput);
    node.addEventListener("focus", onFocus);
    node.addEventListener("blur", onBlur);
    node.addEventListener("keydown", onKeyDown);

    return () => {
      node.removeEventListener("input", onInput);
      node.removeEventListener("focus", onFocus);
      node.removeEventListener("blur", onBlur);
      node.removeEventListener("keydown", onKeyDown);
    };
  }

  const elementProps = $derived<ChildProps>({
    ...rest,
    "type": "text",
    "role": "spinbutton",
    "aria-valuenow": context.modelValue,
    "value": context.displayValue,
    "disabled": context.disabled || undefined,
    "readonly": context.readOnly || undefined,
    "autocomplete": "off",
    "autocorrect": "off",
    "spellcheck": false,
    "inputmode": "text",
    "class": className,
    "style": style,
    [DATA_DISABLED]: context.disabled ? "" : undefined,
    [DATA_READONLY]: context.readOnly ? "" : undefined,
    [attachmentKey]: interaction,
  });
</script>

{#if child}
  {@render child({ props: elementProps })}
{:else}
  <input {...elementProps} />
{/if}
