// packages/react/src/components/ColorTriangle/ColorTriangleThumbZ.tsx
import { forwardRef, useEffect, type ComponentPropsWithoutRef } from "react";
import { useColorTriangleContext } from "./ColorTriangleContext";

export interface ColorTriangleThumbZProps extends ComponentPropsWithoutRef<"span"> {}

export const ColorTriangleThumbZ = forwardRef<HTMLSpanElement, ColorTriangleThumbZProps>(
  function ColorTriangleThumbZ({ style, children, ...props }, ref) {
    const ctx = useColorTriangleContext();

    useEffect(() => {
      return () => { ctx.thumbZElement.current = undefined; };
    }, []);

    return (
      <span
        ref={(el) => {
          if (el) ctx.thumbZElement.current = el;
          if (typeof ref === "function") ref(el);
          else if (ref) ref.current = el;
        }}
        role="slider"
        tabIndex={ctx.disabled ? undefined : (ctx.isThreeChannel ? 0 : (ctx.activeDirection === "z" ? 0 : -1))}
        data-disabled={ctx.disabled ? "" : undefined}
        aria-orientation="horizontal"
        aria-label={ctx.zChannelKey}
        aria-valuenow={ctx.currentZValue}
        aria-valuemin={ctx.zMin}
        aria-valuemax={ctx.zMax}
        onFocus={() => ctx.setActiveDirection("z")}
        style={{ position: "absolute", display: "block", width: "100%", height: "100%", ...style }}
        {...props}
      >
        {children}
      </span>
    );
  },
);

// packages/vue/src/components/ColorTriangle/ColorTriangleThumbZ.vue
<script lang="ts">
import type { PrimitiveProps } from "reka-ui";
export interface ColorTriangleThumbZProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
}
</script>

<script setup lang="ts">
import { onMounted, onUnmounted } from "vue";
import { Primitive, useForwardExpose } from "reka-ui";
import { injectColorTriangleRootContext } from "./ColorTriangleRoot.vue";

withDefaults(defineProps<ColorTriangleThumbZProps>(), {
  as: "span",
});

const rootContext = injectColorTriangleRootContext();
const { forwardRef, currentElement: thumbElement } = useForwardExpose();

onMounted(() => {
  if (thumbElement.value)
    rootContext.thumbZElement.value = thumbElement.value;
});
onUnmounted(() => {
  if (rootContext.thumbZElement.value === thumbElement.value)
    rootContext.thumbZElement.value = undefined;
});
</script>

<template>
  <Primitive
    :ref="forwardRef"
    role="slider"
    :tabindex="rootContext.disabled.value ? undefined : (rootContext.isThreeChannel.value ? 0 : (rootContext.activeDirection.value === 'z' ? 0 : -1))"
    :data-disabled="rootContext.disabled.value ? '' : undefined"
    aria-orientation="horizontal"
    :aria-label="rootContext.zChannelKey.value"
    :aria-valuenow="rootContext.currentZValue.value"
    :aria-valuemin="rootContext.zMin.value"
    :aria-valuemax="rootContext.zMax.value"
    :as-child="asChild"
    :as="as"
    :style="{
      position: 'absolute',
      display: 'block',
      width: '100%',
      height: '100%',
    }"
    @focus="() => {
      rootContext.activeDirection.value = 'z'
    }"
  >
    <slot />
  </Primitive>
</template>
