// packages/react/src/components/ColorTriangle/ColorTriangleRoot.tsx
import { forwardRef, useCallback, useMemo, useRef, useState } from "react";
import { Color } from "internationalized-color";
import { colorSpaces, getChannelConfig, displayToCulori, culoriToDisplay, type ChannelConfig, triangleVertices, clampToTriangle, barycentricCoords, pointInTriangle, type Point } from "@urcolor/core";
import { ColorTriangleContext, type ColorTriangleContextValue, type ActiveDirection } from "./ColorTriangleContext";

export interface ColorTriangleRootProps {
  value?: Color | string | null;
  defaultValue?: Color | string;
  disabled?: boolean;
  colorSpace?: string;
  channelX?: string;
  channelY?: string;
  channelZ?: string;
  rotation?: number;
  inverted?: boolean;
  thumbAlignment?: "contain" | "overflow";
  onValueChange?: (color: Color) => void;
  onValueCommit?: (color: Color) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

function parseColor(v: Color | string | null | undefined): Color | undefined {
  if (!v) return undefined;
  if (v instanceof Color) return v;
  return Color.parse(v) ?? undefined;
}

const ALPHA_CONFIG: ChannelConfig = { key: "alpha", label: "Alpha", min: 0, max: 100, step: 1, format: "percentage", culoriMin: 0, culoriMax: 1 };

export const ColorTriangleRoot = forwardRef<HTMLDivElement, ColorTriangleRootProps>(
  function ColorTriangleRoot(props, ref) {
    const {
      value: valueProp,
      defaultValue: defaultValueProp = "hsl(0, 100%, 50%)",
      disabled = false,
      colorSpace = "hsv",
      channelX: channelXProp,
      channelY: channelYProp,
      channelZ: channelZProp,
      rotation = 0,
      inverted = false,
      thumbAlignment = "overflow",
      onValueChange,
      onValueCommit,
      children,
      className,
      style,
    } = props;

    const isControlled = valueProp !== undefined;
    const [internalColor, setInternalColor] = useState<Color | undefined>(
      () => parseColor(valueProp) ?? parseColor(defaultValueProp),
    );
    const prevValueRef = useRef(valueProp);
    if (valueProp !== prevValueRef.current) {
      prevValueRef.current = valueProp;
      const parsed = parseColor(valueProp);
      if (parsed) setInternalColor(parsed);
    }
    const colorRef = isControlled ? (parseColor(valueProp) ?? internalColor) : internalColor;

    const spaceConfig = colorSpaces[colorSpace];
    const xChannelKey = channelXProp ?? spaceConfig?.channels[1]?.key ?? "s";
    const yChannelKey = channelYProp ?? spaceConfig?.channels[2]?.key ?? "v";
    const zChannelKey = channelZProp;
    const isThreeChannel = zChannelKey != null;

    const xIsAlpha = xChannelKey === "alpha";
    const yIsAlpha = yChannelKey === "alpha";
    const zIsAlpha = zChannelKey === "alpha";
    const xConfig = xIsAlpha ? ALPHA_CONFIG : getChannelConfig(colorSpace, xChannelKey);
    const yConfig = yIsAlpha ? ALPHA_CONFIG : getChannelConfig(colorSpace, yChannelKey);
    const zConfig = zChannelKey ? (zIsAlpha ? ALPHA_CONFIG : getChannelConfig(colorSpace, zChannelKey)) : undefined;

    const xMin = xConfig?.min ?? 0;
    const xMax = xConfig?.max ?? 100;
    const xStep = xConfig?.step ?? 1;
    const yMin = yConfig?.min ?? 0;
    const yMax = yConfig?.max ?? 100;
    const yStep = yConfig?.step ?? 1;
    const zMin = zConfig?.min ?? 0;
    const zMax = zConfig?.max ?? 100;
    const zStep = zConfig?.step ?? 1;

    const vertices = useMemo<[Point, Point, Point]>(() => {
      const [v0, v1, v2] = triangleVertices(1, 1, rotation);
      return inverted ? [v0, v2, v1] : [v0, v1, v2];
    }, [rotation, inverted]);

    const clipPathStyle = useMemo(() => {
      const pts = vertices.map(p => `${(p.x * 100).toFixed(2)}% ${(p.y * 100).toFixed(2)}%`).join(", ");
      return { clipPath: `polygon(${pts})`, ...style };
    }, [vertices, style]);

    function colorToDisplayValues(color: Color | undefined): { x: number; y: number; z: number } {
      if (!color || !xConfig || !yConfig) return { x: xMin, y: yMin, z: zMin };
      const converted = color.to(colorSpace);
      if (!converted) return { x: xMin, y: yMin, z: zMin };
      const rawX = xIsAlpha ? (color.alpha ?? 1) : converted.get(xChannelKey, 0);
      const rawY = yIsAlpha ? (color.alpha ?? 1) : converted.get(yChannelKey, 0);
      const rawZ = zChannelKey ? (zIsAlpha ? (color.alpha ?? 1) : converted.get(zChannelKey, 0)) : 0;
      return {
        x: culoriToDisplay(xConfig, rawX),
        y: culoriToDisplay(yConfig, rawY),
        z: zConfig ? culoriToDisplay(zConfig, rawZ) : zMin,
      };
    }

    const initValues = colorToDisplayValues(colorRef);
    const [currentXValue, setCurrentXValue] = useState(initValues.x);
    const [currentYValue, setCurrentYValue] = useState(initValues.y);
    const [currentZValue, setCurrentZValue] = useState(initValues.z);
    const [isDragging, setIsDragging] = useState(false);
    const [activeDirection, setActiveDirection] = useState<ActiveDirection>("x");

    const prevColorRef = useRef(colorRef);
    if (colorRef !== prevColorRef.current) {
      prevColorRef.current = colorRef;
      const newVals = colorToDisplayValues(colorRef);
      if (Math.abs(currentXValue - newVals.x) > 0.001) setCurrentXValue(newVals.x);
      if (Math.abs(currentYValue - newVals.y) > 0.001) setCurrentYValue(newVals.y);
      if (Math.abs(currentZValue - newVals.z) > 0.001) setCurrentZValue(newVals.z);
    }

    const thumbXElement = useRef<HTMLElement | undefined>(undefined);
    const thumbYElement = useRef<HTMLElement | undefined>(undefined);
    const thumbZElement = useRef<HTMLElement | undefined>(undefined);
    const thumbElement = useRef<HTMLElement | undefined>(undefined);
    const elementRef = useRef<HTMLDivElement>(null);
    const rectRef = useRef<DOMRect | undefined>(undefined);
    const valueBeforeSlide = useRef({ x: currentXValue, y: currentYValue, z: currentZValue });

    function snap(value: number, min: number, max: number, step: number): number {
      const decimals = (String(step).split(".")[1] || "").length;
      const snapped = Math.round((value - min) / step) * step + min;
      const factor = 10 ** decimals;
      return Math.max(min, Math.min(max, Math.round(snapped * factor) / factor));
    }

    function displayValuesToColor(xVal: number, yVal: number, zVal?: number): Color | undefined {
      if (!colorRef || !xConfig || !yConfig) return undefined;
      const culoriX = displayToCulori(xConfig, xVal);
      const culoriY = displayToCulori(yConfig, yVal);
      const updates: Record<string, number> = {};
      if (!xIsAlpha) updates[xChannelKey] = culoriX;
      if (!yIsAlpha) updates[yChannelKey] = culoriY;
      if (zChannelKey && zConfig && zVal != null) {
        const culoriZ = displayToCulori(zConfig, zVal);
        if (!zIsAlpha) updates[zChannelKey] = culoriZ;
      }
      let result = colorRef.set({ mode: colorSpace, ...updates });
      if (xIsAlpha) result = result.set({ alpha: culoriX });
      if (yIsAlpha) result = result.set({ alpha: culoriY });
      if (zChannelKey && zConfig && zVal != null && zIsAlpha) {
        result = result.set({ alpha: displayToCulori(zConfig, zVal) });
      }
      return result;
    }

    function getValuesFromPointer(clientX: number, clientY: number): { x: number; y: number; z?: number } {
      const el = elementRef.current;
      if (!el) return { x: xMin, y: yMin };
      const rect = rectRef.current || el.getBoundingClientRect();
      rectRef.current = rect;

      const nx = (clientX - rect.left) / rect.width;
      const ny = (clientY - rect.top) / rect.height;

      const [v0, v1, v2] = vertices;
      const clamped = clampToTriangle(nx, ny, v0, v1, v2);
      const { u, v, w } = barycentricCoords(clamped.x, clamped.y, v0, v1, v2);
      const cu = Math.max(0, u), cv = Math.max(0, v), cw = Math.max(0, w);
      const sum = cu + cv + cw;
      const nu = cu / sum, nv = cv / sum, nw = cw / sum;

      if (isThreeChannel) {
        return {
          x: nu * xMax + (1 - nu) * xMin,
          y: nv * yMax + (1 - nv) * yMin,
          z: nw * zMax + (1 - nw) * zMin,
        };
      }
      return {
        x: nu * xMax + nv * xMin + nw * xMin,
        y: nu * yMax + nv * yMax + nw * yMin,
      };
    }

    function updateValues(xVal: number, yVal: number, commit = false, zVal?: number) {
      const snappedX = snap(xVal, xMin, xMax, xStep);
      const snappedY = snap(yVal, yMin, yMax, yStep);
      const snappedZ = zVal != null ? snap(zVal, zMin, zMax, zStep) : undefined;

      setCurrentXValue(snappedX);
      setCurrentYValue(snappedY);
      if (snappedZ != null) setCurrentZValue(snappedZ);

      const newColor = displayValuesToColor(snappedX, snappedY, snappedZ);
      if (newColor) {
        if (!isControlled) setInternalColor(newColor);
        onValueChange?.(newColor);
        if (commit) onValueCommit?.(newColor);
      }
    }

    function channelsToBary(): { u: number; v: number; w: number } {
      const xRange = xMax - xMin;
      const yRange = yMax - yMin;

      if (isThreeChannel) {
        const u = xRange > 0 ? (currentXValue - xMin) / xRange : 0;
        const v = yRange > 0 ? (currentYValue - yMin) / yRange : 0;
        const w = Math.max(0, 1 - u - v);
        const sum = u + v + w;
        return sum > 0 ? { u: u / sum, v: v / sum, w: w / sum } : { u: 1 / 3, v: 1 / 3, w: 1 / 3 };
      }
      const u = xRange > 0 ? (currentXValue - xMin) / xRange : 0;
      const w = yRange > 0 ? (yMax - currentYValue) / yRange : 0;
      const v = Math.max(0, 1 - u - w);
      const sum = u + v + w;
      return sum > 0 ? { u: u / sum, v: v / sum, w: w / sum } : { u: 1 / 3, v: 1 / 3, w: 1 / 3 };
    }

    function baryToChannels(u: number, v: number, w: number): { x: number; y: number; z?: number } {
      if (isThreeChannel) {
        return {
          x: u * xMax + (1 - u) * xMin,
          y: v * yMax + (1 - v) * yMin,
          z: w * zMax + (1 - w) * zMin,
        };
      }
      return {
        x: u * xMax + (1 - u) * xMin,
        y: (1 - w) * yMax + w * yMin,
      };
    }

    function handleKeyDown3Channel(event: React.KeyboardEvent) {
      const step = 0.05;
      const multiplier = event.shiftKey ? 4 : 1;
      let channelDelta = 0;

      switch (event.key) {
        case "ArrowUp": case "ArrowRight": channelDelta = step * multiplier; break;
        case "ArrowDown": case "ArrowLeft": channelDelta = -step * multiplier; break;
        case "PageUp": channelDelta = step * 4; break;
        case "PageDown": channelDelta = -step * 4; break;
        case "Home": {
          const u = activeDirection === "x" ? 1 : 0;
          const v = activeDirection === "y" ? 1 : 0;
          const w = activeDirection === "z" ? 1 : 0;
          const vals = baryToChannels(u, v, w);
          updateValues(vals.x, vals.y, true, vals.z);
          event.preventDefault();
          return;
        }
        case "End": {
          const vals = baryToChannels(1 / 3, 1 / 3, 1 / 3);
          updateValues(vals.x, vals.y, true, vals.z);
          event.preventDefault();
          return;
        }
        default: return;
      }

      event.preventDefault();
      const bary = channelsToBary();
      let newU = bary.u, newV = bary.v, newW = bary.w;
      const ad = activeDirection;
      const focused = ad === "x" ? newU : ad === "y" ? newV : newW;
      const newFocused = Math.max(0, Math.min(1, focused + channelDelta));
      const actualDelta = newFocused - focused;
      const origU = newU, origV = newV, origW = newW;

      if (ad === "x") newU = newFocused;
      else if (ad === "y") newV = newFocused;
      else newW = newFocused;

      function redistribute(a: number, b: number, delta: number): [number, number] {
        const sum = a + b;
        if (sum > 0) return [a - delta * (a / sum), b - delta * (b / sum)];
        return [-delta / 2, -delta / 2];
      }

      if (ad === "x") [newV, newW] = redistribute(origV, origW, actualDelta);
      else if (ad === "y") [newU, newW] = redistribute(origU, origW, actualDelta);
      else [newU, newV] = redistribute(origU, origV, actualDelta);

      newU = Math.max(0, newU);
      newV = Math.max(0, newV);
      newW = Math.max(0, newW);
      const sum = newU + newV + newW;
      if (sum > 0) { newU /= sum; newV /= sum; newW /= sum; }

      const vals = baryToChannels(newU, newV, newW);
      updateValues(vals.x, vals.y, true, vals.z);
    }

    function handleKeyDown2Channel(event: React.KeyboardEvent) {
      const multiplier = event.shiftKey ? 4 : 1;
      let newX = currentXValue;
      let newY = currentYValue;
      let targetedY = false;

      switch (event.key) {
        case "ArrowRight": newY = Math.min(yMax, newY + yStep * multiplier); targetedY = true; break;
        case "ArrowLeft": newY = Math.max(yMin, newY - yStep * multiplier); targetedY = true; break;
        case "ArrowUp": newX = Math.min(xMax, newX + xStep * multiplier); break;
        case "ArrowDown": newX = Math.max(xMin, newX - xStep * multiplier); break;
        case "PageUp": case "Home": newX = xMax; newY = yMax; break;
        case "PageDown": case "End": newX = xMin; newY = yMin; break;
        default: return;
      }

      const xRange = xMax - xMin;
      const yRange = yMax - yMin;
      if (xRange > 0 && yRange > 0) {
        const u = (newX - xMin) / xRange;
        const w = (yMax - newY) / yRange;
        if (u + w > 1) {
          if (targetedY) newX = xMin + (1 - w) * xRange;
          else newY = yMax - (1 - u) * yRange;
        }
      }

      event.preventDefault();
      updateValues(newX, newY, true);
    }

    const handlePointerDown = useCallback((event: React.PointerEvent) => {
      if (disabled) return;
      const target = event.target as HTMLElement;
      const el = elementRef.current;
      if (!el) return;

      const rect = el.getBoundingClientRect();
      const nx = (event.clientX - rect.left) / rect.width;
      const ny = (event.clientY - rect.top) / rect.height;
      const [hv0, hv1, hv2] = vertices;
      if (!pointInTriangle(nx, ny, hv0, hv1, hv2)) return;

      target.setPointerCapture(event.pointerId);
      event.preventDefault();

      if (thumbXElement.current && (target === thumbXElement.current || thumbXElement.current.contains(target))) {
        setActiveDirection("x");
        thumbXElement.current.focus();
      } else if (thumbYElement.current && (target === thumbYElement.current || thumbYElement.current.contains(target))) {
        setActiveDirection("y");
        thumbYElement.current.focus();
      } else if (thumbZElement.current && (target === thumbZElement.current || thumbZElement.current.contains(target))) {
        setActiveDirection("z");
        thumbZElement.current.focus();
      } else {
        setActiveDirection("x");
        thumbXElement.current?.focus();
      }

      setIsDragging(true);
      valueBeforeSlide.current = { x: currentXValue, y: currentYValue, z: currentZValue };
      rectRef.current = rect;
      const vals = getValuesFromPointer(event.clientX, event.clientY);
      updateValues(vals.x, vals.y, false, vals.z);
    }, [disabled, vertices, currentXValue, currentYValue, currentZValue, xMin, xMax, yMin, yMax, zMin, zMax, colorRef, xConfig, yConfig, zConfig, isThreeChannel, isControlled, onValueChange]);

    const rafPending = useRef(false);
    const handlePointerMove = useCallback((event: React.PointerEvent) => {
      const target = event.target as HTMLElement;
      if (!target.hasPointerCapture(event.pointerId)) return;
      if (rafPending.current) return;
      rafPending.current = true;
      const { clientX, clientY } = event;
      requestAnimationFrame(() => {
        rafPending.current = false;
        const vals = getValuesFromPointer(clientX, clientY);
        updateValues(vals.x, vals.y, false, vals.z);
      });
    }, [vertices, xMin, xMax, yMin, yMax, zMin, zMax, colorRef, xConfig, yConfig, zConfig, isThreeChannel, isControlled, onValueChange]);

    const handlePointerUp = useCallback((event: React.PointerEvent) => {
      const target = event.target as HTMLElement;
      if (!target.hasPointerCapture(event.pointerId)) return;
      target.releasePointerCapture(event.pointerId);
      setIsDragging(false);
      rectRef.current = undefined;
      const prev = valueBeforeSlide.current;
      if (prev.x !== currentXValue || prev.y !== currentYValue || prev.z !== currentZValue) {
        if (colorRef) onValueCommit?.(colorRef);
      }
    }, [currentXValue, currentYValue, currentZValue, colorRef, onValueCommit]);

    const handleKeyDown = useCallback((event: React.KeyboardEvent) => {
      if (disabled) return;
      if (isThreeChannel) handleKeyDown3Channel(event);
      else handleKeyDown2Channel(event);
    }, [disabled, isThreeChannel, activeDirection, currentXValue, currentYValue, currentZValue, xMin, xMax, yMin, yMax, zMin, zMax, xStep, yStep, zStep, colorRef, xConfig, yConfig, zConfig, isControlled, onValueChange, onValueCommit]);

    const ctxValue = useMemo<ColorTriangleContextValue>(() => ({
      disabled, colorSpace, xChannelKey, yChannelKey, zChannelKey,
      colorRef, currentXValue, currentYValue, currentZValue,
      xMin, xMax, yMin, yMax, zMin, zMax,
      isThreeChannel, rotation, vertices,
      activeDirection, setActiveDirection,
      thumbXElement, thumbYElement, thumbZElement,
      isDragging, thumbAlignment, thumbElement,
    }), [disabled, colorSpace, xChannelKey, yChannelKey, zChannelKey, colorRef, currentXValue, currentYValue, currentZValue, xMin, xMax, yMin, yMax, zMin, zMax, isThreeChannel, rotation, vertices, activeDirection, isDragging, thumbAlignment]);

    return (
      <ColorTriangleContext.Provider value={ctxValue}>
        <div
          ref={(el) => {
            (elementRef as React.MutableRefObject<HTMLDivElement | null>).current = el;
            if (typeof ref === "function") ref(el);
            else if (ref) ref.current = el;
          }}
          aria-disabled={disabled}
          data-disabled={disabled ? "" : undefined}
          data-color-triangle-root=""
          className={className}
          style={clipPathStyle}
          onPointerDown={handlePointerDown}
          onPointerMove={handlePointerMove}
          onPointerUp={handlePointerUp}
          onKeyDown={handleKeyDown}
        >
          {children}
        </div>
      </ColorTriangleContext.Provider>
    );
  },
);

// packages/vue/src/components/ColorTriangle/ColorTriangleRoot.vue
<script lang="ts">
import type { Ref } from "vue";
import type { PrimitiveProps } from "reka-ui";
import { createContext, useDirection, useForwardExpose, VisuallyHidden } from "reka-ui";
import { computed, ref, shallowRef, toRefs, watch } from "vue";
import { Color } from "internationalized-color";
import { colorSpaces, getChannelConfig, displayToCulori, culoriToDisplay, type ChannelConfig } from "@urcolor/core";
import { triangleVertices, clampToTriangle, barycentricCoords, barycentricToCartesian, pointInTriangle, type Point } from "@urcolor/core";

type Direction = "ltr" | "rtl";

export interface ColorTriangleRootProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
  name?: string | undefined;
  required?: boolean;
  modelValue?: Color | string | null;
  defaultValue?: Color | string;
  disabled?: boolean;
  dir?: Direction;
  colorSpace?: string;
  channelX?: string;
  channelY?: string;
  channelZ?: string;
  rotation?: number;
  orientation?: "vertical" | "horizontal";
}

export type ColorTriangleRootEmits = {
  "update:modelValue": [payload: Color | undefined];
  "valueCommit": [payload: Color];
};

export type ActiveDirection = "x" | "y" | "z";

export interface ColorTriangleRootContext {
  disabled: Ref<boolean>;
  colorSpace: Ref<string>;
  xChannelKey: Ref<string>;
  yChannelKey: Ref<string>;
  zChannelKey: Ref<string | undefined>;
  colorRef: Readonly<Ref<Color | undefined>>;
  currentXValue: Ref<number>;
  currentYValue: Ref<number>;
  currentZValue: Ref<number>;
  xMin: Ref<number>;
  xMax: Ref<number>;
  yMin: Ref<number>;
  yMax: Ref<number>;
  zMin: Ref<number>;
  zMax: Ref<number>;
  isThreeChannel: Ref<boolean>;
  rotation: Ref<number>;
  vertices: Ref<[Point, Point, Point]>;
  orientation: Ref<"vertical" | "horizontal">;
  dir: Ref<Direction>;
  activeDirection: Ref<ActiveDirection>;
  thumbXElement: Ref<HTMLElement | undefined>;
  thumbYElement: Ref<HTMLElement | undefined>;
  thumbZElement: Ref<HTMLElement | undefined>;
  isDragging: Ref<boolean>;
}

export const [injectColorTriangleRootContext, provideColorTriangleRootContext]
  = createContext<ColorTriangleRootContext>("ColorTriangleRoot");
</script>

<script setup lang="ts">
import { Primitive } from "reka-ui";
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<ColorTriangleRootProps>(), {
  disabled: false,
  defaultValue: "hsl(0, 100%, 50%)",
  colorSpace: "hsv",
  rotation: 0,
  orientation: "vertical",
  as: "span",
});
const emits = defineEmits<ColorTriangleRootEmits>();

defineSlots<{
  default?: (props: { modelValue: Color | undefined }) => any;
}>();

const { disabled, dir: propDir } = toRefs(props);
const dir = useDirection(propDir);
const { forwardRef, currentElement } = useForwardExpose();

const ALPHA_CONFIG: ChannelConfig = {
  key: "alpha", label: "Alpha", min: 0, max: 100, step: 1, format: "percentage", culoriMin: 0, culoriMax: 1,
};

const spaceConfig = computed(() => colorSpaces[props.colorSpace]);
const xChannelKey = computed(() => props.channelX ?? spaceConfig.value?.channels[1]?.key ?? "s");
const yChannelKey = computed(() => props.channelY ?? spaceConfig.value?.channels[2]?.key ?? "v");
const xIsAlpha = computed(() => xChannelKey.value === "alpha");
const yIsAlpha = computed(() => yChannelKey.value === "alpha");
const xConfig = computed(() => xIsAlpha.value ? ALPHA_CONFIG : getChannelConfig(props.colorSpace, xChannelKey.value));
const yConfig = computed(() => yIsAlpha.value ? ALPHA_CONFIG : getChannelConfig(props.colorSpace, yChannelKey.value));

const zChannelKey = computed(() => props.channelZ);
const zIsAlpha = computed(() => zChannelKey.value === "alpha");
const zConfig = computed(() => zChannelKey.value ? (zIsAlpha.value ? ALPHA_CONFIG : getChannelConfig(props.colorSpace, zChannelKey.value)) : undefined);
const isThreeChannel = computed(() => zChannelKey.value != null);

const xMin = computed(() => xConfig.value?.min ?? 0);
const xMax = computed(() => xConfig.value?.max ?? 100);
const xStep = computed(() => xConfig.value?.step ?? 1);
const yMin = computed(() => yConfig.value?.min ?? 0);
const yMax = computed(() => yConfig.value?.max ?? 100);
const yStep = computed(() => yConfig.value?.step ?? 1);
const zMin = computed(() => zConfig.value?.min ?? 0);
const zMax = computed(() => zConfig.value?.max ?? 100);
const zStep = computed(() => zConfig.value?.step ?? 1);

// Triangle vertices in normalized 0-1 space
const vertices = computed(() => triangleVertices(1, 1, props.rotation));

function parseColor(v: Color | string | null | undefined): Color | undefined {
  if (!v) return undefined;
  if (v instanceof Color) return v;
  return Color.parse(v) ?? undefined;
}

const colorRef = shallowRef<Color | undefined>(parseColor(props.modelValue ?? props.defaultValue));

watch(() => props.modelValue, (val) => {
  const parsed = parseColor(val);
  if (parsed) colorRef.value = parsed;
});

function colorToDisplayValues(color: Color | undefined): { x: number; y: number; z: number } {
  if (!color || !xConfig.value || !yConfig.value) return { x: xMin.value, y: yMin.value, z: zMin.value };
  const converted = color.to(props.colorSpace);
  if (!converted) return { x: xMin.value, y: yMin.value, z: zMin.value };
  const rawX = xIsAlpha.value ? (color.alpha ?? 1) : converted.get(xChannelKey.value, 0);
  const rawY = yIsAlpha.value ? (color.alpha ?? 1) : converted.get(yChannelKey.value, 0);
  const rawZ = zChannelKey.value ? (zIsAlpha.value ? (color.alpha ?? 1) : converted.get(zChannelKey.value, 0)) : 0;
  return {
    x: culoriToDisplay(xConfig.value, rawX),
    y: culoriToDisplay(yConfig.value, rawY),
    z: zConfig.value ? culoriToDisplay(zConfig.value, rawZ) : zMin.value,
  };
}

const initValues = colorToDisplayValues(colorRef.value);
const currentXValue = ref(initValues.x);
const currentYValue = ref(initValues.y);
const currentZValue = ref(initValues.z);

watch([colorRef, xChannelKey, yChannelKey, zChannelKey], ([color]) => {
  const newVals = colorToDisplayValues(color);
  if (Math.abs(currentXValue.value - newVals.x) > 0.001) currentXValue.value = newVals.x;
  if (Math.abs(currentYValue.value - newVals.y) > 0.001) currentYValue.value = newVals.y;
  if (Math.abs(currentZValue.value - newVals.z) > 0.001) currentZValue.value = newVals.z;
});

function displayValuesToColor(xVal: number, yVal: number, zVal?: number): Color | undefined {
  if (!colorRef.value || !xConfig.value || !yConfig.value) return undefined;
  const culoriX = displayToCulori(xConfig.value, xVal);
  const culoriY = displayToCulori(yConfig.value, yVal);
  const updates: Record<string, number> = {};
  if (!xIsAlpha.value) updates[xChannelKey.value] = culoriX;
  if (!yIsAlpha.value) updates[yChannelKey.value] = culoriY;
  if (zChannelKey.value && zConfig.value && zVal != null) {
    const culoriZ = displayToCulori(zConfig.value, zVal);
    if (!zIsAlpha.value) updates[zChannelKey.value] = culoriZ;
  }
  let result = colorRef.value.set({ mode: props.colorSpace, ...updates });
  if (xIsAlpha.value) result = result.set({ alpha: culoriX });
  if (yIsAlpha.value) result = result.set({ alpha: culoriY });
  if (zChannelKey.value && zConfig.value && zVal != null && zIsAlpha.value) {
    result = result.set({ alpha: displayToCulori(zConfig.value, zVal) });
  }
  return result;
}

function snap(value: number, min: number, max: number, step: number): number {
  const decimals = (String(step).split(".")[1] || "").length;
  const snapped = Math.round((value - min) / step) * step + min;
  const factor = 10 ** decimals;
  return Math.max(min, Math.min(max, Math.round(snapped * factor) / factor));
}

const activeDirection = ref<ActiveDirection>("x");
const thumbXElement = ref<HTMLElement>();
const thumbYElement = ref<HTMLElement>();
const thumbZElement = ref<HTMLElement>();
const isDragging = ref(false);

const valueBeforeSlide = ref({ x: currentXValue.value, y: currentYValue.value, z: currentZValue.value });
const rectRef = ref<DOMRect>();

function getValuesFromPointer(event: PointerEvent): { x: number; y: number; z?: number } {
  const rect = rectRef.value || currentElement.value.getBoundingClientRect();
  rectRef.value = rect;

  const nx = (event.clientX - rect.left) / rect.width;
  const ny = (event.clientY - rect.top) / rect.height;

  const [v0, v1, v2] = vertices.value;
  const clamped = clampToTriangle(nx, ny, v0, v1, v2);

  const { u, v, w } = barycentricCoords(clamped.x, clamped.y, v0, v1, v2);
  const cu = Math.max(0, u), cv = Math.max(0, v), cw = Math.max(0, w);
  const sum = cu + cv + cw;
  const nu = cu / sum, nv = cv / sum, nw = cw / sum;

  if (isThreeChannel.value) {
    // 3-channel: v0→(xMax,yMin,zMin), v1→(xMin,yMax,zMin), v2→(xMin,yMin,zMax)
    const xVal = nu * xMax.value + (1 - nu) * xMin.value;
    const yVal = nv * yMax.value + (1 - nv) * yMin.value;
    const zVal = nw * zMax.value + (1 - nw) * zMin.value;
    return { x: xVal, y: yVal, z: zVal };
  }

  // 2-channel: v0→(xMax,yMax), v1→(xMin,yMax), v2→(xMin,yMin)
  const xVal = nu * xMax.value + nv * xMin.value + nw * xMin.value;
  const yVal = nu * yMax.value + nv * yMax.value + nw * yMin.value;
  return { x: xVal, y: yVal };
}

function updateValues(xVal: number, yVal: number, commit = false, zVal?: number) {
  const snappedX = snap(xVal, xMin.value, xMax.value, xStep.value);
  const snappedY = snap(yVal, yMin.value, yMax.value, yStep.value);
  const snappedZ = zVal != null ? snap(zVal, zMin.value, zMax.value, zStep.value) : undefined;

  currentXValue.value = snappedX;
  currentYValue.value = snappedY;
  if (snappedZ != null) currentZValue.value = snappedZ;

  const newColor = displayValuesToColor(snappedX, snappedY, snappedZ);
  if (newColor) {
    colorRef.value = newColor;
    emits("update:modelValue", newColor);
    if (commit) emits("valueCommit", newColor);
  }
}

function handlePointerDown(event: PointerEvent) {
  if (props.disabled) return;
  const target = event.target as HTMLElement;

  // Ignore clicks outside the triangle
  const rect = currentElement.value.getBoundingClientRect();
  const nx = (event.clientX - rect.left) / rect.width;
  const ny = (event.clientY - rect.top) / rect.height;
  const [v0, v1, v2] = vertices.value;
  if (!pointInTriangle(nx, ny, v0, v1, v2)) return;

  target.setPointerCapture(event.pointerId);
  event.preventDefault();

  if (thumbXElement.value && (target === thumbXElement.value || thumbXElement.value.contains(target))) {
    activeDirection.value = "x";
    thumbXElement.value.focus();
  } else if (thumbYElement.value && (target === thumbYElement.value || thumbYElement.value.contains(target))) {
    activeDirection.value = "y";
    thumbYElement.value.focus();
  } else if (thumbZElement.value && (target === thumbZElement.value || thumbZElement.value.contains(target))) {
    activeDirection.value = "z";
    thumbZElement.value.focus();
  } else {
    // Clicked on triangle surface — focus the X thumb by default
    activeDirection.value = "x";
    thumbXElement.value?.focus();
  }

  isDragging.value = true;
  valueBeforeSlide.value = { x: currentXValue.value, y: currentYValue.value, z: currentZValue.value };
  const vals = getValuesFromPointer(event);
  updateValues(vals.x, vals.y, false, vals.z);
}

const lastPointerPosition = ref<{ x: number; y: number }>();
let rafPending = false;

function handlePointerMove(event: PointerEvent) {
  const target = event.target as HTMLElement;
  if (!target.hasPointerCapture(event.pointerId)) return;
  if (rafPending) return;
  rafPending = true;
  const clientX = event.clientX;
  const clientY = event.clientY;
  const pointerId = event.pointerId;
  requestAnimationFrame(() => {
    rafPending = false;
    if (lastPointerPosition.value) {
      const dx = Math.abs(clientX - lastPointerPosition.value.x);
      const dy = Math.abs(clientY - lastPointerPosition.value.y);
      const newDirection = dx >= dy ? "x" : "y";
      activeDirection.value = newDirection;
    }
    lastPointerPosition.value = { x: clientX, y: clientY };
    const vals = getValuesFromPointer({ clientX, clientY, pointerId } as PointerEvent);
    updateValues(vals.x, vals.y, false, vals.z);
  });
}

function handlePointerUp(event: PointerEvent) {
  const target = event.target as HTMLElement;
  if (!target.hasPointerCapture(event.pointerId)) return;
  target.releasePointerCapture(event.pointerId);
  isDragging.value = false;
  rectRef.value = undefined;
  lastPointerPosition.value = undefined;
  const prev = valueBeforeSlide.value;
  if (prev.x !== currentXValue.value || prev.y !== currentYValue.value || prev.z !== currentZValue.value) {
    if (colorRef.value) emits("valueCommit", colorRef.value);
  }
}

function channelsToBary(): { u: number; v: number; w: number } {
  const xRange = xMax.value - xMin.value;
  const yRange = yMax.value - yMin.value;

  if (isThreeChannel.value) {
    // 3-channel: v0→(xMax,yMin,zMin), v1→(xMin,yMax,zMin), v2→(xMin,yMin,zMax)
    const u = xRange > 0 ? (currentXValue.value - xMin.value) / xRange : 0;
    const v = yRange > 0 ? (currentYValue.value - yMin.value) / yRange : 0;
    const w = Math.max(0, 1 - u - v);
    const sum = u + v + w;
    return sum > 0 ? { u: u / sum, v: v / sum, w: w / sum } : { u: 1 / 3, v: 1 / 3, w: 1 / 3 };
  }

  // 2-channel: v0→(xMax,yMax), v1→(xMin,yMax), v2→(xMin,yMin)
  // x = u*xMax + (1-u)*xMin → u = (x - xMin) / xRange
  // y = (1-w)*yMax + w*yMin → w = (yMax - y) / yRange
  const u = xRange > 0 ? (currentXValue.value - xMin.value) / xRange : 0;
  const w = yRange > 0 ? (yMax.value - currentYValue.value) / yRange : 0;
  const v = Math.max(0, 1 - u - w);
  const sum = u + v + w;
  return sum > 0 ? { u: u / sum, v: v / sum, w: w / sum } : { u: 1 / 3, v: 1 / 3, w: 1 / 3 };
}

function baryToChannels(u: number, v: number, w: number): { x: number; y: number; z?: number } {
  if (isThreeChannel.value) {
    return {
      x: u * xMax.value + (1 - u) * xMin.value,
      y: v * yMax.value + (1 - v) * yMin.value,
      z: w * zMax.value + (1 - w) * zMin.value,
    };
  }
  return {
    x: u * xMax.value + (1 - u) * xMin.value,
    y: (1 - w) * yMax.value + w * yMin.value,
  };
}

function handleKeyDown3Channel(event: KeyboardEvent) {
  const step = 0.05;
  const multiplier = event.shiftKey ? 4 : 1;

  // Determine delta for the focused channel
  let channelDelta = 0;
  switch (event.key) {
    case "ArrowUp":
    case "ArrowRight":
      channelDelta = step * multiplier;
      break;
    case "ArrowDown":
    case "ArrowLeft":
      channelDelta = -step * multiplier;
      break;
    case "PageUp":
      channelDelta = step * 4;
      break;
    case "PageDown":
      channelDelta = -step * 4;
      break;
    case "Home": {
      // Jump to this channel's vertex (max this, min others)
      const dir = activeDirection.value;
      const u = dir === "x" ? 1 : 0;
      const v = dir === "y" ? 1 : 0;
      const w = dir === "z" ? 1 : 0;
      const vals = baryToChannels(u, v, w);
      updateValues(vals.x, vals.y, true, vals.z);
      event.preventDefault();
      return;
    }
    case "End": {
      // Jump to center (equal distribution)
      const vals = baryToChannels(1 / 3, 1 / 3, 1 / 3);
      updateValues(vals.x, vals.y, true, vals.z);
      event.preventDefault();
      return;
    }
    default:
      return;
  }

  event.preventDefault();

  const bary = channelsToBary();
  let newU = bary.u, newV = bary.v, newW = bary.w;
  const ad = activeDirection.value;

  // Get current value of focused component and apply delta
  const focused = ad === "x" ? newU : ad === "y" ? newV : newW;
  const newFocused = Math.max(0, Math.min(1, focused + channelDelta));
  const actualDelta = newFocused - focused;

  // Save originals before mutation
  const origU = newU, origV = newV, origW = newW;

  if (ad === "x") newU = newFocused;
  else if (ad === "y") newV = newFocused;
  else newW = newFocused;

  // Distribute the opposite delta proportionally to the other two
  function redistribute(a: number, b: number, delta: number): [number, number] {
    const sum = a + b;
    if (sum > 0) {
      return [a - delta * (a / sum), b - delta * (b / sum)];
    }
    const half = -delta / 2;
    return [half, half];
  }

  if (ad === "x") {
    [newV, newW] = redistribute(origV, origW, actualDelta);
  } else if (ad === "y") {
    [newU, newW] = redistribute(origU, origW, actualDelta);
  } else {
    [newU, newV] = redistribute(origU, origV, actualDelta);
  }

  // Clamp and normalize
  newU = Math.max(0, newU);
  newV = Math.max(0, newV);
  newW = Math.max(0, newW);
  const sum = newU + newV + newW;
  if (sum > 0) { newU /= sum; newV /= sum; newW /= sum; }

  const vals = baryToChannels(newU, newV, newW);
  updateValues(vals.x, vals.y, true, vals.z);
}

function handleKeyDown2Channel(event: KeyboardEvent) {
  const multiplier = event.shiftKey ? 4 : 1;
  let newX = currentXValue.value;
  let newY = currentYValue.value;

  let targetedY = false;

  switch (event.key) {
    case "ArrowRight":
      newY = Math.min(yMax.value, newY + yStep.value * multiplier);
      targetedY = true;
      break;
    case "ArrowLeft":
      newY = Math.max(yMin.value, newY - yStep.value * multiplier);
      targetedY = true;
      break;
    case "ArrowUp":
      newX = Math.min(xMax.value, newX + xStep.value * multiplier);
      break;
    case "ArrowDown":
      newX = Math.max(xMin.value, newX - xStep.value * multiplier);
      break;
    case "PageUp":
      newX = xMax.value;
      newY = yMax.value;
      break;
    case "PageDown":
      newX = xMin.value;
      newY = yMin.value;
      break;
    case "Home":
      newX = xMax.value;
      newY = yMax.value;
      break;
    case "End":
      newX = xMin.value;
      newY = yMin.value;
      break;
    default:
      return;
  }

  // Clamp to triangle bounds: u + w <= 1 (v >= 0)
  const xRange = xMax.value - xMin.value;
  const yRange = yMax.value - yMin.value;
  if (xRange > 0 && yRange > 0) {
    const u = (newX - xMin.value) / xRange;
    const w = (yMax.value - newY) / yRange;
    if (u + w > 1) {
      if (targetedY) {
        newX = xMin.value + (1 - w) * xRange;
      } else {
        newY = yMax.value - (1 - u) * yRange;
      }
    }
  }

  event.preventDefault();
  updateValues(newX, newY, true);
}

function handleKeyDown(event: KeyboardEvent) {
  if (props.disabled) return;
  if (isThreeChannel.value) {
    handleKeyDown3Channel(event);
  } else {
    handleKeyDown2Channel(event);
  }
}

const isFormControl = computed(() => currentElement.value ? Boolean(currentElement.value.closest("form")) : false);

provideColorTriangleRootContext({
  disabled,
  colorSpace: computed(() => props.colorSpace),
  xChannelKey,
  yChannelKey,
  zChannelKey,
  colorRef,
  currentXValue,
  currentYValue,
  currentZValue,
  xMin,
  xMax,
  yMin,
  yMax,
  zMin,
  zMax,
  isThreeChannel,
  rotation: computed(() => props.rotation),
  orientation: computed(() => props.orientation!),
  vertices,
  dir,
  activeDirection,
  thumbXElement,
  thumbYElement,
  thumbZElement,
  isDragging,
});
</script>

<template>
  <Primitive
    v-bind="$attrs"
    :ref="forwardRef"
    :as-child="asChild"
    :as="as"
    :dir="dir"
    :aria-disabled="disabled"
    :data-disabled="disabled ? '' : undefined"
    @pointerdown="handlePointerDown"
    @pointermove="handlePointerMove"
    @pointerup="handlePointerUp"
    @keydown="handleKeyDown"
  >
    <slot :model-value="colorRef" />

    <VisuallyHidden
      v-if="isFormControl && name"
      as="input"
      type="hidden"
      :value="colorRef?.toString() ?? ''"
      :name="name"
      :required="required"
      :disabled="disabled"
    />
  </Primitive>
</template>
