// packages/angular/src/components/color-swatch-group/root/color-swatch-group-root.ts
import {
  afterNextRender,
  booleanAttribute,
  computed,
  DestroyRef,
  Directive,
  ElementRef,
  HostAttributeToken,
  inject,
  input,
  model,
  signal,
} from "@angular/core";
import type { FormValueControl } from "@angular/forms/signals";
import {
  DATA_DISABLED,
  DATA_ORIENTATION,
  rovingIndexFromKey,
  rovingTabIndex,
  type ToggleGroupState,
} from "@urcolor/primitives";

/** Whether the group holds at most one selection or any number of them. */
export type ColorSwatchGroupSelectionType = "single" | "multiple";

/** The axis arrow-key navigation runs along. */
export type ColorSwatchGroupOrientation = "horizontal" | "vertical";

/**
 * An item's live seat in the group, handed back by {@link ColorSwatchGroupRoot.register}.
 *
 * `index` is recomputed from the registration order on every read, so items
 * added or removed after mount stay correctly numbered. Items must call
 * `dispose()` when they are destroyed, e.g. from `DestroyRef.onDestroy`.
 */
export interface ColorSwatchGroupItemHandle {
  /** Position in registration (and therefore DOM) order, or -1 once disposed. */
  readonly index: number;
  /** The single tab stop is 0; every other item is -1. */
  readonly tabIndex: 0 | -1;
  /** True when this item owns the group's tab stop. */
  readonly active: boolean;
  /** Moves the group's tab stop to this item. */
  activate(): void;
  /** Removes the item from the group. */
  dispose(): void;
}

/**
 * Roving focus needs the items as DOM nodes, and items are supplied by the
 * caller rather than rendered here, so they are found by shape: a native
 * button, an explicit button role, or anything carrying a tab stop.
 */
const ITEM_SELECTOR = "button, [role='button'], [tabindex]";

/**
 * A group of colour swatches sharing one selection and one tab stop.
 *
 * ```html
 * <div urcColorSwatchGroupRoot [(value)]="selected" type="multiple">
 *   @for (color of palette(); track color) {
 *     <button urcColorSwatch [value]="color"></button>
 *   }
 * </div>
 * ```
 *
 * Selection is tracked by **value string** and focus by **index** — never by
 * `Color` identity, which is immutable and so never compares equal.
 *
 * The group owns roving focus alone: `keydown` and `focusin` bubble here from
 * the focused item, so a `ColorSwatch` needs no coupling to it and stays usable
 * standalone. Activation (Enter/Space) belongs to the item, which owns its own
 * pressed state.
 *
 * `implements FormValueControl<string[]>` is satisfied by the `value` model
 * alone, which is what makes `<div urcColorSwatchGroupRoot [field]="form.tags">`
 * work.
 */
@Directive({
  selector: "[urcColorSwatchGroupRoot]",
  exportAs: "urcColorSwatchGroupRoot",
  host: {
    "[attr.role]": "role()",
    [`[attr.${DATA_ORIENTATION}]`]: "orientation()",
    [`[attr.${DATA_DISABLED}]`]: "isDisabled() ? '' : null",
    "(keydown)": "onKeyDown($event)",
    "(focusin)": "onFocusIn($event)",
  },
})
export class ColorSwatchGroupRoot implements FormValueControl<string[]> {
  /** The selected item values, two-way bindable as `[(value)]`. Also the Signal Forms contract. */
  readonly value = model<string[]>([]);

  /** Whether to allow a single selection or any number of them. */
  readonly type = input<ColorSwatchGroupSelectionType>("single");
  /** The axis arrow-key navigation runs along. */
  readonly orientation = input<ColorSwatchGroupOrientation>("horizontal");
  /** Whether keyboard focus wraps back to the first item past the last one. */
  readonly loopFocus = input(true, { transform: booleanAttribute });

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly destroyRef = inject(DestroyRef);

  /** A static `role` the consumer set themselves always wins over ours. */
  private readonly roleAttr = inject(new HostAttributeToken("role"), { optional: true });

  /**
   * `disabled` and `dir` are DOM state, not inputs. The static host attribute
   * is read at construction — which works under SSR, where there is no DOM —
   * and a `MutationObserver` installed after the first render keeps both live.
   */
  private readonly disabledState = signal(
    inject(new HostAttributeToken("disabled"), { optional: true }) !== null,
  );

  private readonly dirState = signal<"ltr" | "rtl">(
    inject(new HostAttributeToken("dir"), { optional: true }) === "rtl" ? "rtl" : "ltr",
  );

  /** Registration seats, in mount order. An item's index is its position here. */
  private readonly seats = signal<readonly symbol[]>([]);
  /** Which item owns the group's single tab stop. */
  private readonly activeIndexState = signal(0);

  /**
   * Whether interaction is refused. Named `isDisabled` rather than `disabled`
   * because `FormUiControl` reserves `disabled` for an `InputSignal<boolean>`.
   */
  readonly isDisabled = this.disabledState.asReadonly();
  /** The resolved reading direction, which mirrors horizontal arrow navigation. */
  readonly dir = this.dirState.asReadonly();
  /** Index of the item owning the group's single tab stop. */
  readonly activeIndex = this.activeIndexState.asReadonly();
  /** Number of registered items. */
  readonly count = computed(() => this.seats().length);

  /** The roving-focus state, ready for `rovingIndexFromKey`/`rovingTabIndex`. */
  readonly groupState = computed<ToggleGroupState>(() => ({
    activeIndex: this.activeIndex(),
    count: this.count(),
    orientation: this.orientation(),
    dir: this.dir(),
    loop: this.loopFocus(),
  }));

  protected readonly role = computed(() => this.roleAttr ?? "group");

  constructor() {
    // `afterNextRender` never runs on the server, so this is the only place a
    // directive may touch the DOM.
    afterNextRender(() => {
      const element = this.host.nativeElement;
      this.syncDomState(element);
      if (typeof MutationObserver === "undefined") return;
      const observer = new MutationObserver(() => this.syncDomState(element));
      // Deliberately excludes our own data-* bindings, so there is no feedback loop.
      observer.observe(element, { attributes: true, attributeFilter: ["disabled", "dir"] });
      this.destroyRef.onDestroy(() => observer.disconnect());
    });
  }

  /** True when `itemValue` is part of the current selection. */
  isSelected(itemValue: string): boolean {
    return this.value().includes(itemValue);
  }

  /** Flips `itemValue`, honouring single- vs multiple-selection semantics. */
  toggle(itemValue: string): void {
    if (this.isDisabled()) return;
    const selection = this.value();
    if (selection.includes(itemValue)) {
      this.value.set(
        this.type() === "single" ? [] : selection.filter(entry => entry !== itemValue),
      );
      return;
    }
    this.value.set(this.type() === "single" ? [itemValue] : [...selection, itemValue]);
  }

  /** Moves the group's tab stop to `index`. */
  setActiveIndex(index: number): void {
    if (index < 0) return;
    this.activeIndexState.set(index);
  }

  /** tabindex for the item at `index`. */
  tabIndexFor(index: number): 0 | -1 {
    return rovingTabIndex(this.groupState(), index);
  }

  /**
   * Claims a seat in the group; the caller must `dispose()` it on destroy.
   *
   * Nothing in this package registers today — a `ColorSwatch` is driven by the
   * bubbling listeners above — but a consumer's own item directive can inject
   * the root and take a seat to get its index and tab stop.
   */
  register(): ColorSwatchGroupItemHandle {
    const seat = Symbol("ColorSwatchGroupItem");
    this.seats.update(seats => [...seats, seat]);

    // Every member reads through a closure over the directive, so the handle
    // reports live state rather than a snapshot taken at registration.
    const indexOf = (): number => this.seats().indexOf(seat);
    const tabIndexOf = (): 0 | -1 => rovingTabIndex(this.groupState(), indexOf());
    const isActive = (): boolean => indexOf() === this.activeIndex();
    const activate = (): void => this.setActiveIndex(indexOf());
    const dispose = (): void => {
      this.seats.update(seats => seats.filter(entry => entry !== seat));
    };

    return {
      get index() {
        return indexOf();
      },
      get tabIndex() {
        return tabIndexOf();
      },
      get active() {
        return isActive();
      },
      activate,
      dispose,
    };
  }

  /**
   * Keyboard lives on the root rather than the items: `keydown` from the
   * focused item bubbles here, so one listener covers the whole group.
   */
  protected onKeyDown(event: KeyboardEvent): void {
    if (this.isDisabled()) return;
    const nodes = this.itemNodes();
    if (nodes.length === 0) return;
    const next = rovingIndexFromKey(
      {
        activeIndex: Math.min(this.activeIndex(), nodes.length - 1),
        count: nodes.length,
        orientation: this.orientation(),
        dir: this.dir(),
        loop: this.loopFocus(),
      },
      event.key,
    );
    if (next === undefined) return;
    event.preventDefault();
    this.activeIndexState.set(next);
    nodes[next]?.focus();
  }

  /** Clicking or tabbing into an item moves the tab stop to it. */
  protected onFocusIn(event: FocusEvent): void {
    const target = event.target;
    if (!(target instanceof Element)) return;
    const index = this.itemNodes().findIndex(
      item => item === target || item.contains(target),
    );
    if (index >= 0) this.activeIndexState.set(index);
  }

  /** Items in DOM order, excluding anything nested inside another item. */
  private itemNodes(): HTMLElement[] {
    const root = this.host.nativeElement;
    const found = Array.from(root.querySelectorAll<HTMLElement>(ITEM_SELECTOR));
    return found.filter((node) => {
      const enclosing = node.parentElement?.closest<HTMLElement>(ITEM_SELECTOR);
      return !enclosing || enclosing === root || !root.contains(enclosing);
    });
  }

  /**
   * `getComputedStyle` is used for direction because `dir` inherits from any
   * ancestor; reading the host attribute alone would miss `<html dir="rtl">`.
   */
  private syncDomState(element: HTMLElement): void {
    this.disabledState.set(element.hasAttribute("disabled"));
    const direction
      = typeof getComputedStyle === "function"
        ? getComputedStyle(element).direction
        : element.getAttribute("dir");
    this.dirState.set(direction === "rtl" ? "rtl" : "ltr");
  }
}

// packages/svelte/src/lib/components/color-swatch-group/root/ColorSwatchGroupRoot.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { ChildSnippetArgs } from "../../../shared/child.js";
  import type { SelectionType } from "./context.svelte.js";

  export interface ColorSwatchGroupRootProps extends HTMLAttributes<HTMLDivElement> {
    /** Whether to allow single or multiple selection. */
    type?: SelectionType;
    /** The selected item values. Bindable: `bind:value`. */
    value?: string[];
    /** The selection used until the first interaction when `value` is not bound. */
    defaultValue?: string[];
    /** When true, prevents the user from interacting with the group. */
    disabled?: boolean;
    /** The orientation of the group for arrow key navigation. */
    orientation?: "horizontal" | "vertical";
    /** The reading direction, which mirrors horizontal arrow navigation. */
    dir?: "ltr" | "rtl";
    /** Whether keyboard focus wraps back to the first item past the last one. */
    loopFocus?: boolean;
    /** Called whenever the selection changes. */
    onValueChange?: (value: string[]) => void;
    /** Replaces the default element; receives the props it would have received. */
    child?: Snippet<[ChildSnippetArgs]>;
  }
</script>

<script lang="ts">
  import { untrack } from "svelte";
  import { createAttachmentKey } from "svelte/attachments";
  import {
    DATA_DISABLED,
    DATA_ORIENTATION,
    rovingIndexFromKey,
    rovingTabIndex,
    type ToggleGroupState,
  } from "@urcolor/primitives";
  import type { ChildProps } from "../../../shared/child.js";
  import { colorSwatchGroupContext, type ColorSwatchGroupItemHandle } from "./context.svelte.js";

  /**
   * Roving focus needs the items as DOM nodes, and items are supplied by the
   * caller rather than rendered here, so they are found by shape: a native
   * button, an explicit button role, or anything carrying the tab stop this
   * group hands out.
   */
  const ITEM_SELECTOR = "button, [role='button'], [tabindex]";

  let {
    type = "single",
    value = $bindable(),
    defaultValue = [],
    disabled = false,
    orientation = "horizontal",
    dir,
    loopFocus = true,
    onValueChange,
    class: className,
    style,
    children,
    child,
    ...rest
  }: ColorSwatchGroupRootProps = $props();

  /**
   * Uncontrolled fallback, kept in sync so it and `value` never disagree.
   * `untrack` states the intent that only the initial props are read here.
   */
  let internalValue = $state<string[]>(untrack(() => value ?? defaultValue));
  /** Registration seats, in mount order. An item's index is its position here. */
  let seats = $state<symbol[]>([]);
  /** Which item owns the group's single tab stop. */
  let activeIndex = $state(0);

  const selection = $derived<readonly string[]>(value ?? internalValue);
  const groupState = $derived<ToggleGroupState>({
    activeIndex,
    count: seats.length,
    orientation,
    dir: dir ?? "ltr",
    loop: loopFocus,
  });

  function isSelected(itemValue: string): boolean {
    return selection.includes(itemValue);
  }

  /** Writes the next selection back through both the bound and callback paths. */
  function commit(next: string[]): void {
    internalValue = next;
    value = next;
    onValueChange?.(next);
  }

  function toggle(itemValue: string): void {
    if (disabled) return;
    if (isSelected(itemValue)) {
      commit(type === "single" ? [] : selection.filter((entry) => entry !== itemValue));
      return;
    }
    commit(type === "single" ? [itemValue] : [...selection, itemValue]);
  }

  function setActiveIndex(index: number): void {
    if (index < 0) return;
    activeIndex = index;
  }

  function tabIndexFor(index: number): 0 | -1 {
    return rovingTabIndex(groupState, index);
  }

  function register(): ColorSwatchGroupItemHandle {
    const seat = Symbol("ColorSwatchGroupItem");
    seats.push(seat);
    return {
      get index() {
        return seats.indexOf(seat);
      },
      get tabIndex() {
        return rovingTabIndex(groupState, seats.indexOf(seat));
      },
      get active() {
        return seats.indexOf(seat) === activeIndex;
      },
      activate() {
        setActiveIndex(seats.indexOf(seat));
      },
      dispose() {
        const index = seats.indexOf(seat);
        if (index >= 0) seats.splice(index, 1);
      },
    };
  }

  /** Items in DOM order, excluding anything nested inside another item. */
  function itemNodes(root: HTMLElement): HTMLElement[] {
    const found = Array.from(root.querySelectorAll<HTMLElement>(ITEM_SELECTOR));
    return found.filter((node) => {
      const enclosing = node.parentElement?.closest<HTMLElement>(ITEM_SELECTOR);
      return !enclosing || enclosing === root || !root.contains(enclosing);
    });
  }

  const attachmentKey = createAttachmentKey();

  /**
   * The family's single behaviour attachment: roving focus.
   *
   * It travels inside the props object under a `Symbol` key, so a consumer
   * spreading those props onto their own element — or onto another component —
   * gets the full interaction, which an `onkeydown` prop bag could not do.
   * `keydown` and `focusin` from the focused item bubble here, so the group
   * never has to attach anything to the items themselves. Activation
   * (Enter/Space) belongs to the item, which owns its own pressed state.
   */
  function interaction(node: HTMLElement): () => void {
    const onKeyDown = (event: KeyboardEvent): void => {
      if (disabled) return;
      const nodes = itemNodes(node);
      if (nodes.length === 0) return;
      const next = rovingIndexFromKey(
        {
          activeIndex: Math.min(activeIndex, nodes.length - 1),
          count: nodes.length,
          orientation,
          dir: dir ?? "ltr",
          loop: loopFocus,
        },
        event.key,
      );
      if (next === undefined) return;
      event.preventDefault();
      activeIndex = next;
      nodes[next]?.focus();
    };
    /** Clicking or tabbing into an item moves the tab stop to it. */
    const onFocusIn = (event: FocusEvent): void => {
      const target = event.target;
      if (!(target instanceof Element)) return;
      const index = itemNodes(node).findIndex((item) => item === target || item.contains(target));
      if (index >= 0) activeIndex = index;
    };

    node.addEventListener("keydown", onKeyDown);
    node.addEventListener("focusin", onFocusIn);

    return () => {
      node.removeEventListener("keydown", onKeyDown);
      node.removeEventListener("focusin", onFocusIn);
    };
  }

  const elementProps = $derived<ChildProps>({
    // Ahead of the rest props so an explicit `role` from the caller wins.
    "role": "group",
    ...rest,
    "class": className,
    "style": style,
    "dir": dir,
    [DATA_ORIENTATION]: orientation,
    [DATA_DISABLED]: disabled ? "" : undefined,
    [attachmentKey]: interaction,
  });

  colorSwatchGroupContext.set({
    get type() {
      return type;
    },
    get value() {
      return selection;
    },
    get disabled() {
      return disabled;
    },
    get orientation() {
      return orientation;
    },
    get loopFocus() {
      return loopFocus;
    },
    get activeIndex() {
      return activeIndex;
    },
    get count() {
      return seats.length;
    },
    get groupState() {
      return groupState;
    },
    isSelected,
    toggle,
    setActiveIndex,
    tabIndexFor,
    register,
  });
</script>

{#if child}
  {@render child({ props: elementProps })}
{:else}
  <div {...elementProps}>{@render children?.()}</div>
{/if}
