// packages/react/src/components/ColorField/ColorFieldInput.tsx
import { forwardRef, useCallback, type ComponentPropsWithoutRef } from "react";
import { useColorFieldContext } from "./ColorFieldContext";

export interface ColorFieldInputProps extends ComponentPropsWithoutRef<"input"> {}

export const ColorFieldInput = forwardRef<HTMLInputElement, ColorFieldInputProps>(
  function ColorFieldInput(props, ref) {
    const ctx = useColorFieldContext();

    const handleInput = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
      ctx.onInputChange(e.target.value);
    }, [ctx]);

    const handleFocus = useCallback((e: React.FocusEvent<HTMLInputElement>) => {
      requestAnimationFrame(() => e.target.select());
    }, []);

    const handleBlur = useCallback(() => {
      ctx.commitValue(ctx.modelValue);
    }, [ctx]);

    const handleKeyDown = useCallback((e: React.KeyboardEvent<HTMLInputElement>) => {
      if (ctx.disabled || ctx.readOnly) return;
      if (e.key === "Enter") { ctx.commitValue(ctx.modelValue); return; }
      switch (e.key) {
        case "ArrowUp": e.preventDefault(); ctx.handleIncrease(); break;
        case "ArrowDown": e.preventDefault(); ctx.handleDecrease(); break;
        case "PageUp": e.preventDefault(); ctx.handleIncrease(10); break;
        case "PageDown": e.preventDefault(); ctx.handleDecrease(10); break;
        case "Home": e.preventDefault(); ctx.handleMinMaxValue("min"); break;
        case "End": e.preventDefault(); ctx.handleMinMaxValue("max"); break;
      }
    }, [ctx]);

    return (
      <input
        ref={(el) => {
          if (typeof ref === "function") ref(el);
          else if (ref) ref.current = el;
          (ctx.inputRef as React.MutableRefObject<HTMLInputElement | null>).current = el;
        }}
        type="text"
        role="spinbutton"
        aria-valuenow={ctx.modelValue}
        value={ctx.displayValue}
        disabled={ctx.disabled || undefined}
        readOnly={ctx.readOnly || undefined}
        data-disabled={ctx.disabled ? "" : undefined}
        data-readonly={ctx.readOnly ? "" : undefined}
        autoComplete="off"
        autoCorrect="off"
        spellCheck={false}
        inputMode="text"
        onChange={handleInput}
        onFocus={handleFocus}
        onBlur={handleBlur}
        onKeyDown={handleKeyDown}
        {...props}
      />
    );
  },
);

// packages/vue/src/components/ColorField/ColorFieldInput.vue
<script lang="ts">
import type { PrimitiveProps } from "reka-ui";

export interface ColorFieldInputProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
}
</script>

<script setup lang="ts">
import { nextTick, onMounted } from "vue";
import { Primitive, useForwardExpose } from "reka-ui";
import { injectColorFieldRootContext } from "./ColorFieldRoot.vue";

withDefaults(defineProps<ColorFieldInputProps>(), {
  as: "input",
});

const rootContext = injectColorFieldRootContext();
const { forwardRef, currentElement } = useForwardExpose();

onMounted(() => {
  if (currentElement.value)
    rootContext.onInputElement(currentElement.value as HTMLInputElement);
});

function onInput(event: Event) {
  const target = event.target as HTMLInputElement;
  rootContext.onInputChange(target.value);
}

function onFocus(event: FocusEvent) {
  const target = event.target as HTMLInputElement;
  nextTick(() => target.select());
}

function onBlur() {
  const parsed = rootContext.displayValue.value;
  rootContext.commitValue(
    rootContext.modelValue.value !== undefined
      ? rootContext.modelValue.value
      : undefined,
  );
}

function onKeydown(event: KeyboardEvent) {
  if (rootContext.disabled.value || rootContext.readOnly.value) return;

  if (event.key === "Enter") {
    rootContext.commitValue(rootContext.modelValue.value);
    return;
  }

  switch (event.key) {
    case "ArrowUp":
      event.preventDefault();
      rootContext.handleIncrease();
      break;
    case "ArrowDown":
      event.preventDefault();
      rootContext.handleDecrease();
      break;
    case "PageUp":
      event.preventDefault();
      rootContext.handleIncrease(10);
      break;
    case "PageDown":
      event.preventDefault();
      rootContext.handleDecrease(10);
      break;
    case "Home":
      event.preventDefault();
      rootContext.handleMinMaxValue("min");
      break;
    case "End":
      event.preventDefault();
      rootContext.handleMinMaxValue("max");
      break;
  }
}
</script>

<template>
  <Primitive
    :ref="forwardRef"
    :as="as"
    :as-child="asChild"
    type="text"
    role="spinbutton"
    :aria-valuenow="rootContext.modelValue.value"
    :aria-valuemin="undefined"
    :aria-valuemax="undefined"
    :value="rootContext.displayValue.value"
    :disabled="rootContext.disabled.value || undefined"
    :readonly="rootContext.readOnly.value || undefined"
    :data-disabled="rootContext.disabled.value ? '' : undefined"
    :data-readonly="rootContext.readOnly.value ? '' : undefined"
    autocomplete="off"
    autocorrect="off"
    spellcheck="false"
    inputmode="text"
    @input="onInput"
    @focus="onFocus"
    @blur="onBlur"
    @keydown="onKeydown"
  >
    <slot />
  </Primitive>
</template>
