// packages/angular/src/components/color-slider/root/color-slider-root.ts
import {
  afterNextRender,
  booleanAttribute,
  computed,
  DestroyRef,
  Directive,
  ElementRef,
  HostAttributeToken,
  inject,
  input,
  model,
  output,
  signal,
} from "@angular/core";
import type { FormValueControl } from "@angular/forms/signals";
import { Color, type SpaceId } from "@urcolor/core";
import {
  applyDisplayValue,
  colorToDisplayValue,
  createDragController,
  DATA_DISABLED,
  DATA_DRAGGING,
  DATA_ORIENTATION,
  FEEDBACK_EPSILON,
  positionFromValue,
  resolveChannelConfig,
  valueFromKey,
  valueFromPosition,
  type SliderState,
} from "@urcolor/primitives";

/** The axis a `ColorSlider` runs along. */
export type ColorSliderOrientation = "horizontal" | "vertical";

/** The colour a root falls back to when `[(value)]` is never bound. */
export const COLOR_SLIDER_DEFAULT_COLOR: Color = Color.parse("hsl(210, 80%, 50%)")!;

/**
 * The root of a colour slider. Owns the colour, the interaction, and every
 * piece of state the other parts read through `inject(ColorSliderRoot)`.
 *
 * ```html
 * <div urcColorSliderRoot [(value)]="color" colorSpace="oklch" channel="h">
 *   <div urcColorSliderTrack>
 *     <canvas urcColorSliderGradient></canvas>
 *     <div urcColorSliderThumb></div>
 *   </div>
 * </div>
 * ```
 *
 * `implements FormValueControl<Color>` is satisfied by the `value` model alone,
 * which is what makes `<div urcColorSliderRoot [field]="form.brandColor">` work.
 */
@Directive({
  selector: "[urcColorSliderRoot]",
  exportAs: "urcColorSliderRoot",
  host: {
    [`[attr.${DATA_ORIENTATION}]`]: "orientation()",
    [`[attr.${DATA_DISABLED}]`]: "isDisabled() ? '' : null",
    [`[attr.${DATA_DRAGGING}]`]: "dragging() ? '' : null",
    "[attr.aria-disabled]": "isDisabled() ? 'true' : null",
    "(pointerdown)": "onPointerDown($event)",
    "(pointermove)": "onPointerMove($event)",
    "(pointerup)": "onPointerUp($event)",
    "(pointercancel)": "onPointerCancel()",
    "(keydown)": "onKeyDown($event)",
    "(keyup)": "onKeyUp()",
  },
})
export class ColorSliderRoot implements FormValueControl<Color> {
  /** The colour, two-way bindable as `[(value)]`. Also the Signal Forms contract. */
  readonly value = model<Color>(COLOR_SLIDER_DEFAULT_COLOR);
  /** Emitted once at the end of an interaction, never mid-drag. */
  readonly valueCommit = output<Color>();

  /** The colour space the slider operates in. */
  readonly colorSpace = input<SpaceId>("hsl");
  /** The channel this slider controls, or `"alpha"`. */
  readonly channel = input<string>("h");
  /** The axis the slider runs along. */
  readonly orientation = input<ColorSliderOrientation>("horizontal");
  /** Whether the slider runs opposite to its natural direction. */
  readonly inverted = input(false, { transform: booleanAttribute });

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly destroyRef = inject(DestroyRef);

  /**
   * `disabled` and `dir` are DOM state, not inputs. The static host attribute
   * is read at construction — which works under SSR, where there is no DOM —
   * and a `MutationObserver` installed after the first render keeps both live.
   */
  private readonly disabledState = signal(
    inject(new HostAttributeToken("disabled"), { optional: true }) !== null,
  );

  private readonly dirState = signal<"ltr" | "rtl">(
    inject(new HostAttributeToken("dir"), { optional: true }) === "rtl" ? "rtl" : "ltr",
  );

  private readonly draggingState = signal(false);

  /**
   * Whether interaction is refused. Named `isDisabled` rather than `disabled`
   * because `FormUiControl` reserves `disabled` for an `InputSignal<boolean>`.
   */
  readonly isDisabled = this.disabledState.asReadonly();
  /** The resolved reading direction. */
  readonly dir = this.dirState.asReadonly();
  /** True while a pointer drag is in flight. */
  readonly dragging = this.draggingState.asReadonly();

  private readonly channelConfig = computed(() =>
    resolveChannelConfig(this.colorSpace(), this.channel()),
  );

  /** The channel in display units, plus its bounds and axis flags. */
  readonly sliderState = computed<SliderState>(() => {
    const config = this.channelConfig();
    return {
      value: colorToDisplayValue(this.value(), this.colorSpace(), this.channel()),
      min: config?.min ?? 0,
      max: config?.max ?? 100,
      step: config?.step ?? 1,
      orientation: this.orientation(),
      dir: this.dir(),
      inverted: this.inverted(),
      disabled: this.isDisabled(),
    };
  });

  /** 0-1 offset of the thumb from the track's CSS start edge. */
  readonly position = computed(() => positionFromValue(this.sliderState()));

  /** True while a key that changes the value is held down. */
  private keyboardActive = false;

  private readonly drag = createDragController({
    getElement: () => this.host.nativeElement,
    isDisabled: () => this.isDisabled(),
    onStart: () => this.draggingState.set(true),
    onMove: (point) => {
      const state = this.sliderState();
      const offset = state.orientation === "vertical" ? point.normalizedY : point.normalizedX;
      this.setDisplayValue(valueFromPosition(state, offset));
    },
    onEnd: () => {
      this.draggingState.set(false);
      this.valueCommit.emit(this.value());
    },
  });

  constructor() {
    // `afterNextRender` never runs on the server, so this is the only place a
    // directive may touch the DOM.
    afterNextRender(() => {
      const element = this.host.nativeElement;
      this.syncDomState(element);
      if (typeof MutationObserver === "undefined") return;
      const observer = new MutationObserver(() => this.syncDomState(element));
      observer.observe(element, { attributes: true, attributeFilter: ["disabled", "dir"] });
      this.destroyRef.onDestroy(() => observer.disconnect());
    });

    this.destroyRef.onDestroy(() => this.drag.cancel());
  }

  /** Writes one display-space channel value back as a colour. */
  private setDisplayValue(next: number): void {
    if (!this.channelConfig()) return;
    if (Math.abs(next - this.sliderState().value) < FEEDBACK_EPSILON) return;
    this.value.set(applyDisplayValue(this.value(), this.colorSpace(), this.channel(), next));
  }

  /**
   * `getComputedStyle` is used for direction because `dir` inherits from any
   * ancestor; reading the host attribute alone would miss `<html dir="rtl">`.
   */
  private syncDomState(element: HTMLElement): void {
    this.disabledState.set(element.hasAttribute("disabled"));
    const direction
      = typeof getComputedStyle === "function"
        ? getComputedStyle(element).direction
        : element.getAttribute("dir");
    this.dirState.set(direction === "rtl" ? "rtl" : "ltr");
  }

  protected onPointerDown(event: PointerEvent): void {
    this.drag.pointerDown(event);
    // `pointerDown` calls `preventDefault`, which suppresses the focus the
    // browser would have moved to the thumb; do it explicitly instead.
    if (this.drag.isDragging) {
      this.host.nativeElement.querySelector<HTMLElement>("[role='slider']")?.focus();
    }
  }

  protected onPointerMove(event: PointerEvent): void {
    this.drag.pointerMove(event);
  }

  protected onPointerUp(event: PointerEvent): void {
    this.drag.pointerUp(event);
  }

  protected onPointerCancel(): void {
    this.drag.cancel();
    this.draggingState.set(false);
  }

  /**
   * Keyboard lives on the root rather than the thumb: `keydown` from the
   * focused thumb bubbles here, so one listener covers both.
   */
  protected onKeyDown(event: KeyboardEvent): void {
    const next = valueFromKey(this.sliderState(), event);
    if (next === undefined) return;
    event.preventDefault();
    this.keyboardActive = true;
    this.setDisplayValue(next);
  }

  protected onKeyUp(): void {
    if (!this.keyboardActive) return;
    this.keyboardActive = false;
    this.valueCommit.emit(this.value());
  }
}

// packages/svelte/src/lib/components/color-slider/root/ColorSliderRoot.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { Color, SpaceId } from "@urcolor/core";
  import type { ChildSnippetArgs } from "../../../shared/child.js";

  export interface ColorSliderRootProps extends HTMLAttributes<HTMLDivElement> {
    /** The colour value. Bindable: `bind:value`. */
    value?: Color | string | null;
    /** The colour used until the first interaction when `value` is not bound. */
    defaultValue?: Color | string | null;
    /** The colour space mode (e.g. `"hsl"`, `"oklch"`). */
    colorSpace?: SpaceId;
    /** Which channel this slider controls (e.g. `"h"`, `"s"`, `"l"`, `"alpha"`). */
    channel?: string;
    /** When true, prevents the user from interacting with the slider. */
    disabled?: boolean;
    /** The reading direction. */
    dir?: "ltr" | "rtl";
    /** Whether the slider runs opposite to its natural direction. */
    inverted?: boolean;
    /** The orientation of the slider. */
    orientation?: "horizontal" | "vertical";
    /** Called on every change, including mid-drag. */
    onValueChange?: (color: Color) => void;
    /** Called once at the end of an interaction. */
    onValueCommit?: (color: Color) => void;
    /** Replaces the default element; receives the props it would have received. */
    child?: Snippet<[ChildSnippetArgs]>;
  }
</script>

<script lang="ts">
  import { untrack } from "svelte";
  import { createAttachmentKey } from "svelte/attachments";
  import { Color as ColorClass } from "@urcolor/core";
  import {
    applyDisplayValue,
    colorToDisplayValue,
    createDragController,
    DATA_DISABLED,
    DATA_DRAGGING,
    DATA_ORIENTATION,
    FEEDBACK_EPSILON,
    parseColor,
    positionFromValue,
    resolveChannelConfig,
    valueFromKey,
    valueFromPosition,
    type SliderState,
  } from "@urcolor/primitives";
  import type { ChildProps } from "../../../shared/child.js";
  import { colorSliderContext } from "./context.svelte.js";

  const DEFAULT_COLOR = ColorClass.parse("hsl(210, 80%, 50%)")!;

  let {
    value = $bindable(),
    defaultValue,
    colorSpace = "hsl",
    channel = "h",
    disabled = false,
    dir,
    inverted = false,
    orientation = "horizontal",
    onValueChange,
    onValueCommit,
    class: className,
    style,
    children,
    child,
    ...rest
  }: ColorSliderRootProps = $props();

  /**
   * Uncontrolled fallback, kept in sync so it and `value` never disagree.
   * `untrack` states the intent that only the initial props are read here.
   */
  let internalColor = $state<Color>(
    untrack(() => parseColor(value) ?? parseColor(defaultValue) ?? DEFAULT_COLOR),
  );
  let dragging = $state(false);
  /** Plain, non-reactive: only the drag controller reads it, and only on pointer events. */
  let element: HTMLElement | null = null;

  const color = $derived(parseColor(value) ?? internalColor);
  const channelConfig = $derived(resolveChannelConfig(colorSpace, channel));
  const sliderState = $derived<SliderState>({
    value: colorToDisplayValue(color, colorSpace, channel),
    min: channelConfig?.min ?? 0,
    max: channelConfig?.max ?? 100,
    step: channelConfig?.step ?? 1,
    orientation,
    dir: dir ?? "ltr",
    inverted,
    disabled,
  });

  /** Writes one display-space channel value back as a colour. */
  function setDisplayValue(next: number): void {
    if (!channelConfig) return;
    if (Math.abs(next - sliderState.value) < FEEDBACK_EPSILON) return;
    const nextColor = applyDisplayValue(color, colorSpace, channel, next);
    internalColor = nextColor;
    value = nextColor;
    onValueChange?.(nextColor);
  }

  function commit(): void {
    onValueCommit?.(color);
  }

  const drag = createDragController({
    getElement: () => element,
    isDisabled: () => disabled,
    onStart: () => {
      dragging = true;
    },
    onMove: (point) => {
      const position = orientation === "vertical" ? point.normalizedY : point.normalizedX;
      setDisplayValue(valueFromPosition(sliderState, position));
    },
    onEnd: () => {
      dragging = false;
      commit();
    },
  });

  const attachmentKey = createAttachmentKey();

  /**
   * The family's single behaviour attachment: pointer capture, keyboard, and
   * the element that position→value is measured against.
   *
   * It travels inside the props object under a `Symbol` key, so a consumer
   * spreading those props onto their own element — or onto another component —
   * gets the full interaction, which an `onpointerdown` prop bag could not do.
   * Keyboard lives here too rather than on the thumb: `keydown` from the
   * focused thumb bubbles to this element, so one attachment covers both.
   */
  function interaction(node: HTMLElement): () => void {
    element = node;
    let keyboardActive = false;

    const onPointerDown = (event: PointerEvent): void => {
      drag.pointerDown(event);
      // `pointerDown` calls `preventDefault`, which suppresses the focus the
      // browser would have moved to the thumb; do it explicitly instead.
      if (drag.isDragging) node.querySelector<HTMLElement>("[role='slider']")?.focus();
    };
    const onPointerMove = (event: PointerEvent): void => drag.pointerMove(event);
    const onPointerUp = (event: PointerEvent): void => drag.pointerUp(event);
    const onPointerCancel = (): void => {
      drag.cancel();
      dragging = false;
    };
    const onKeyDown = (event: KeyboardEvent): void => {
      const next = valueFromKey(sliderState, event);
      if (next === undefined) return;
      event.preventDefault();
      keyboardActive = true;
      setDisplayValue(next);
    };
    const onKeyUp = (): void => {
      if (!keyboardActive) return;
      keyboardActive = false;
      commit();
    };

    node.addEventListener("pointerdown", onPointerDown);
    node.addEventListener("pointermove", onPointerMove);
    node.addEventListener("pointerup", onPointerUp);
    node.addEventListener("pointercancel", onPointerCancel);
    node.addEventListener("keydown", onKeyDown);
    node.addEventListener("keyup", onKeyUp);

    return () => {
      node.removeEventListener("pointerdown", onPointerDown);
      node.removeEventListener("pointermove", onPointerMove);
      node.removeEventListener("pointerup", onPointerUp);
      node.removeEventListener("pointercancel", onPointerCancel);
      node.removeEventListener("keydown", onKeyDown);
      node.removeEventListener("keyup", onKeyUp);
      drag.cancel();
      dragging = false;
      element = null;
    };
  }

  const elementProps = $derived<ChildProps>({
    ...rest,
    "class": className,
    "style": style,
    "dir": dir,
    [DATA_ORIENTATION]: orientation,
    [DATA_DISABLED]: disabled ? "" : undefined,
    [DATA_DRAGGING]: dragging ? "" : undefined,
    [attachmentKey]: interaction,
  });

  colorSliderContext.set({
    get color() {
      return color;
    },
    get colorSpace() {
      return colorSpace;
    },
    get channel() {
      return channel;
    },
    get orientation() {
      return orientation;
    },
    get inverted() {
      return inverted;
    },
    get disabled() {
      return disabled;
    },
    get dragging() {
      return dragging;
    },
    get sliderState() {
      return sliderState;
    },
    get position() {
      return positionFromValue(sliderState);
    },
  });
</script>

{#if child}
  {@render child({ props: elementProps })}
{:else}
  <div {...elementProps}>{@render children?.()}</div>
{/if}
