// packages/angular/src/components/color-slider/range/color-slider-range.ts
import { computed, Directive, inject } from "@angular/core";
import { clamp, DATA_DISABLED, DATA_ORIENTATION, positionFromValue } from "@urcolor/primitives";
import { ColorSliderRoot } from "../root/color-slider-root";

/**
 * The filled portion of the track, measured from the channel's minimum end.
 *
 * Every layout declaration is a host style binding, so a consumer's own
 * `style` attribute — a template-level binding — still wins the cascade.
 */
@Directive({
  selector: "[urcColorSliderRange]",
  exportAs: "urcColorSliderRange",
  host: {
    [`[attr.${DATA_ORIENTATION}]`]: "root.orientation()",
    [`[attr.${DATA_DISABLED}]`]: "root.isDisabled() ? '' : null",
    "[style.position]": "'absolute'",
    "[style.top]": "top()",
    "[style.bottom]": "bottom()",
    "[style.left]": "left()",
    "[style.right]": "right()",
    "[style.width]": "width()",
    "[style.height]": "height()",
  },
})
export class ColorSliderRange {
  protected readonly root = inject(ColorSliderRoot);

  private readonly vertical = computed(() => this.root.sliderState().orientation === "vertical");

  /** Filled share of the track, 0-1. */
  private readonly fraction = computed(() => {
    const state = this.root.sliderState();
    if (state.max === state.min) return 0;
    return clamp((state.value - state.min) / (state.max - state.min), 0, 1);
  });

  /**
   * Whether the minimum sits at the track's CSS start edge. Asking the
   * primitive where `min` renders keeps `dir`, `inverted` and vertical
   * flipping in one place instead of re-deriving them here.
   */
  private readonly fillsFromStart = computed(() => {
    const state = this.root.sliderState();
    return positionFromValue({ ...state, value: state.min }) === 0;
  });

  private readonly extent = computed(() => `${this.fraction() * 100}%`);

  protected readonly top = computed(() =>
    this.vertical() ? (this.fillsFromStart() ? "0" : null) : "0",
  );

  protected readonly bottom = computed(() =>
    this.vertical() ? (this.fillsFromStart() ? null : "0") : "0",
  );

  protected readonly left = computed(() =>
    this.vertical() ? "0" : this.fillsFromStart() ? "0" : null,
  );

  protected readonly right = computed(() =>
    this.vertical() ? "0" : this.fillsFromStart() ? null : "0",
  );

  protected readonly width = computed(() => (this.vertical() ? null : this.extent()));

  protected readonly height = computed(() => (this.vertical() ? this.extent() : null));
}

// packages/svelte/src/lib/components/color-slider/range/ColorSliderRange.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { ChildSnippetArgs } from "../../../shared/child.js";

  export interface ColorSliderRangeProps extends HTMLAttributes<HTMLDivElement> {
    /** Replaces the default element; receives the props it would have received. */
    child?: Snippet<[ChildSnippetArgs]>;
  }
</script>

<script lang="ts">
  import { clamp, DATA_DISABLED, DATA_ORIENTATION, positionFromValue } from "@urcolor/primitives";
  import type { ChildProps } from "../../../shared/child.js";
  import { colorSliderContext } from "../root/context.svelte.js";

  let { class: className, style, children, child, ...rest }: ColorSliderRangeProps = $props();

  const context = colorSliderContext.get();

  const state = $derived(context.sliderState);
  /** Filled share of the track, measured from the minimum end. */
  const fraction = $derived(
    state.max === state.min ? 0 : clamp((state.value - state.min) / (state.max - state.min), 0, 1),
  );
  /**
   * Whether the minimum sits at the track's CSS start edge. Asking the
   * primitive where `min` renders keeps `dir`, `inverted` and vertical flipping
   * in one place instead of re-deriving them here.
   */
  const fillsFromStart = $derived(positionFromValue({ ...state, value: state.min }) === 0);
  const layout = $derived(
    state.orientation === "vertical"
      ? `position:absolute;left:0;right:0;height:${fraction * 100}%;${fillsFromStart ? "top:0" : "bottom:0"};`
      : `position:absolute;top:0;bottom:0;width:${fraction * 100}%;${fillsFromStart ? "left:0" : "right:0"};`,
  );

  const elementProps = $derived<ChildProps>({
    ...rest,
    class: className,
    // The caller's declarations come last so they win the cascade.
    style: style ? `${layout}${style}` : layout,
    [DATA_ORIENTATION]: state.orientation,
    [DATA_DISABLED]: state.disabled ? "" : undefined,
  });
</script>

{#if child}
  {@render child({ props: elementProps })}
{:else}
  <div {...elementProps}>{@render children?.()}</div>
{/if}
