// docs/components/vue/demo/ColorAreaOKLCh.vue
<script setup lang="ts">
import "internationalized-color/css";
import {
  ColorAreaRoot,
  ColorAreaGradient,
  ColorAreaThumb,
  useColor,
} from "@urcolor/vue";

const { color } = useColor("hsl(210, 80%, 50%)");
</script>

<template>
  <ColorAreaRoot
    v-model="color"
    color-space="oklch"
    channel-x="c"
    channel-y="l"
    as="div"
    class="
      relative block h-[200px] w-full cursor-crosshair touch-none overflow-clip
      rounded-lg
    "
    aria-label="OKLCh color area"
  >
    <ColorAreaGradient
      as="div"
      class="absolute inset-0"
    />
    <ColorAreaThumb
      as="div"
      class="
        absolute size-5 transform-(--reka-slider-area-thumb-transform)
        rounded-full border-2 border-white
        shadow-[0_0_0_1px_rgba(0,0,0,0.3),0_2px_4px_rgba(0,0,0,0.3)]
      "
    />
  </ColorAreaRoot>
</template>

// docs/components/react/demo/ColorAreaOKLCh.tsx
import "internationalized-color/css";
import {
  ColorAreaRoot,
  ColorAreaTrack,
  ColorAreaGradient,
  ColorAreaThumb,
  useColor,
} from "@urcolor/react";

export default function ColorAreaOKLCh() {
  const { color, setColor } = useColor("hsl(210, 80%, 50%)");

  return (
    <ColorAreaRoot
      value={color}
      onValueChange={setColor}
      colorSpace="oklch"
      channelX="c"
      channelY="l"
      className="block"
      aria-label="OKLCh color area"
    >
      <ColorAreaTrack
        className="
          relative h-[200px] w-full cursor-crosshair touch-none overflow-clip
          rounded-lg
        "
      >
        <ColorAreaGradient className="absolute inset-0" />
        <ColorAreaThumb
          className="
            absolute size-5
            rounded-full border-2 border-white
            shadow-[0_0_0_1px_rgba(0,0,0,0.3),0_2px_4px_rgba(0,0,0,0.3)]
          "
        />
      </ColorAreaTrack>
    </ColorAreaRoot>
  );
}
