// packages/svelte/src/lib/components/color-field/root/ColorFieldRoot.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { Color, SpaceId } from "@urcolor/core";
  import type { ChildSnippetArgs } from "../../../shared/child.js";
  import type { ColorFieldFormat } from "./context.svelte.js";

  export interface ColorFieldRootProps extends HTMLAttributes<HTMLDivElement> {
    /** The colour value. Bindable: `bind:value`. */
    value?: Color | string | null;
    /** The colour used until the first interaction when `value` is not bound. */
    defaultValue?: Color | string | null;
    /** The colour space mode (e.g. `"hsl"`, `"oklch"`). */
    colorSpace?: SpaceId;
    /** Which channel this field controls (e.g. `"h"`, `"s"`, `"l"`, `"alpha"`). */
    channel?: string;
    /** Channel display format. Auto-derived from the channel config when unset. */
    format?: ColorFieldFormat;
    /** Minimum allowed value, in display units. */
    min?: number;
    /** Maximum allowed value, in display units. */
    max?: number;
    /** Step increment for arrow keys and the stepper buttons. */
    step?: number;
    /** When true, prevents the user from interacting with the field. */
    disabled?: boolean;
    /** When true, the value is shown but cannot be edited. */
    readOnly?: boolean;
    /** Called on every change, including mid-edit. */
    onValueChange?: (color: Color) => void;
    /** Called once at the end of an interaction. */
    onValueCommit?: (color: Color) => void;
    /** Replaces the default element; receives the props it would have received. */
    child?: Snippet<[ChildSnippetArgs]>;
  }
</script>

<script lang="ts">
  import { untrack } from "svelte";
  import { Color as ColorClass, type ChannelConfig } from "@urcolor/core";
  import {
    applyDisplayValue,
    clamp,
    colorToDisplayValue,
    DATA_DISABLED,
    DATA_READONLY,
    FEEDBACK_EPSILON,
    parseColor,
    resolveChannelConfig,
    snapToStep,
  } from "@urcolor/primitives";
  import type { ChildProps } from "../../../shared/child.js";
  // `ColorFieldFormat` is already in scope from the module block above.
  import { colorFieldContext } from "./context.svelte.js";

  const HEX_MAX = 0xffffff;

  let {
    value = $bindable(),
    defaultValue,
    colorSpace = "hsl",
    channel = "h",
    format: formatProp,
    min: minProp,
    max: maxProp,
    step: stepProp,
    disabled = false,
    readOnly = false,
    onValueChange,
    onValueCommit,
    class: className,
    style,
    children,
    child,
    ...rest
  }: ColorFieldRootProps = $props();

  /**
   * Uncontrolled fallback, kept in sync so it and `value` never disagree.
   * `untrack` states the intent that only the initial props are read here.
   */
  let internalColor = $state<Color | undefined>(
    untrack(() => parseColor(value) ?? parseColor(defaultValue)),
  );

  const color = $derived(parseColor(value) ?? internalColor);
  const isAlpha = $derived(channel === "alpha");
  const channelConfig = $derived<ChannelConfig | undefined>(resolveChannelConfig(colorSpace, channel));
  const effectiveFormat = $derived<ColorFieldFormat>(formatProp ?? channelConfig?.format ?? "number");
  const isHexMode = $derived(effectiveFormat === "hex");
  const effectiveMin = $derived(minProp ?? channelConfig?.min ?? 0);
  const effectiveMax = $derived(maxProp ?? channelConfig?.max ?? (isHexMode ? HEX_MAX : 100));
  const effectiveStep = $derived(stepProp ?? channelConfig?.step ?? 1);

  /** The channel value the current colour implies, in display units. */
  function displayFromColor(): number | undefined {
    const current = color;
    if (!current) return undefined;
    if (isHexMode) {
      const hex = current.toString("hex").replace(/^#/, "");
      if (!hex) return undefined;
      return Number.parseInt(hex.slice(0, 6), 16);
    }
    if (!channelConfig) return undefined;
    if (isAlpha) return Math.round(current.alpha * 100);
    return colorToDisplayValue(current, colorSpace, channel);
  }

  function formatValue(val: number | undefined): string {
    if (val === undefined) return "";
    switch (effectiveFormat) {
      case "degree":
        return `${val}°`;
      case "percentage":
        return `${val}%`;
      case "hex":
        return `#${Math.round(val).toString(16).padStart(6, "0")}`;
      default:
        return String(val);
    }
  }

  function parseValue(text: string): number | undefined {
    const trimmed = text.trim();
    if (trimmed === "") return undefined;
    switch (effectiveFormat) {
      case "degree":
        return Number.parseFloat(trimmed.replace(/[°]$|deg$/i, ""));
      case "percentage":
        return Number.parseFloat(trimmed.replace(/%$/, ""));
      case "hex": {
        const hex = trimmed.replace(/^#/, "");
        if (!/^[0-9a-f]*$/i.test(hex)) return undefined;
        return Number.parseInt(hex, 16);
      }
      default:
        return Number.parseFloat(trimmed);
    }
  }

  function clampValue(val: number): number {
    return snapToStep(clamp(val, effectiveMin, effectiveMax), effectiveMin, effectiveMax, effectiveStep);
  }

  /**
   * The field's own numeric state. It is not purely derived from `color`: the
   * field is usable before any colour exists, and mid-edit text may not yet
   * round-trip. `$effect` below syncs it down whenever the colour moves.
   */
  let numericValue = $state<number | undefined>(untrack(() => displayFromColor()));
  let displayValue = $state<string>(untrack(() => formatValue(numericValue)));

  $effect(() => {
    const next = displayFromColor();
    if (next === undefined) return;
    // Writes are untracked reads of our own state, so this can never re-enter.
    if (Math.abs(next - (untrack(() => numericValue) ?? 0)) <= FEEDBACK_EPSILON) return;
    numericValue = next;
    displayValue = formatValue(next);
  });

  function rebuildColor(displayVal: number): Color | undefined {
    const current = color;
    if (!current) return undefined;
    if (isHexMode) {
      const hexStr = `#${Math.round(clamp(displayVal, 0, HEX_MAX)).toString(16).padStart(6, "0")}`;
      return ColorClass.parse(hexStr) ?? undefined;
    }
    if (!channelConfig) return undefined;
    return applyDisplayValue(current, colorSpace, channel, displayVal);
  }

  function emitColor(val: number): Color | undefined {
    const nextColor = rebuildColor(val);
    if (!nextColor) return undefined;
    internalColor = nextColor;
    // A no-op locally when the caller did not bind, so bound and unbound
    // callers see identical behaviour.
    value = nextColor;
    onValueChange?.(nextColor);
    return nextColor;
  }

  function setValue(val: number): void {
    numericValue = val;
    displayValue = formatValue(val);
    const nextColor = emitColor(val);
    if (nextColor) onValueCommit?.(nextColor);
  }

  function commitValue(val: number | undefined): void {
    if (val === undefined || Number.isNaN(val)) {
      numericValue = undefined;
      displayValue = "";
      return;
    }
    setValue(isHexMode ? clamp(Math.round(val), effectiveMin, effectiveMax) : clampValue(val));
  }

  function onInputChange(text: string): void {
    displayValue = text;
    const parsed = parseValue(text);
    if (parsed === undefined || Number.isNaN(parsed)) return;
    numericValue = parsed;
    emitColor(parsed);
  }

  function handleIncrease(multiplier = 1): void {
    if (disabled || readOnly) return;
    setValue(clampValue((numericValue ?? 0) + effectiveStep * multiplier));
  }

  function handleDecrease(multiplier = 1): void {
    if (disabled || readOnly) return;
    setValue(clampValue((numericValue ?? 0) - effectiveStep * multiplier));
  }

  function handleMinMaxValue(type: "min" | "max"): void {
    if (disabled || readOnly) return;
    setValue(type === "min" ? effectiveMin : effectiveMax);
  }

  const isDecreaseDisabled = $derived(numericValue !== undefined && clampValue(numericValue) <= effectiveMin);
  const isIncreaseDisabled = $derived(numericValue !== undefined && clampValue(numericValue) >= effectiveMax);

  const elementProps = $derived<ChildProps>({
    ...rest,
    class: className,
    style: style,
    [DATA_DISABLED]: disabled ? "" : undefined,
    [DATA_READONLY]: readOnly ? "" : undefined,
  });

  colorFieldContext.set({
    get modelValue() {
      return numericValue;
    },
    get displayValue() {
      return displayValue;
    },
    get disabled() {
      return disabled;
    },
    get readOnly() {
      return readOnly;
    },
    get isDecreaseDisabled() {
      return isDecreaseDisabled;
    },
    get isIncreaseDisabled() {
      return isIncreaseDisabled;
    },
    get format() {
      return effectiveFormat;
    },
    handleIncrease,
    handleDecrease,
    handleMinMaxValue,
    commitValue,
    onInputChange,
  });
</script>

{#if child}
  {@render child({ props: elementProps })}
{:else}
  <div {...elementProps}>{@render children?.()}</div>
{/if}

// packages/react/src/components/color-field/root/ColorFieldRoot.tsx
import { forwardRef, useCallback, useMemo, useRef, useState } from "react";
import { Color, type SpaceId } from "@urcolor/core";
import { getChannelConfig, displayToNative, nativeToDisplay, type ChannelConfig } from "@urcolor/shared";
import { clamp, snapToStep } from "../../../utils";
import { ColorFieldContext, type ColorFieldContextValue } from "./ColorFieldRootContext";

export interface ColorFieldRootProps {
  /** The controlled color value. */
  value?: Color | string | null;
  /** The default color value when uncontrolled. */
  defaultValue?: Color | string | null;
  /** The color space mode (e.g. 'hsl', 'oklch'). */
  colorSpace?: SpaceId;
  /** Which channel this field controls (e.g. 'h', 's', 'l'). */
  channel?: string;
  /** Channel display format. Auto-derived from colorSpace config if not set. */
  format?: "number" | "degree" | "percentage" | "hex";
  /** Minimum allowed value. */
  min?: number;
  /** Maximum allowed value. */
  max?: number;
  /** Step increment for arrow keys. */
  step?: number;
  /** Whether the field is disabled. */
  disabled?: boolean;
  /** Whether the field is read-only. */
  readOnly?: boolean;
  /** Callback fired when the color value changes. */
  onValueChange?: (color: Color) => void;
  /** Callback fired when the value changes at the end of an interaction. */
  onValueCommit?: (color: Color) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  as?: React.ElementType;
}

function parseColor(v: Color | string | null | undefined): Color | undefined {
  if (!v) return undefined;
  if (v instanceof Color) return v;
  return Color.parse(v) ?? undefined;
}

const ALPHA_CONFIG: ChannelConfig = { key: "alpha", label: "Alpha", min: 0, max: 100, step: 1, format: "percentage", nativeMin: 0, nativeMax: 1 };

export const ColorFieldRoot = forwardRef<HTMLDivElement, ColorFieldRootProps>(
  function ColorFieldRoot(props, ref) {
    const {
      value: valueProp,
      defaultValue: defaultValueProp,
      colorSpace = "hsl",
      channel = "h",
      format: formatProp,
      min: minProp,
      max: maxProp,
      step: stepProp,
      disabled = false,
      readOnly = false,
      onValueChange,
      onValueCommit,
      children,
      className,
      style,
      as: Component = "div",
    } = props;

    const isControlled = valueProp !== undefined;
    const [internalColor, setInternalColor] = useState<Color | undefined>(
      () => parseColor(valueProp) ?? parseColor(defaultValueProp),
    );

    const prevValueRef = useRef(valueProp);
    if (valueProp !== prevValueRef.current) {
      prevValueRef.current = valueProp;
      const parsed = parseColor(valueProp);
      if (parsed) setInternalColor(parsed);
    }

    const colorRef = isControlled ? (parseColor(valueProp) ?? internalColor) : internalColor;

    const isAlpha = channel === "alpha";
    const channelConfig = isAlpha ? ALPHA_CONFIG : getChannelConfig(colorSpace, channel);

    const effectiveFormat = formatProp ?? channelConfig?.format ?? "number";
    const isHexMode = effectiveFormat === "hex";
    const effectiveMin = minProp ?? channelConfig?.min ?? 0;
    const effectiveMax = maxProp ?? channelConfig?.max ?? (isHexMode ? 0xFFFFFF : 100);
    const effectiveStep = stepProp ?? channelConfig?.step ?? 1;

    function getDisplayValue(): number | undefined {
      if (!colorRef) return undefined;
      if (isHexMode) {
        const hex = colorRef.toString("hex").replace(/^#/, "");
        if (!hex) return undefined;
        return Number.parseInt(hex.slice(0, 6), 16);
      }
      if (!channelConfig) return undefined;
      if (isAlpha) return Math.round(colorRef.alpha * 100);
      const converted = colorRef.to(colorSpace);
      const raw = converted.get(channel);
      return nativeToDisplay(channelConfig, raw);
    }

    const [numericValue, setNumericValue] = useState<number | undefined>(() => getDisplayValue());

    // Sync from color changes
    const prevColorRef = useRef(colorRef);
    if (colorRef !== prevColorRef.current) {
      prevColorRef.current = colorRef;
      const v = getDisplayValue();
      if (v !== undefined && Math.abs((v ?? 0) - (numericValue ?? 0)) > 0.001) {
        setNumericValue(v);
      }
    }

    function formatValue(val: number | undefined): string {
      if (val === undefined) return "";
      switch (effectiveFormat) {
        case "degree": return `${val}\u00B0`;
        case "percentage": return `${val}%`;
        case "hex": return `#${Math.round(val).toString(16).padStart(6, "0")}`;
        default: return String(val);
      }
    }

    function parseValue(text: string): number | undefined {
      const trimmed = text.trim();
      if (trimmed === "") return undefined;
      switch (effectiveFormat) {
        case "degree": return Number.parseFloat(trimmed.replace(/[\u00B0]$|deg$/i, ""));
        case "percentage": return Number.parseFloat(trimmed.replace(/%$/, ""));
        case "hex": {
          const hex = trimmed.replace(/^#/, "");
          if (!/^[0-9a-f]*$/i.test(hex)) return undefined;
          return Number.parseInt(hex, 16);
        }
        default: return Number.parseFloat(trimmed);
      }
    }

    function clampValue(val: number): number {
      let clamped = clamp(val, effectiveMin, effectiveMax);
      clamped = snapToStep(clamped, effectiveMin, effectiveMax, effectiveStep);
      return clamped;
    }

    const [displayValue, setDisplayValue] = useState(() => formatValue(numericValue));

    // Keep display value in sync
    const prevNumericRef = useRef(numericValue);
    if (numericValue !== prevNumericRef.current) {
      prevNumericRef.current = numericValue;
      setDisplayValue(formatValue(numericValue));
    }

    function rebuildColor(displayVal: number): Color | undefined {
      if (!colorRef) return undefined;
      if (isHexMode) {
        const hexStr = `#${Math.round(clamp(displayVal, 0, 0xFFFFFF)).toString(16).padStart(6, "0")}`;
        return Color.parse(hexStr) ?? undefined;
      }
      if (!channelConfig) return undefined;
      if (isAlpha) return colorRef.withAlpha(displayVal / 100);
      const nativeVal = displayToNative(channelConfig, displayVal);
      return colorRef.with({ space: colorSpace, [channel]: nativeVal });
    }

    function emitColor(val: number): Color | undefined {
      const newColor = rebuildColor(val);
      if (newColor) {
        if (!isControlled) setInternalColor(newColor);
        onValueChange?.(newColor);
      }
      return newColor;
    }

    const inputRef = useRef<HTMLInputElement>(null);

    const commitValue = useCallback((val: number | undefined) => {
      if (val === undefined || Number.isNaN(val)) {
        setNumericValue(undefined);
        setDisplayValue("");
        return;
      }
      const clamped = isHexMode ? clamp(Math.round(val), effectiveMin, effectiveMax) : clampValue(val);
      setNumericValue(clamped);
      setDisplayValue(formatValue(clamped));
      const newColor = emitColor(clamped);
      if (newColor) onValueCommit?.(newColor);
    }, [isHexMode, effectiveMin, effectiveMax, effectiveStep, colorRef, channelConfig, isAlpha, colorSpace, channel, isControlled, onValueChange, onValueCommit]);

    const onInputChange = useCallback((text: string) => {
      setDisplayValue(text);
      const parsed = parseValue(text);
      if (parsed !== undefined && !Number.isNaN(parsed)) {
        setNumericValue(parsed);
        emitColor(parsed);
      }
    }, [colorRef, channelConfig, isAlpha, isHexMode, colorSpace, channel, isControlled, onValueChange]);

    const handleIncrease = useCallback((multiplier = 1) => {
      if (disabled || readOnly) return;
      const current = numericValue ?? 0;
      const next = clampValue(current + effectiveStep * multiplier);
      setNumericValue(next);
      setDisplayValue(formatValue(next));
      const newColor = emitColor(next);
      if (newColor) onValueCommit?.(newColor);
    }, [disabled, readOnly, numericValue, effectiveStep, effectiveMin, effectiveMax, colorRef, channelConfig, isAlpha, colorSpace, channel, isControlled, onValueChange, onValueCommit]);

    const handleDecrease = useCallback((multiplier = 1) => {
      if (disabled || readOnly) return;
      const current = numericValue ?? 0;
      const next = clampValue(current - effectiveStep * multiplier);
      setNumericValue(next);
      setDisplayValue(formatValue(next));
      const newColor = emitColor(next);
      if (newColor) onValueCommit?.(newColor);
    }, [disabled, readOnly, numericValue, effectiveStep, effectiveMin, effectiveMax, colorRef, channelConfig, isAlpha, colorSpace, channel, isControlled, onValueChange, onValueCommit]);

    const handleMinMaxValue = useCallback((type: "min" | "max") => {
      if (disabled || readOnly) return;
      const val = type === "min" ? effectiveMin : effectiveMax;
      setNumericValue(val);
      setDisplayValue(formatValue(val));
      const newColor = emitColor(val);
      if (newColor) onValueCommit?.(newColor);
    }, [disabled, readOnly, effectiveMin, effectiveMax, colorRef, channelConfig, isAlpha, colorSpace, channel, isControlled, onValueChange, onValueCommit]);

    const isDecreaseDisabled = numericValue !== undefined && clampValue(numericValue) <= effectiveMin;
    const isIncreaseDisabled = numericValue !== undefined && clampValue(numericValue) >= effectiveMax;

    const ctxValue = useMemo<ColorFieldContextValue>(() => ({
      modelValue: numericValue,
      displayValue,
      disabled,
      readOnly,
      isDecreaseDisabled,
      isIncreaseDisabled,
      handleIncrease,
      handleDecrease,
      handleMinMaxValue,
      commitValue,
      onInputChange,
      inputRef,
      format: effectiveFormat,
    }), [numericValue, displayValue, disabled, readOnly, isDecreaseDisabled, isIncreaseDisabled, handleIncrease, handleDecrease, handleMinMaxValue, commitValue, onInputChange, effectiveFormat]);

    return (
      <ColorFieldContext.Provider value={ctxValue}>
        <Component
          ref={ref}
          className={className}
          style={style}
          data-disabled={disabled ? "" : undefined}
          data-readonly={readOnly ? "" : undefined}
        >
          {children}
        </Component>
      </ColorFieldContext.Provider>
    );
  },
);
