// packages/vue/src/components/ColorArea/ColorAreaThumbX.vue
<script lang="ts">
import type { PrimitiveProps } from "reka-ui";
export interface ColorAreaThumbXProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
}
</script>

<script setup lang="ts">
import { computed, onMounted, onUnmounted } from "vue";
import { Primitive, useForwardExpose } from "reka-ui";
import { injectColorAreaRootContext } from "./ColorAreaRoot.vue";
import { injectColorAreaThumbContext } from "./utils";

withDefaults(defineProps<ColorAreaThumbXProps>(), {
  as: "span",
});

const rootContext = injectColorAreaRootContext();
const thumbContext = injectColorAreaThumbContext();
const { forwardRef, currentElement: thumbElement } = useForwardExpose();

const value = computed(() => rootContext.modelValue?.value?.[thumbContext.index.value]);

onMounted(() => {
  if (thumbElement.value)
    rootContext.thumbXElements.value.push(thumbElement.value);
});
onUnmounted(() => {
  const i = rootContext.thumbXElements.value.findIndex(el => el === thumbElement.value);
  if (i >= 0)
    rootContext.thumbXElements.value.splice(i, 1);
});
</script>

<template>
  <Primitive
    :ref="forwardRef"
    role="slider"
    :tabindex="rootContext.disabled.value ? undefined : (rootContext.activeDirection.value === 'x' ? 0 : -1)"
    :data-disabled="rootContext.disabled.value ? '' : undefined"
    aria-orientation="horizontal"
    :aria-valuenow="value ? value[0] : undefined"
    :aria-valuemin="rootContext.minX.value"
    :aria-valuemax="rootContext.maxX.value"
    :as-child="asChild"
    :as="as"
    :style="{
      position: 'absolute',
      display: 'block',
      width: '100%',
      height: '100%',
    }"
    @focus="() => {
      rootContext.valueIndexToChangeRef.value = thumbContext.index.value
      rootContext.activeDirection.value = 'x'
    }"
  >
    <slot />
  </Primitive>
</template>

// packages/react/src/components/ColorArea/ColorAreaThumbX.tsx
import { forwardRef, useCallback, useEffect, useRef, type ComponentPropsWithoutRef } from "react";
import { useColorAreaContext, useColorAreaThumbContext } from "./ColorAreaContext";

export interface ColorAreaThumbXProps extends ComponentPropsWithoutRef<"span"> {}

export const ColorAreaThumbX = forwardRef<HTMLSpanElement, ColorAreaThumbXProps>(
  function ColorAreaThumbX(props, ref) {
    const ctx = useColorAreaContext();
    const thumbCtx = useColorAreaThumbContext();
    const elRef = useRef<HTMLSpanElement>(null);

    useEffect(() => {
      const el = elRef.current;
      if (el) ctx.thumbXElements.current.push(el);
      return () => {
        const i = ctx.thumbXElements.current.indexOf(el!);
        if (i >= 0) ctx.thumbXElements.current.splice(i, 1);
      };
    }, [ctx]);

    const value = ctx.currentModelValue[thumbCtx.index];

    const handleFocus = useCallback(() => {
      ctx.setValueIndexToChange(thumbCtx.index);
      ctx.setActiveDirection("x");
    }, [ctx, thumbCtx.index]);

    return (
      <span
        ref={(el) => {
          (elRef as React.MutableRefObject<HTMLSpanElement | null>).current = el;
          if (typeof ref === "function") ref(el);
          else if (ref) ref.current = el;
        }}
        role="slider"
        tabIndex={ctx.disabled ? undefined : (ctx.activeDirection === "x" ? 0 : -1)}
        data-disabled={ctx.disabled ? "" : undefined}
        aria-orientation="horizontal"
        aria-valuenow={value ? value[0] : undefined}
        aria-valuemin={ctx.minX}
        aria-valuemax={ctx.maxX}
        onFocus={handleFocus}
        style={{ position: "absolute", display: "block", width: "100%", height: "100%" }}
        {...props}
      />
    );
  },
);
