// packages/vue/src/components/ColorSwatchGroup/ColorSwatchGroupItem.vue
<script lang="ts">
import type { ColorSwatchRootProps } from "../ColorSwatch/ColorSwatchRoot.vue";
import type { PrimitiveProps } from "reka-ui";

export interface ColorSwatchGroupItemProps extends PrimitiveProps, Pick<ColorSwatchRootProps, "checkerSize" | "alpha"> {
  as?: string;
  asChild?: boolean;
  /** The color value. Serves as both the selection value and the displayed color. */
  value: string;
  /** When `true`, prevents the user from interacting with this item. */
  disabled?: boolean;
}
</script>

<script setup lang="ts">
import { computed } from "vue";
import { RovingFocusItem, useForwardExpose } from "reka-ui";
import ColorSwatchRoot from "../ColorSwatch/ColorSwatchRoot.vue";
import { injectColorSwatchGroupContext } from "./ColorSwatchGroupRoot.vue";

const props = withDefaults(defineProps<ColorSwatchGroupItemProps>(), {
  as: "button",
  disabled: false,
});

const { forwardRef } = useForwardExpose();
const context = injectColorSwatchGroupContext();

const isDisabled = computed(() => props.disabled || context.disabled.value);
const isPressed = computed(() => context.modelValue.value.includes(props.value));
const dataState = computed(() => (isPressed.value ? "on" : "off"));

const role = computed(() => (context.type.value === "single" ? "radio" : "checkbox"));
const ariaChecked = computed(() => isPressed.value);

function handleClick() {
  if (isDisabled.value) return;
  context.changeModelValue(props.value);
}
</script>

<template>
  <RovingFocusItem
    v-if="context.rovingFocus.value"
    as-child
    :focusable="!isDisabled"
  >
    <ColorSwatchRoot
      :ref="forwardRef"
      :as="as"
      :as-child="asChild"
      :model-value="value"
      :checker-size="checkerSize"
      :alpha="alpha"
      :role="role"
      :aria-checked="ariaChecked"
      :aria-pressed="isPressed"
      :aria-disabled="isDisabled || undefined"
      :data-state="dataState"
      :data-disabled="isDisabled ? '' : undefined"
      :tabindex="isDisabled ? -1 : undefined"
      @click="handleClick"
      @keydown.enter.prevent="handleClick"
      @keydown.space.prevent="handleClick"
    >
      <slot />
    </ColorSwatchRoot>
  </RovingFocusItem>

  <ColorSwatchRoot
    v-else
    :ref="forwardRef"
    :as="as"
    :as-child="asChild"
    :model-value="value"
    :checker-size="checkerSize"
    :alpha="alpha"
    :role="role"
    :aria-checked="ariaChecked"
    :aria-pressed="isPressed"
    :aria-disabled="isDisabled || undefined"
    :data-state="dataState"
    :data-disabled="isDisabled ? '' : undefined"
    @click="handleClick"
    @keydown.enter.prevent="handleClick"
    @keydown.space.prevent="handleClick"
  >
    <slot />
  </ColorSwatchRoot>
</template>

// packages/react/src/components/ColorSwatchGroup/ColorSwatchGroupItem.tsx
import { forwardRef, useCallback, useMemo, type ComponentPropsWithoutRef } from "react";
import { ColorSwatchRoot, type ColorSwatchRootProps } from "../ColorSwatch/ColorSwatchRoot";
import { useColorSwatchGroupContext } from "./ColorSwatchGroupContext";

export interface ColorSwatchGroupItemProps extends Omit<ComponentPropsWithoutRef<"div">, "value"> {
  /** The color value. Serves as both the selection value and the displayed color. */
  value: string;
  /** When true, prevents interaction with this item. */
  disabled?: boolean;
  /** Checkerboard size passed to the inner swatch. */
  checkerSize?: number;
  /** Whether to show alpha channel. */
  alpha?: boolean;
}

export const ColorSwatchGroupItem = forwardRef<HTMLButtonElement, ColorSwatchGroupItemProps>(
  function ColorSwatchGroupItem({ value, disabled: disabledProp = false, checkerSize, alpha, ...props }, ref) {
    const ctx = useColorSwatchGroupContext();
    const isDisabled = disabledProp || ctx.disabled;
    const isPressed = ctx.modelValue.includes(value);
    const dataState = isPressed ? "on" : "off";
    const role = ctx.type === "single" ? "radio" : "checkbox";

    const handleClick = useCallback(() => {
      if (isDisabled) return;
      ctx.changeModelValue(value);
    }, [isDisabled, ctx, value]);

    const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        handleClick();
      }
    }, [handleClick]);

    return (
      <ColorSwatchRoot
        ref={ref as any}
        as="button"
        value={value}
        checkerSize={checkerSize}
        alpha={alpha}
        role={role}
        aria-checked={isPressed}
        aria-pressed={isPressed}
        aria-disabled={isDisabled || undefined}
        data-state={dataState}
        data-disabled={isDisabled ? "" : undefined}
        onClick={handleClick as any}
        onKeyDown={handleKeyDown as any}
        {...props}
      />
    );
  },
);
