// packages/react/src/components/color-ring/gradient/ColorRingGradient.tsx
import { forwardRef, useCallback, useEffect, useRef, type ComponentPropsWithoutRef } from "react";
import { Color, type SpaceId } from "@urcolor/core";
import { channelStops, cssConicStops, getChannelConfig, renderToCanvas, sampleConicRing, type GradientRenderer } from "@urcolor/shared";
import { useColorRingContext } from "../root/ColorRingRootContext";
import { CHECKERBOARD_STYLE } from "../../../utils";
import { CssGradientLayers, resolveCssGradient } from "../../../cssGradient";

export interface ColorRingGradientProps extends ComponentPropsWithoutRef<"span"> {
  /**
   * Which painter to use.
   * - `"auto"` (default) - CSS when an exact recipe exists, canvas otherwise
   * - `"css"` - force CSS; falls back to the canvas with a dev warning if none exists
   * - `"canvas"` - force the canvas painter
   */
  renderer?: GradientRenderer;
  channelOverrides?: Record<string, number> | false;
}

export const ColorRingGradient = forwardRef<HTMLSpanElement, ColorRingGradientProps>(
  function ColorRingGradient({ renderer = "auto", channelOverrides = { alpha: 1 }, style, children, ...props }, ref) {
    const rootCtx = useColorRingContext();
    const canvasRef = useRef<HTMLCanvasElement | null>(null);

    // The annulus is cut here and nowhere else: the canvas paints the full
    // square and this mask — which applies to the element and every descendant,
    // canvas included — hides the hole and the corners. Clipping the canvas as
    // well used to leave a seam, because the two edges are rasterised
    // independently and their partial coverage multiplies along the boundary.
    //
    // The ±0.5px on the stops is what antialiases the edges: a gradient hard
    // stop (two stops at one position) rasterises without any, so both circles
    // came out visibly stepped.
    const maskP = rootCtx.innerRadius * 100;
    const checkerboardMask = `radial-gradient(circle closest-side at center, transparent calc(${maskP}% - 0.5px), #000 calc(${maskP}% + 0.5px), #000 calc(100% - 0.5px), transparent 100%)`;

    function applyOverrides(baseColor: Color, cs: SpaceId): Color {
      if (!channelOverrides) return baseColor;
      let result = baseColor;
      const updates: Record<string, number> = {};
      for (const [k, v] of Object.entries(channelOverrides)) {
        if (k === "alpha") result = result.withAlpha(v);
        else if (getChannelConfig(cs, k)) updates[k] = v;
      }
      if (Object.keys(updates).length > 0) result = result.with({ space: cs, ...updates });
      return result;
    }

    // `sampleConicRing` writes an opaque alpha byte for every pixel, so the CSS
    // stops drop the base color's alpha to match rather than tinting the ring.
    const cssLayers = resolveCssGradient(renderer, "ColorRingGradient", () => {
      const baseColor = rootCtx.colorRef;
      if (!baseColor) return null;
      const overridden = applyOverrides(baseColor, rootCtx.colorSpace).withAlpha(1);
      const stops = channelStops(overridden, rootCtx.colorSpace, rootCtx.channelKey);
      return stops && cssConicStops(stops, rootCtx.startAngle);
    });

    const render = useCallback(() => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      const baseColor = rootCtx.colorRef;
      if (!baseColor) return;
      const overriddenBase = applyOverrides(baseColor, rootCtx.colorSpace);
      const cfg = getChannelConfig(rootCtx.colorSpace, rootCtx.channelKey);
      if (!cfg) return;
      const cMin = cfg.nativeMin ?? cfg.min;
      const cMax = cfg.nativeMax ?? cfg.max;
      const sampleSize = 128;
      const pixels = sampleConicRing(overriddenBase, rootCtx.colorSpace, rootCtx.channelKey, cMin, cMax, sampleSize, sampleSize, rootCtx.startAngle);
      renderToCanvas({ canvas, pixels, sampleWidth: sampleSize, sampleHeight: sampleSize });
      // `innerRadius` is not a dependency: it only moves the mask, and the
      // pixels the canvas paints are the same at every radius.
    }, [rootCtx.colorRef, rootCtx.colorSpace, rootCtx.channelKey, rootCtx.startAngle, rootCtx.isDragging, channelOverrides]);

    useEffect(() => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      if (!rootCtx.isDragging) render();
      const observer = new ResizeObserver(() => render());
      observer.observe(canvas);
      return () => observer.disconnect();
    }, [render, rootCtx.isDragging]);

    useEffect(() => {
      if (!rootCtx.isDragging) render();
    }, [rootCtx.isDragging]);

    useEffect(() => {
      return () => {
        const canvas = canvasRef.current;
        if (canvas) {
          const gl = canvas.getContext("webgl");
          if (gl) gl.getExtension("WEBGL_lose_context")?.loseContext();
        }
      };
    }, []);

    return (
      <span ref={ref} data-disabled={rootCtx.disabled ? "" : undefined} style={{ ...CHECKERBOARD_STYLE, maskImage: checkerboardMask, WebkitMaskImage: checkerboardMask, ...style }} {...props}>
        {cssLayers
          ? <CssGradientLayers layers={cssLayers} />
          : (
              <canvas
                ref={canvasRef}
                style={{ position: "absolute", inset: "0", width: "100%", height: "100%", pointerEvents: "none" }}
              />
            )}
        {children}
      </span>
    );
  },
);

// packages/vue/src/components/ColorRing/ColorRingGradient.vue
<script lang="ts">
import type { PrimitiveProps } from "../../primitives/types";
import type { GradientRenderer } from "@urcolor/shared";

export interface ColorRingGradientProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
  /**
   * Which painter to use.
   * - `"auto"` (default) — CSS when an exact recipe exists, canvas otherwise
   * - `"css"` — force CSS; falls back to the canvas with a dev warning if none exists
   * - `"canvas"` — force the canvas painter
   */
  renderer?: GradientRenderer;
  channelOverrides?: Record<string, number> | false;
  /** @deprecated Use innerRadius on ColorRingRoot instead */
  innerRadius?: number;
}
</script>

<script setup lang="ts">
import { ref, computed } from "vue";
import { useForwardExpose, Primitive } from "reka-ui";
import { channelStops, cssConicStops, getChannelConfig, sampleConicRing } from "@urcolor/shared";
import { applyChannelOverrides, renderToCanvas, useGradientCanvas } from "../../shared/useGradientCanvas";
import { CSS_GRADIENT_ROOT_STYLE, cssLayerStyle, useCssGradient } from "../../shared/useCssGradient";
import { CHECKERBOARD_STYLE } from "../../shared/checkerboard";
import { injectColorRingRootContext } from "./ColorRingRoot.vue";

const props = withDefaults(defineProps<ColorRingGradientProps>(), {
  as: "span",
  renderer: "auto",
  channelOverrides: () => ({ alpha: 1 }),
});

const rootContext = injectColorRingRootContext();
useForwardExpose();

const canvasRef = ref<HTMLCanvasElement | null>(null);

// The annulus is cut here and nowhere else: the canvas paints the full square
// and this mask — which applies to the element and every descendant, canvas
// included — hides the hole and the corners. Clipping the canvas as well used
// to leave a seam, because the two edges are rasterised independently and their
// partial coverage multiplies along the boundary.
//
// The ±0.5px on the stops is what antialiases the edges: a gradient hard stop
// (two stops at one position) rasterises without any, so both circles came out
// visibly stepped.
const checkerboardMask = computed(() => {
  const p = (props.innerRadius ?? rootContext.innerRadius.value) * 100;
  return `radial-gradient(circle closest-side at center, transparent calc(${p}% - 0.5px), #000 calc(${p}% + 0.5px), #000 calc(100% - 0.5px), transparent 100%)`;
});

// `sampleConicRing` writes an opaque alpha byte for every pixel, so the CSS
// stops drop the base color's alpha to match rather than tinting the ring.
const cssLayers = useCssGradient({
  renderer: () => props.renderer,
  name: "ColorRingGradient",
  build: () => {
    const colorSpace = rootContext.colorSpace.value;
    const baseColor = rootContext.colorRef.value;
    if (!baseColor) return null;

    const overriddenBase = applyChannelOverrides(baseColor, colorSpace, props.channelOverrides);
    const stops = channelStops(overriddenBase.withAlpha(1), colorSpace, rootContext.channelKey.value);
    if (!stops) return null;
    return cssConicStops(stops, rootContext.startAngle.value);
  },
});

function paint(canvas: HTMLCanvasElement) {
  const colorSpace = rootContext.colorSpace.value;
  const channel = rootContext.channelKey.value;
  const baseColor = rootContext.colorRef.value;
  if (!baseColor) return;

  const overriddenBase = applyChannelOverrides(baseColor, colorSpace, props.channelOverrides);
  const cfg = getChannelConfig(colorSpace, channel);
  if (!cfg) return;

  const cMin = cfg.nativeMin ?? cfg.min;
  const cMax = cfg.nativeMax ?? cfg.max;

  const sampleSize = 128;
  const pixels = sampleConicRing(
    overriddenBase, colorSpace, channel, cMin, cMax,
    sampleSize, sampleSize,
    rootContext.startAngle.value,
  );
  renderToCanvas({ canvas, pixels, sampleWidth: sampleSize, sampleHeight: sampleSize });
}

useGradientCanvas({
  canvas: canvasRef,
  // `innerRadius` is not a source: it only moves the mask, and the pixels the
  // canvas paints are the same at every radius.
  sources: () => [
    props.channelOverrides,
    rootContext.colorSpace.value, rootContext.channelKey.value,
    rootContext.colorRef.value, rootContext.startAngle.value,
  ],
  paint,
  isDragging: rootContext.isDragging,
});
</script>

<template>
  <Primitive
    :as-child="asChild"
    :as="as"
    :style="{ ...CHECKERBOARD_STYLE, maskImage: checkerboardMask, WebkitMaskImage: checkerboardMask }"
    :data-disabled="rootContext.disabled.value ? '' : undefined"
  >
    <span
      v-if="cssLayers"
      :style="CSS_GRADIENT_ROOT_STYLE"
    >
      <span
        v-for="(layer, i) in cssLayers"
        :key="i"
        :style="cssLayerStyle(layer)"
      />
    </span>
    <canvas
      v-else
      ref="canvasRef"
      :style="{ position: 'absolute', inset: '0', width: '100%', height: '100%', pointerEvents: 'none' }"
    />
    <slot />
  </Primitive>
</template>
