// packages/vue/src/components/ColorArea/ColorAreaRoot.vue
<script lang="ts">
import type { Ref } from "vue";
import type { PrimitiveProps } from "reka-ui";
import { createContext, useDirection, useForwardExpose, VisuallyHidden } from "reka-ui";
import { computed, ref, shallowRef, toRefs, watch } from "vue";
import { Color } from "internationalized-color";
import { colorSpaces, getChannelConfig, displayToCulori, culoriToDisplay, type ChannelConfig } from "@urcolor/core";
import { useCollection, useFormControl, ARROW_KEYS, PAGE_KEYS, getClosestThumbIndex, hasMinStepsBetweenValues, linearScale, snapToStep, type ActiveDirection } from "./utils";

type Direction = "ltr" | "rtl";
type ThumbAlignment = "contain" | "overflow";

export interface ColorAreaRootProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
  /** The name of the hidden input field for form submission. */
  name?: string | undefined;
  /** Whether the field is required for form submission. */
  required?: boolean;
  /** The controlled color value. Can be bind as `v-model`. */
  modelValue?: Color | string | null;
  /** The default color value when uncontrolled. */
  defaultValue?: Color | string;
  /** When `true`, prevents the user from interacting with the slider area. */
  disabled?: boolean;
  /** The reading direction. If omitted, inherits globally from `ConfigProvider` or assumes LTR. */
  dir?: Direction;
  /** Whether the X axis is visually inverted. */
  invertedX?: boolean;
  /** Whether the Y axis is visually inverted. */
  invertedY?: boolean;
  /** The color space mode to work in (e.g. 'hsl', 'oklch'). */
  colorSpace?: string;
  /** Which channel maps to the X axis (e.g. 's' for HSL saturation, or 'alpha' for opacity). */
  channelX?: string;
  /** Which channel maps to the Y axis (e.g. 'l' for HSL lightness, or 'alpha' for opacity). */
  channelY?: string;
  /** The minimum permitted steps between multiple thumbs on the X axis. */
  minXStepsBetweenThumbs?: number;
  /** The minimum permitted steps between multiple thumbs on the Y axis. */
  minYStepsBetweenThumbs?: number;
  /**
   * The alignment of the slider area thumb.
   * - `contain`: thumbs will be contained within the bounds of the track.
   * - `overflow`: thumbs will not be bound by the track. No extra offset will be added.
   * @defaultValue 'overflow'
   */
  thumbAlignment?: ThumbAlignment;
}

export type ColorAreaRootEmits = {
  /** Event handler called when the color value changes */
  "update:modelValue": [payload: Color | undefined];
  /** Event handler called when the value changes at the end of an interaction. */
  "valueCommit": [payload: Color];
};

export interface ColorAreaRootContext {
  disabled: Ref<boolean>;
  minX: Ref<number>;
  maxX: Ref<number>;
  minY: Ref<number>;
  maxY: Ref<number>;
  modelValue?: Readonly<Ref<number[][] | null | undefined>>;
  currentModelValue: Ref<number[][]>;
  valueIndexToChangeRef: Ref<number>;
  thumbRef: Ref<HTMLElement | undefined>;
  isSlidingFromLeft: Ref<boolean>;
  isSlidingFromTop: Ref<boolean>;
  thumbAlignment: Ref<ThumbAlignment>;
  colorSpace: Ref<string>;
  xChannelKey: Ref<string>;
  yChannelKey: Ref<string>;
  colorRef: Readonly<Ref<Color | undefined>>;
  dir: Ref<Direction>;
  isDragging: Ref<boolean>;
}

export const [injectColorAreaRootContext, provideColorAreaRootContext]
  = createContext<ColorAreaRootContext>("ColorAreaRoot");
</script>

<script setup lang="ts">
import { Primitive } from "reka-ui";
defineOptions({
  inheritAttrs: false,
});

const props = withDefaults(defineProps<ColorAreaRootProps>(), {
  disabled: false,
  defaultValue: "hsl(0, 100%, 50%)",
  invertedX: false,
  invertedY: false,
  colorSpace: "hsl",
  minXStepsBetweenThumbs: 0,
  minYStepsBetweenThumbs: 0,
  thumbAlignment: "overflow",
  as: "span",
});
const emits = defineEmits<ColorAreaRootEmits>();

defineSlots<{
  default?: (props: {
    /** Current color value */
    modelValue: Color | undefined;
  }) => any;
}>();

const { disabled, thumbAlignment, dir: propDir } = toRefs(props);
const dir = useDirection(propDir); // eslint-disable-line vue/no-dupe-keys
const { forwardRef, currentElement } = useForwardExpose();
const isFormControl = useFormControl(currentElement);
const { CollectionSlot } = useCollection({ isProvider: true });

// Alpha channel config (display 0-100, culori 0-1)
const ALPHA_CONFIG: ChannelConfig = {
  key: "alpha",
  label: "Alpha",
  min: 0,
  max: 100,
  step: 1,
  format: "percentage",
  culoriMin: 0,
  culoriMax: 1,
};

// Resolve default xChannel/yChannel from colorSpace
const spaceConfig = computed(() => colorSpaces[props.colorSpace]);
const xChannelKey = computed(() => props.channelX ?? spaceConfig.value?.channels[0]?.key ?? "h");
const yChannelKey = computed(() => props.channelY ?? spaceConfig.value?.channels[1]?.key ?? "s");
const xIsAlpha = computed(() => xChannelKey.value === "alpha");
const yIsAlpha = computed(() => yChannelKey.value === "alpha");
const xConfig = computed(() => xIsAlpha.value ? ALPHA_CONFIG : getChannelConfig(props.colorSpace, xChannelKey.value));
const yConfig = computed(() => yIsAlpha.value ? ALPHA_CONFIG : getChannelConfig(props.colorSpace, yChannelKey.value));

const minX = computed(() => xConfig.value?.min ?? 0);
const maxX = computed(() => xConfig.value?.max ?? 100);
const minY = computed(() => yConfig.value?.min ?? 0);
const maxY = computed(() => yConfig.value?.max ?? 100);
const stepX = computed(() => xConfig.value?.step ?? 1);
const stepY = computed(() => yConfig.value?.step ?? 1);

// Parse incoming modelValue to Color
function parseColor(v: Color | string | null | undefined): Color | undefined {
  if (!v) return undefined;
  if (v instanceof Color) return v;
  return Color.parse(v) ?? undefined;
}

// Internal Color ref
const colorRef = shallowRef<Color | undefined>(parseColor(props.modelValue ?? props.defaultValue));

// Sync from external modelValue changes
watch(() => props.modelValue, (val) => {
  const parsed = parseColor(val);
  if (parsed) colorRef.value = parsed;
});

// Convert Color to display values for the internal slider
function colorToDisplayValues(color: Color | undefined): number[][] {
  if (!color || !xConfig.value || !yConfig.value) return [[minX.value, minY.value]];
  const converted = color.to(props.colorSpace);
  if (!converted) return [[minX.value, minY.value]];
  const rawX = xIsAlpha.value ? (color.alpha ?? 1) : converted.get(xChannelKey.value, 0);
  const rawY = yIsAlpha.value ? (color.alpha ?? 1) : converted.get(yChannelKey.value, 0);
  return [[culoriToDisplay(xConfig.value, rawX), culoriToDisplay(yConfig.value, rawY)]];
}

// Internal numeric model for the slider mechanics
const internalValue = ref<number[][]>(colorToDisplayValues(colorRef.value));

// Sync Color → internal numeric values (also when channels change)
watch([colorRef, xChannelKey, yChannelKey], ([color]) => {
  const newVals = colorToDisplayValues(color);
  // Only update if significantly different to avoid feedback loops
  const cur = internalValue.value[0];
  if (cur && Math.abs((cur[0] ?? 0) - (newVals[0]?.[0] ?? 0)) < 0.001 && Math.abs((cur[1] ?? 0) - (newVals[0]?.[1] ?? 0)) < 0.001) return;
  internalValue.value = newVals;
});

// Rebuild Color from numeric display values
function displayValuesToColor(vals: number[][]): Color | undefined {
  if (!vals[0] || !colorRef.value || !xConfig.value || !yConfig.value) return undefined;
  const culoriX = displayToCulori(xConfig.value, vals[0][0] ?? 0);
  const culoriY = displayToCulori(yConfig.value, vals[0][1] ?? 0);
  const channelUpdates: Record<string, number> = {};
  if (!xIsAlpha.value) channelUpdates[xChannelKey.value] = culoriX;
  if (!yIsAlpha.value) channelUpdates[yChannelKey.value] = culoriY;
  let result = colorRef.value.set({ mode: props.colorSpace, ...channelUpdates });
  if (xIsAlpha.value) result = result.set({ alpha: culoriX });
  if (yIsAlpha.value) result = result.set({ alpha: culoriY });
  return result;
}

const currentModelValue = computed(() => Array.isArray(internalValue.value) ? [...internalValue.value] : []);

const valueIndexToChangeRef = ref(0);
const valuesBeforeSlideStartRef = ref(currentModelValue.value);
const rectRef = ref<DOMRect>();
const offsetPosition = ref<{ x: number; y: number }>();

// Determine axis directions
const isSlidingFromLeft = computed(() => {
  return (dir.value !== "rtl" && !props.invertedX) || (dir.value !== "ltr" && props.invertedX);
});
const isSlidingFromTop = computed(() => !props.invertedY);

function getPointFromPointerEvent(event: PointerEvent, slideStart?: boolean): number[] {
  const rect = rectRef.value || currentElement.value.getBoundingClientRect();
  rectRef.value = rect;

  const thumb = thumbRef.value;
  const thumbWidth = thumbAlignment.value === "contain" && thumb ? thumb.clientWidth : 0;
  const thumbHeight = thumbAlignment.value === "contain" && thumb ? thumb.clientHeight : 0;

  if (!offsetPosition.value && !slideStart && thumbAlignment.value === "contain" && thumb) {
    const thumbRect = thumb.getBoundingClientRect();
    offsetPosition.value = {
      x: event.clientX - thumbRect.left,
      y: event.clientY - thumbRect.top,
    };
  }

  const inputX: [number, number] = [0, rect.width - thumbWidth];
  const outputX: [number, number] = isSlidingFromLeft.value ? [minX.value, maxX.value] : [maxX.value, minX.value];
  const scaleX = linearScale(inputX, outputX);

  const inputY: [number, number] = [0, rect.height - thumbHeight];
  const outputY: [number, number] = isSlidingFromTop.value ? [minY.value, maxY.value] : [maxY.value, minY.value];
  const scaleY = linearScale(inputY, outputY);

  const posX = slideStart
    ? event.clientX - rect.left - thumbWidth / 2
    : event.clientX - rect.left - (offsetPosition.value?.x ?? 0);
  const posY = slideStart
    ? event.clientY - rect.top - thumbHeight / 2
    : event.clientY - rect.top - (offsetPosition.value?.y ?? 0);

  return [scaleX(posX), scaleY(posY)];
}

const lastPointerPosition = ref<{ x: number; y: number }>();

function handleSlideStart(event: PointerEvent) {
  const point = getPointFromPointerEvent(event, true);
  const closestIndex = getClosestThumbIndex(currentModelValue.value, point, minX.value, maxX.value, minY.value, maxY.value);
  if (closestIndex === -1)
    return;
  isDragging.value = true;
  lastPointerPosition.value = { x: event.clientX, y: event.clientY };
  updateValues(point, closestIndex, { skipFocus: true });
}

function handleSlideMove(event: PointerEvent) {
  const point = getPointFromPointerEvent(event);
  lastPointerPosition.value = { x: event.clientX, y: event.clientY };
  updateValues(point, valueIndexToChangeRef.value);
}

function handleSlideEnd() {
  isDragging.value = false;
  rectRef.value = undefined;
  offsetPosition.value = undefined;
  lastPointerPosition.value = undefined;
  const prevValue = valuesBeforeSlideStartRef.value[valueIndexToChangeRef.value];
  const nextValue = currentModelValue.value[valueIndexToChangeRef.value];
  const hasChanged = prevValue?.[0] !== nextValue?.[0] || prevValue?.[1] !== nextValue?.[1];
  if (hasChanged && colorRef.value)
    emits("valueCommit", colorRef.value);
}

const minXStepsBetweenThumbs = computed(() => props.minXStepsBetweenThumbs);
const minYStepsBetweenThumbs = computed(() => props.minYStepsBetweenThumbs);

function clampAxis(nextValue: number, axisIndex: number, atIndex: number, minGap: number): number {
  if (minGap <= 0)
    return nextValue;
  const testValues = currentModelValue.value.map((v, i) => i === atIndex ? nextValue : (v[axisIndex] ?? 0));
  if (!hasMinStepsBetweenValues([...testValues].sort((a, b) => a - b), minGap))
    return currentModelValue.value[atIndex]?.[axisIndex] ?? nextValue;
  return nextValue;
}

function updateValues(point: number[], atIndex: number, { commit = false, skipFocus = false } = {}) {
  const nextX = snapToStep(point[0] ?? 0, minX.value, maxX.value, stepX.value);
  const nextY = snapToStep(point[1] ?? 0, minY.value, maxY.value, stepY.value);

  const finalX = clampAxis(nextX, 0, atIndex, minXStepsBetweenThumbs.value * stepX.value);
  const finalY = clampAxis(nextY, 1, atIndex, minYStepsBetweenThumbs.value * stepY.value);

  const nextValues = [...currentModelValue.value];
  nextValues[atIndex] = [finalX, finalY];

  valueIndexToChangeRef.value = atIndex;

  const hasChanged = JSON.stringify(nextValues) !== JSON.stringify(internalValue.value);

  if (hasChanged) {
    if (!skipFocus) {
      thumbRef.value?.focus();
    }
    internalValue.value = nextValues;

    // Rebuild and emit Color
    const newColor = displayValuesToColor(nextValues);
    if (newColor) {
      colorRef.value = newColor;
      emits("update:modelValue", newColor);
      if (commit) emits("valueCommit", newColor);
    }
  }
}

const STEP_KEY_DELTAS: Record<string, { axis: ActiveDirection; sign: number }> = {
  ArrowRight: { axis: "x", sign: 1 },
  ArrowLeft: { axis: "x", sign: -1 },
  ArrowDown: { axis: "y", sign: 1 },
  ArrowUp: { axis: "y", sign: -1 },
};

function handleStepKeyDown(event: KeyboardEvent) {
  const delta = STEP_KEY_DELTAS[event.key];
  if (!delta)
    return;

  const atIndex = valueIndexToChangeRef.value;
  const value = currentModelValue.value[atIndex];
  if (!value)
    return;

  const multiplier = (event.shiftKey && ARROW_KEYS.includes(event.key)) ? 10 : 1;

  const dirMultiplier = delta.axis === "x"
    ? (isSlidingFromLeft.value ? 1 : -1)
    : (isSlidingFromTop.value ? 1 : -1);
  const step = delta.axis === "x" ? stepX.value : stepY.value;
  const offset = step * multiplier * delta.sign * dirMultiplier;

  const vx = value[0] ?? 0;
  const vy = value[1] ?? 0;
  const point: number[] = delta.axis === "x"
    ? [vx + offset, vy]
    : [vx, vy + offset];

  updateValues(point, atIndex, { commit: true });
}

function handleBoundaryKey(axis: ActiveDirection, boundaryValue: number) {
  const atIndex = valueIndexToChangeRef.value;
  const value = currentModelValue.value[atIndex];
  if (!value)
    return;

  let effectiveValue = boundaryValue;
  if (axis === "x" && !isSlidingFromLeft.value) {
    effectiveValue = boundaryValue === minX.value ? maxX.value : minX.value;
  } else if (axis === "y" && !isSlidingFromTop.value) {
    effectiveValue = boundaryValue === minY.value ? maxY.value : minY.value;
  }

  const point = axis === "x"
    ? [effectiveValue, value[1] ?? 0]
    : [value[0] ?? 0, effectiveValue];
  updateValues(point, atIndex, { commit: true });
}

const thumbRef = ref<HTMLElement | undefined>();
const isDragging = ref(false);

provideColorAreaRootContext({
  modelValue: internalValue,
  currentModelValue,
  valueIndexToChangeRef,
  thumbRef,
  minX,
  maxX,
  minY,
  maxY,
  disabled,
  isSlidingFromLeft,
  isSlidingFromTop,
  thumbAlignment,
  colorSpace: computed(() => props.colorSpace),
  xChannelKey,
  yChannelKey,
  colorRef,
  dir,
  isDragging,
});
</script>

<template>
  <CollectionSlot>
    <Primitive
      v-bind="$attrs"
      :ref="forwardRef"
      :as-child="asChild"
      :as="as"
      :dir="dir"
      :aria-disabled="disabled"
      :data-disabled="disabled ? '' : undefined"
      :style="{
        ['--reka-slider-area-thumb-transform' as any]: `translate(${!isSlidingFromLeft && thumbAlignment === 'overflow' ? '50%' : '-50%'}, ${!isSlidingFromTop && thumbAlignment === 'overflow' ? '50%' : '-50%'})`,
      }"
      @keydown="(event: KeyboardEvent) => {
        if (disabled) return;
        if (event.key === 'Home') { handleBoundaryKey('x', minX); event.preventDefault(); }
        else if (event.key === 'End') { handleBoundaryKey('x', maxX); event.preventDefault(); }
        else if (event.key === 'PageUp') { handleBoundaryKey('y', minY); event.preventDefault(); }
        else if (event.key === 'PageDown') { handleBoundaryKey('y', maxY); event.preventDefault(); }
        else if (PAGE_KEYS.concat(ARROW_KEYS).includes(event.key)) { handleStepKeyDown(event); event.preventDefault(); }
      }"
      @pointerdown="(event: PointerEvent) => {
        if (disabled) return;
        const target = event.target as HTMLElement;
        target.setPointerCapture(event.pointerId);
        event.preventDefault();
        if (thumbRef && thumbRef.contains(target)) {
          thumbRef.focus();
        }
        else {
          valuesBeforeSlideStartRef = currentModelValue;
          handleSlideStart(event);
        }
      }"
      @pointermove="(event: PointerEvent) => {
        if (disabled) return;
        const target = event.target as HTMLElement;
        if (target.hasPointerCapture(event.pointerId)) handleSlideMove(event);
      }"
      @pointerup="(event: PointerEvent) => {
        if (disabled) return;
        const target = event.target as HTMLElement;
        if (target.hasPointerCapture(event.pointerId)) {
          target.releasePointerCapture(event.pointerId);
          handleSlideEnd();
        }
      }"
    >
      <slot :model-value="colorRef" />

      <VisuallyHidden
        v-if="isFormControl && name"
        as="input"
        type="hidden"
        :value="colorRef?.toString() ?? ''"
        :name="name"
        :required="required"
        :disabled="disabled"
      />
    </Primitive>
  </CollectionSlot>
</template>

// packages/react/src/components/color-area/root/ColorAreaRoot.tsx
import { forwardRef, useCallback, useMemo, useRef, useState } from "react";
import { Color } from "internationalized-color";
import { colorSpaces, getChannelConfig, displayToCulori, culoriToDisplay, type ChannelConfig } from "@urcolor/core";
import { snapToStep, linearScale, getClosestThumbIndex, hasMinStepsBetweenValues, ARROW_KEYS } from "../../../utils";
import { ColorAreaContext, type ColorAreaContextValue } from "./ColorAreaRootContext";

export interface ColorAreaRootProps {
  /** The controlled color value. */
  value?: Color | string | null;
  /** The default color value when uncontrolled. */
  defaultValue?: Color | string;
  /** When true, prevents interaction. */
  disabled?: boolean;
  /** The reading direction. */
  dir?: "ltr" | "rtl";
  /** Whether the X axis is visually inverted. */
  invertedX?: boolean;
  /** Whether the Y axis is visually inverted. */
  invertedY?: boolean;
  /** The color space mode. */
  colorSpace?: string;
  /** Which channel maps to the X axis. */
  channelX?: string;
  /** Which channel maps to the Y axis. */
  channelY?: string;
  /** Thumb alignment. */
  thumbAlignment?: "contain" | "overflow";
  /** Callback fired when the color value changes. */
  onValueChange?: (color: Color) => void;
  /** Callback fired when the value changes at the end of an interaction. */
  onValueCommit?: (color: Color) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

function parseColor(v: Color | string | null | undefined): Color | undefined {
  if (!v) return undefined;
  if (v instanceof Color) return v;
  return Color.parse(v) ?? undefined;
}

const ALPHA_CONFIG: ChannelConfig = { key: "alpha", label: "Alpha", min: 0, max: 100, step: 1, format: "percentage", culoriMin: 0, culoriMax: 1 };

export const ColorAreaRoot = forwardRef<HTMLDivElement, ColorAreaRootProps>(
  function ColorAreaRoot(props, ref) {
    const {
      value: valueProp,
      defaultValue: defaultValueProp = "hsl(0, 100%, 50%)",
      disabled = false,
      dir = "ltr",
      invertedX = false,
      invertedY = false,
      colorSpace = "hsl",
      channelX: channelXProp,
      channelY: channelYProp,
      thumbAlignment = "overflow",
      onValueChange,
      onValueCommit,
      children,
      className,
      style,
    } = props;

    const isControlled = valueProp !== undefined;
    const [internalColor, setInternalColor] = useState<Color | undefined>(
      () => parseColor(valueProp) ?? parseColor(defaultValueProp),
    );

    const prevValueRef = useRef(valueProp);
    if (valueProp !== prevValueRef.current) {
      prevValueRef.current = valueProp;
      const parsed = parseColor(valueProp);
      if (parsed) setInternalColor(parsed);
    }

    const colorRef = isControlled ? (parseColor(valueProp) ?? internalColor) : internalColor;

    const spaceConfig = colorSpaces[colorSpace];
    const xChannelKey = channelXProp ?? spaceConfig?.channels[0]?.key ?? "h";
    const yChannelKey = channelYProp ?? spaceConfig?.channels[1]?.key ?? "s";
    const xIsAlpha = xChannelKey === "alpha";
    const yIsAlpha = yChannelKey === "alpha";
    const xConfig = xIsAlpha ? ALPHA_CONFIG : getChannelConfig(colorSpace, xChannelKey);
    const yConfig = yIsAlpha ? ALPHA_CONFIG : getChannelConfig(colorSpace, yChannelKey);

    const minX = xConfig?.min ?? 0;
    const maxX = xConfig?.max ?? 100;
    const minY = yConfig?.min ?? 0;
    const maxY = yConfig?.max ?? 100;
    const stepX = xConfig?.step ?? 1;
    const stepY = yConfig?.step ?? 1;

    function colorToDisplayValues(color: Color | undefined): number[][] {
      if (!color || !xConfig || !yConfig) return [[minX, minY]];
      const converted = color.to(colorSpace);
      if (!converted) return [[minX, minY]];
      const rawX = xIsAlpha ? (color.alpha ?? 1) : converted.get(xChannelKey, 0);
      const rawY = yIsAlpha ? (color.alpha ?? 1) : converted.get(yChannelKey, 0);
      return [[culoriToDisplay(xConfig, rawX), culoriToDisplay(yConfig, rawY)]];
    }

    const [internalValue, setInternalValue] = useState<number[][]>(() => colorToDisplayValues(colorRef));
    const [valueIndexToChange, setValueIndexToChange] = useState(0);
    const [isDragging, setIsDragging] = useState(false);

    const thumbRef = useRef<HTMLElement | null>(null);
    const elementRef = useRef<HTMLDivElement>(null);
    const rectRef = useRef<DOMRect | undefined>(undefined);
    const offsetPosition = useRef<{ x: number; y: number } | undefined>(undefined);
    const lastPointerPosition = useRef<{ x: number; y: number } | undefined>(undefined);
    const valuesBeforeSlideStart = useRef<number[][]>(internalValue);

    // Sync color -> internal value
    const prevColorRef = useRef(colorRef);
    if (colorRef !== prevColorRef.current) {
      prevColorRef.current = colorRef;
      const newVals = colorToDisplayValues(colorRef);
      const cur = internalValue[0];
      if (!cur || Math.abs((cur[0] ?? 0) - (newVals[0]?.[0] ?? 0)) >= 0.001 || Math.abs((cur[1] ?? 0) - (newVals[0]?.[1] ?? 0)) >= 0.001) {
        setInternalValue(newVals);
      }
    }

    const isSlidingFromLeft = (dir !== "rtl" && !invertedX) || (dir !== "ltr" && invertedX);
    const isSlidingFromTop = !invertedY;

    function displayValuesToColor(vals: number[][]): Color | undefined {
      if (!vals[0] || !colorRef || !xConfig || !yConfig) return undefined;
      const culoriX = displayToCulori(xConfig, vals[0][0] ?? 0);
      const culoriY = displayToCulori(yConfig, vals[0][1] ?? 0);
      const channelUpdates: Record<string, number> = {};
      if (!xIsAlpha) channelUpdates[xChannelKey] = culoriX;
      if (!yIsAlpha) channelUpdates[yChannelKey] = culoriY;
      let result = colorRef.set({ mode: colorSpace, ...channelUpdates });
      if (xIsAlpha) result = result.set({ alpha: culoriX });
      if (yIsAlpha) result = result.set({ alpha: culoriY });
      return result;
    }

    function updateValues(point: number[], atIndex: number, { commit = false } = {}) {
      const nextX = snapToStep(point[0] ?? 0, minX, maxX, stepX);
      const nextY = snapToStep(point[1] ?? 0, minY, maxY, stepY);
      const nextValues = [...internalValue];
      nextValues[atIndex] = [nextX, nextY];

      setValueIndexToChange(atIndex);

      const hasChanged = JSON.stringify(nextValues) !== JSON.stringify(internalValue);
      if (hasChanged) {
        setInternalValue(nextValues);
        const newColor = displayValuesToColor(nextValues);
        if (newColor) {
          if (!isControlled) setInternalColor(newColor);
          onValueChange?.(newColor);
          if (commit) onValueCommit?.(newColor);
        }
      }
    }

    function getPointFromPointerEvent(event: { clientX: number; clientY: number }, slideStart?: boolean): number[] {
      const el = elementRef.current;
      if (!el) return [minX, minY];
      const rect = rectRef.current || el.getBoundingClientRect();
      rectRef.current = rect;

      const inputX: [number, number] = [0, rect.width];
      const outputX: [number, number] = isSlidingFromLeft ? [minX, maxX] : [maxX, minX];
      const scaleX = linearScale(inputX, outputX);

      const inputY: [number, number] = [0, rect.height];
      const outputY: [number, number] = isSlidingFromTop ? [minY, maxY] : [maxY, minY];
      const scaleY = linearScale(inputY, outputY);

      const posX = event.clientX - rect.left;
      const posY = event.clientY - rect.top;
      return [scaleX(posX), scaleY(posY)];
    }

    const handlePointerDown = useCallback((event: React.PointerEvent) => {
      if (disabled) return;
      const target = event.target as HTMLElement;
      target.setPointerCapture(event.pointerId);
      event.preventDefault();

      if (thumbRef.current && thumbRef.current.contains(target)) {
        thumbRef.current.focus();
        return;
      }

      valuesBeforeSlideStart.current = [...internalValue];
      setIsDragging(true);
      lastPointerPosition.current = { x: event.clientX, y: event.clientY };
      const point = getPointFromPointerEvent(event, true);
      const closestIndex = getClosestThumbIndex(internalValue, point, minX, maxX, minY, maxY);
      if (closestIndex >= 0) updateValues(point, closestIndex);
    }, [disabled, internalValue, minX, maxX, minY, maxY, isSlidingFromLeft, isSlidingFromTop]);

    const handlePointerMove = useCallback((event: React.PointerEvent) => {
      const target = event.target as HTMLElement;
      if (!target.hasPointerCapture(event.pointerId)) return;
      lastPointerPosition.current = { x: event.clientX, y: event.clientY };
      const point = getPointFromPointerEvent(event);
      updateValues(point, valueIndexToChange);
    }, [valueIndexToChange, internalValue, minX, maxX, minY, maxY, isSlidingFromLeft, isSlidingFromTop, stepX, stepY]);

    const handlePointerUp = useCallback((event: React.PointerEvent) => {
      const target = event.target as HTMLElement;
      if (!target.hasPointerCapture(event.pointerId)) return;
      target.releasePointerCapture(event.pointerId);
      setIsDragging(false);
      rectRef.current = undefined;
      offsetPosition.current = undefined;
      lastPointerPosition.current = undefined;
      const prevValue = valuesBeforeSlideStart.current[valueIndexToChange];
      const nextValue = internalValue[valueIndexToChange];
      const hasChanged = prevValue?.[0] !== nextValue?.[0] || prevValue?.[1] !== nextValue?.[1];
      if (hasChanged && colorRef) onValueCommit?.(colorRef);
    }, [valueIndexToChange, internalValue, colorRef, onValueCommit]);

    const STEP_KEY_DELTAS: Record<string, { axis: "x" | "y"; sign: number }> = {
      ArrowRight: { axis: "x", sign: 1 },
      ArrowLeft: { axis: "x", sign: -1 },
      ArrowDown: { axis: "y", sign: 1 },
      ArrowUp: { axis: "y", sign: -1 },
    };

    const handleKeyDown = useCallback((event: React.KeyboardEvent) => {
      if (disabled) return;
      if (event.key === "Home") { event.preventDefault(); handleBoundaryKey("x", minX); return; }
      if (event.key === "End") { event.preventDefault(); handleBoundaryKey("x", maxX); return; }
      if (event.key === "PageUp") { event.preventDefault(); handleBoundaryKey("y", minY); return; }
      if (event.key === "PageDown") { event.preventDefault(); handleBoundaryKey("y", maxY); return; }

      const delta = STEP_KEY_DELTAS[event.key];
      if (!delta) return;
      event.preventDefault();

      const value = internalValue[valueIndexToChange];
      if (!value) return;
      const multiplier = (event.shiftKey && ARROW_KEYS.includes(event.key)) ? 10 : 1;

      const dirMultiplier = delta.axis === "x"
        ? (isSlidingFromLeft ? 1 : -1)
        : (isSlidingFromTop ? 1 : -1);
      const step = delta.axis === "x" ? stepX : stepY;
      const offset = step * multiplier * delta.sign * dirMultiplier;

      const vx = value[0] ?? 0;
      const vy = value[1] ?? 0;
      const point = delta.axis === "x" ? [vx + offset, vy] : [vx, vy + offset];
      updateValues(point, valueIndexToChange, { commit: true });
    }, [disabled, internalValue, valueIndexToChange, isSlidingFromLeft, isSlidingFromTop, stepX, stepY, minX, maxX, minY, maxY]);

    function handleBoundaryKey(axis: "x" | "y", boundaryValue: number) {
      const value = internalValue[valueIndexToChange];
      if (!value) return;
      let effectiveValue = boundaryValue;
      if (axis === "x" && !isSlidingFromLeft) effectiveValue = boundaryValue === minX ? maxX : minX;
      else if (axis === "y" && !isSlidingFromTop) effectiveValue = boundaryValue === minY ? maxY : minY;
      const point = axis === "x" ? [effectiveValue, value[1] ?? 0] : [value[0] ?? 0, effectiveValue];
      updateValues(point, valueIndexToChange, { commit: true });
    }

    const ctxValue = useMemo<ColorAreaContextValue>(() => ({
      disabled,
      minX, maxX, minY, maxY,
      currentModelValue: internalValue,
      valueIndexToChange,
      setValueIndexToChange,
      thumbRef,
      isSlidingFromLeft,
      isSlidingFromTop,
      thumbAlignment,
      colorSpace,
      xChannelKey,
      yChannelKey,
      colorRef,
      isDragging,
    }), [disabled, minX, maxX, minY, maxY, internalValue, valueIndexToChange, isSlidingFromLeft, isSlidingFromTop, thumbAlignment, colorSpace, xChannelKey, yChannelKey, colorRef, isDragging]);

    return (
      <ColorAreaContext.Provider value={ctxValue}>
        <div
          ref={(el) => {
            (elementRef as React.MutableRefObject<HTMLDivElement | null>).current = el;
            if (typeof ref === "function") ref(el);
            else if (ref) ref.current = el;
          }}
          data-slider-area-impl
          aria-disabled={disabled}
          data-disabled={disabled ? "" : undefined}
          className={className}
          style={{
            ...style,
            "--reka-slider-area-thumb-transform": `translate(${!isSlidingFromLeft && thumbAlignment === "overflow" ? "50%" : "-50%"}, ${!isSlidingFromTop && thumbAlignment === "overflow" ? "50%" : "-50%"})`,
          } as React.CSSProperties}
          onPointerDown={handlePointerDown}
          onPointerMove={handlePointerMove}
          onPointerUp={handlePointerUp}
          onKeyDown={handleKeyDown}
        >
          {children}
        </div>
      </ColorAreaContext.Provider>
    );
  },
);
