// packages/svelte/src/lib/components/color-swatch/ColorSwatch.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { Color } from "@urcolor/core";
  import type { ChildSnippetArgs } from "../../shared/child.js";

  export interface ColorSwatchProps extends HTMLAttributes<HTMLElement> {
    /** The colour to display. Accepts a `Color` or any CSS colour string. */
    value?: Color | string | null;
    /** The checkerboard tile size, in pixels. */
    checkerSize?: number;
    /** When true, reflects the colour's alpha channel; otherwise it paints fully opaque. */
    alpha?: boolean;
    /** When true, prevents the user from interacting with the swatch. */
    disabled?: boolean;
    /**
     * Renders the swatch as a toggle button instead of a static `role="img"`
     * element. Defaults to true when `pressed` or `onPressedChange` is supplied.
     */
    toggle?: boolean;
    /** Whether the swatch is selected. Bindable: `bind:pressed`. */
    pressed?: boolean;
    /** Called whenever the pressed state flips. */
    onPressedChange?: (pressed: boolean) => void;
    /** Replaces the default element; receives the props it would have received. */
    child?: Snippet<[ChildSnippetArgs]>;
  }
</script>

<script lang="ts">
  import { untrack } from "svelte";
  import { createAttachmentKey } from "svelte/attachments";
    import {
      DATA_DISABLED,
      DATA_PRESSED,
      isToggleActivationKey,
      parseColor,
      toggleAria,
    } from "@urcolor/primitives";
  import type { ChildProps } from "../../shared/child.js";

  const CHECKER_PATTERN
    = "repeating-conic-gradient(rgb(230, 230, 230) 0%, rgb(230, 230, 230) 25%, white 0%, white 50%) 0% 50%";

  let {
    value,
    checkerSize = 16,
    alpha: showAlpha = false,
    disabled = false,
    toggle,
    pressed = $bindable(),
    onPressedChange,
    class: className,
    style,
    children,
    child,
    ...rest
  }: ColorSwatchProps = $props();

  /**
   * Resolved once: `pressed` becomes defined as soon as the swatch is toggled,
   * so reading it reactively would flip a static swatch into a button.
   */
  const inferredToggle = untrack(() => pressed !== undefined || onPressedChange !== undefined);
  const interactive = $derived(toggle ?? inferredToggle);

  /** Uncontrolled fallback, kept in sync so it and `pressed` never disagree. */
  let internalPressed = $state<boolean>(untrack(() => pressed ?? false));
  const isPressed = $derived(pressed ?? internalPressed);

  const color = $derived(parseColor(value));
  const checkerboard = $derived(`${CHECKER_PATTERN} / ${checkerSize}px ${checkerSize}px`);

  /**
   * The four CSS custom properties React's swatch emits, plus the painted
   * background. They are always all present, including for an unparseable or
   * absent value, so consumer styling never has to guard for a missing var.
   */
  const swatchStyle = $derived.by(() => {
    const vars = (opaque: string, alphaValue: number, current: string) =>
      `--swatch-color-opaque:${opaque};--swatch-alpha:${alphaValue};--swatch-checkerboard:${checkerboard};--swatch-color:${current};`;

    if (!color) {
      return `${vars("transparent", 1, "transparent")}background:linear-gradient(transparent, transparent), ${checkerboard};`;
    }

    const opaqueStr = color.withAlpha(1).to("srgb").toString();
    const colorStr = showAlpha ? color.to("srgb").toString() : opaqueStr;
    return `${vars(opaqueStr, color.alpha, colorStr)}background:linear-gradient(${colorStr}, ${colorStr}), ${checkerboard};`;
  });

  function togglePressed(): void {
    if (disabled) return;
    const next = !isPressed;
    internalPressed = next;
    pressed = next;
    onPressedChange?.(next);
  }

  const attachmentKey = createAttachmentKey();

  /**
   * The toggle behaviour, carried inside the props object under a `Symbol` key
   * so a consumer spreading those props onto their own element — or onto
   * another component — gets it too.
   *
   * `keydown` calls `preventDefault` for Enter and Space, which suppresses the
   * click a native button would otherwise synthesise; without it every keyboard
   * activation would toggle twice.
   */
  function interaction(node: HTMLElement): () => void {
    const onClick = (): void => togglePressed();
    const onKeyDown = (event: KeyboardEvent): void => {
      if (!isToggleActivationKey(event.key)) return;
      event.preventDefault();
      togglePressed();
    };

    node.addEventListener("click", onClick);
    node.addEventListener("keydown", onKeyDown);

    return () => {
      node.removeEventListener("click", onClick);
      node.removeEventListener("keydown", onKeyDown);
    };
  }

  const elementProps = $derived<ChildProps>({
    ...rest,
    ...(interactive
      ? { ...toggleAria(isPressed, disabled), type: "button", disabled: disabled || undefined }
      : { role: "img" }),
    class: className,
    // The caller's declarations come last so they win the cascade.
    style: style ? `${swatchStyle}${style}` : swatchStyle,
    [DATA_PRESSED]: interactive && isPressed ? "" : undefined,
    [DATA_DISABLED]: disabled ? "" : undefined,
    ...(interactive ? { [attachmentKey]: interaction } : {}),
  });
</script>

{#if child}
  {@render child({ props: elementProps })}
{:else if interactive}
  <button {...elementProps}>{@render children?.()}</button>
{:else}
  <div {...elementProps}>{@render children?.()}</div>
{/if}

// packages/angular/src/components/color-swatch/root/color-swatch.ts
import {
  afterNextRender,
  booleanAttribute,
  computed,
  DestroyRef,
  Directive,
  ElementRef,
  HostAttributeToken,
  inject,
  input,
  model,
  numberAttribute,
  signal,
  untracked,
  type OnInit,
} from "@angular/core";
import type { Color } from "@urcolor/core";
import {
  DATA_DISABLED,
  DATA_PRESSED,
  isToggleActivationKey,
  parseColor,
  toggleAria,
} from "@urcolor/primitives";

/**
 * The transparency grid the swatch paints under its colour. The tile size is
 * appended per instance, so the pattern itself carries no `background-size`.
 */
const CHECKER_PATTERN
  = "repeating-conic-gradient(rgb(230, 230, 230) 0%, rgb(230, 230, 230) 25%, white 0%, white 50%) 0% 50%";

/**
 * A single colour sample. Standalone it is a static `role="img"` element; as a
 * toggle it is a self-contained pressed/unpressed button.
 *
 * ```html
 * <div urcColorSwatch [value]="color()"></div>
 * <button urcColorSwatch [value]="'#f43f5e'" [(pressed)]="selected"></button>
 * ```
 *
 * The swatch always emits the same four custom properties — `--swatch-color`,
 * `--swatch-color-opaque`, `--swatch-alpha` and `--swatch-checkerboard` — even
 * for an absent or unparseable value, so consumer styling never has to guard
 * for a missing variable.
 *
 * Inside a `ColorSwatchGroup` the group owns roving focus: it listens for
 * `keydown` and `focusin` bubbling from its items, so the swatch needs no
 * coupling to it and stays usable on its own.
 */
@Directive({
  selector: "[urcColorSwatch]",
  exportAs: "urcColorSwatch",
  host: {
    "[attr.role]": "role()",
    "[attr.type]": "buttonType()",
    "[attr.aria-pressed]": "ariaPressed()",
    "[attr.aria-disabled]": "ariaDisabled()",
    "[attr.tabindex]": "tabIndex()",
    [`[attr.${DATA_PRESSED}]`]: "dataPressed()",
    [`[attr.${DATA_DISABLED}]`]: "dataDisabled()",
    "[style.--swatch-color]": "swatchColor()",
    "[style.--swatch-color-opaque]": "swatchColorOpaque()",
    "[style.--swatch-alpha]": "swatchAlpha()",
    "[style.--swatch-checkerboard]": "checkerboard()",
    "[style.background]": "background()",
    "(click)": "onClick()",
    "(keydown)": "onKeyDown($event)",
  },
})
export class ColorSwatch implements OnInit {
  /** The colour to display. Accepts a `Color` or any CSS colour string. */
  readonly value = input<Color | string | null>();
  /** The transparency grid's tile size, in pixels. */
  readonly checkerSize = input(16, { transform: numberAttribute });
  /** When true, reflects the colour's alpha; otherwise it paints fully opaque. */
  readonly alpha = input(false, { transform: booleanAttribute });
  /**
   * Forces toggle behaviour on or off. Left unset, the swatch becomes a toggle
   * when `[(pressed)]` is bound.
   */
  readonly toggle = input<boolean>();
  /** Whether the swatch is selected, two-way bindable as `[(pressed)]`. */
  readonly pressed = model<boolean | undefined>(undefined);

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly destroyRef = inject(DestroyRef);

  /** Static attributes the consumer set themselves always win over ours. */
  private readonly roleAttr = inject(new HostAttributeToken("role"), { optional: true });
  private readonly typeAttr = inject(new HostAttributeToken("type"), { optional: true });
  private readonly tabIndexAttr = inject(new HostAttributeToken("tabindex"), { optional: true });

  /**
   * `disabled` is DOM state, not an input. The static host attribute is read at
   * construction — which works under SSR, where there is no DOM — and a
   * `MutationObserver` installed after the first render keeps it live.
   */
  private readonly disabledState = signal(
    inject(new HostAttributeToken("disabled"), { optional: true }) !== null,
  );

  /**
   * Whether the host is a native `<button>`, which already carries the role and
   * the click-on-Enter/Space behaviour an arbitrary element does not.
   */
  private readonly isButtonElement
    = (this.host.nativeElement?.tagName ?? "").toLowerCase() === "button";

  /** Resolved once `pressed` has been bound; see {@link ngOnInit}. */
  private readonly inferredToggle = signal(false);

  /** Whether interaction is refused. */
  readonly isDisabled = this.disabledState.asReadonly();
  /** Whether the swatch behaves as a toggle rather than a static sample. */
  readonly interactive = computed(() => this.toggle() ?? this.inferredToggle());
  /** The pressed state, defaulting to unpressed while `pressed` is unbound. */
  readonly isPressed = computed(() => this.pressed() ?? false);

  private readonly color = computed(() => parseColor(this.value()));

  private readonly opaqueString = computed(
    () => this.color()?.withAlpha(1).to("srgb").toString() ?? "transparent",
  );

  private readonly colorString = computed(() => {
    const color = this.color();
    if (!color) return "transparent";
    return this.alpha() ? color.to("srgb").toString() : this.opaqueString();
  });

  protected readonly checkerboard = computed(
    () => `${CHECKER_PATTERN} / ${this.checkerSize()}px ${this.checkerSize()}px`,
  );

  protected readonly swatchColor = this.colorString;
  protected readonly swatchColorOpaque = this.opaqueString;
  protected readonly swatchAlpha = computed(() => this.color()?.alpha ?? 1);

  /**
   * The colour is painted as a flat gradient rather than a `background-color`
   * so that it composites over the checkerboard in a single declaration.
   */
  protected readonly background = computed(() => {
    const colorStr = this.colorString();
    return `linear-gradient(${colorStr}, ${colorStr}), ${this.checkerboard()}`;
  });

  private readonly aria = computed(() => toggleAria(this.isPressed(), this.isDisabled()));

  protected readonly role = computed(() => {
    if (this.roleAttr !== null) return this.roleAttr;
    if (!this.interactive()) return "img";
    // A native button needs no role; anything else must claim one so the
    // group's roving focus can find it.
    return this.isButtonElement ? null : "button";
  });

  protected readonly buttonType = computed(() => {
    if (this.typeAttr !== null) return this.typeAttr;
    return this.interactive() && this.isButtonElement ? "button" : null;
  });

  protected readonly ariaPressed = computed(() =>
    this.interactive() ? this.aria()["aria-pressed"] : null,
  );

  protected readonly ariaDisabled = computed(() => this.aria()["aria-disabled"] ?? null);

  protected readonly dataPressed = computed(() =>
    this.interactive() ? this.aria()[DATA_PRESSED] ?? null : null,
  );

  protected readonly dataDisabled = computed(() => this.aria()[DATA_DISABLED] ?? null);

  protected readonly tabIndex = computed<string | number | null>(() => {
    if (this.tabIndexAttr !== null) return this.tabIndexAttr;
    if (!this.interactive()) return null;
    return this.aria().tabindex ?? null;
  });

  constructor() {
    // `afterNextRender` never runs on the server, so this is the only place a
    // directive may touch the DOM.
    afterNextRender(() => {
      const element = this.host.nativeElement;
      this.syncDisabled(element);
      if (typeof MutationObserver === "undefined") return;
      const observer = new MutationObserver(() => this.syncDisabled(element));
      // Deliberately excludes our own data-* bindings, so there is no feedback loop.
      observer.observe(element, { attributes: true, attributeFilter: ["disabled"] });
      this.destroyRef.onDestroy(() => observer.disconnect());
    });
  }

  /**
   * Toggle inference is resolved once, after the first binding pass: `pressed`
   * becomes defined as soon as the swatch is toggled, so reading it reactively
   * would flip a static swatch into a button.
   */
  ngOnInit(): void {
    this.inferredToggle.set(untracked(this.pressed) !== undefined);
  }

  /** Flips the pressed state, honouring `disabled` and non-toggle swatches. */
  togglePressed(): void {
    if (this.isDisabled() || !this.interactive()) return;
    this.pressed.set(!this.isPressed());
  }

  protected onClick(): void {
    this.togglePressed();
  }

  /**
   * `preventDefault` suppresses the click a native button would otherwise
   * synthesise; without it every keyboard activation would toggle twice.
   */
  protected onKeyDown(event: KeyboardEvent): void {
    if (!this.interactive() || !isToggleActivationKey(event.key)) return;
    event.preventDefault();
    this.togglePressed();
  }

  private syncDisabled(element: HTMLElement): void {
    this.disabledState.set(element.hasAttribute("disabled"));
  }
}
