// packages/vue/src/components/ColorRing/ColorRingCheckerboard.vue
<script lang="ts">
import type { CheckerboardProps } from "../../shared/Checkerboard.vue";

/**
 * @deprecated Deprecated. The Gradient component now paints the checkerboard itself, so
 * this component is no longer needed.
 */
export interface ColorRingCheckerboardProps extends Omit<CheckerboardProps, "shape"> {}
</script>

<script setup lang="ts">
import Checkerboard from "../../shared/Checkerboard.vue";

const props = withDefaults(defineProps<ColorRingCheckerboardProps>(), {
  as: "div",
});
</script>

<template>
  <Checkerboard
    v-bind="props"
    shape="circle"
  />
</template>

// packages/react/src/components/color-ring/checkerboard/ColorRingCheckerboard.tsx
import { forwardRef, type ComponentPropsWithoutRef } from "react";
import { CHECKERBOARD_STYLE } from "@urcolor/shared";
import { warnCheckerboardDeprecated } from "../../../utils";

/**
 * @deprecated Deprecated. The Gradient component now paints the checkerboard itself, so
 * this component is no longer needed.
 */
export interface ColorRingCheckerboardProps extends ComponentPropsWithoutRef<"div"> {}

/** @deprecated The Gradient component now paints the checkerboard itself; remove this component. */
export const ColorRingCheckerboard = forwardRef<HTMLDivElement, ColorRingCheckerboardProps>(
  function ColorRingCheckerboard({ style, ...props }, ref) {
    warnCheckerboardDeprecated();
    return (
      <div
        ref={ref}
        style={{
          position: "absolute",
          inset: "0",
          pointerEvents: "none",
          ...CHECKERBOARD_STYLE,
          ...style,
        }}
        {...props}
      />
    );
  },
);
