// packages/svelte/src/lib/components/color-triangle/gradient/ColorTriangleGradient.svelte
<script module lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import type { GradientRenderer } from "@urcolor/shared";
  import type { ChildSnippetArgs } from "../../../shared/child.js";

  export interface ColorTriangleGradientProps extends HTMLAttributes<HTMLSpanElement> {
    /**
     * Lock channels to fixed values in the gradient.
     * - `{ alpha: 1 }` (default) — lock alpha to 1
     * - `false` — no overrides
     */
    channelOverrides?: Record<string, number> | false;
    /**
     * Which painter to use. A barycentric sweep has no CSS equivalent, so this
     * component always paints into a canvas — the prop exists for symmetry with
     * the other gradients, and `"css"` warns and falls back.
     */
    renderer?: GradientRenderer;
    /**
     * Replaces the default `<canvas>`; receives its props, including the paint
     * attachment. The checkerboard wrapper is always rendered by this part.
     */
    child?: Snippet<[ChildSnippetArgs]>;
  }
</script>

<script lang="ts">
  import { createAttachmentKey } from "svelte/attachments";
  import { Color } from "@urcolor/core";
  import { CHECKERBOARD_BACKGROUND, DATA_DISABLED, getChannelConfig, renderToCanvas, sampleTriangleGrid } from "@urcolor/shared";
  import { warnNoCssRecipe } from "../../../shared/cssGradient.svelte.js";
  import type { ChildProps } from "../../../shared/child.js";
  import { gradientAttachment } from "../../../shared/gradient.svelte.js";
  import { colorTriangleContext } from "../root/context.svelte.js";

  /** Both axes are sampled at this resolution and then smoothly upscaled. */
  const GRID = 64;

  let {
    channelOverrides = { alpha: 1 },
    class: className,
    style,
    renderer = "auto",
    children,
    child,
    ...rest
  }: ColorTriangleGradientProps = $props();

  const context = colorTriangleContext.get();

  const canvasOpacity = $derived.by(() => {
    if (channelOverrides === false || channelOverrides.alpha === undefined) return context.color.alpha;
    return 1;
  });

  /**
   * Cut once, on the wrapper — it clips the canvas with it. Clipping the canvas
   * to the same polygon as well left a seam along the three edges: each clip
   * antialiases independently and the two partial coverages multiply.
   * `sampleTriangleGrid` clamps its barycentric coordinates, so the canvas is
   * coloured out to its corners and nothing translucent can show through.
   */
  const clipPath = $derived.by(() => {
    const [v0, v1, v2] = context.vertices;
    return `clip-path:polygon(${v0.x * 100}% ${v0.y * 100}%, ${v1.x * 100}% ${v1.y * 100}%, ${v2.x * 100}% ${v2.y * 100}%);`;
  });

  /** Applies the caller's fixed channel values on top of a base colour. */
  function withOverrides(base: Color): Color {
    if (channelOverrides === false) return base;
    let result = base;
    const applicable: Record<string, number> = {};
    for (const [key, value] of Object.entries(channelOverrides)) {
      if (key === "alpha") result = result.withAlpha(value);
      else if (getChannelConfig(context.colorSpace, key)) applicable[key] = value;
    }
    if (Object.keys(applicable).length > 0) {
      result = result.with({ space: context.colorSpace, ...applicable });
    }
    return result;
  }

  function paint(canvas: HTMLCanvasElement): void {
    // Sampling a triangle is the most expensive of the five grids, and a drag
    // only moves the channels the surface already spans, so the pixels cannot
    // change while one is in flight.
    if (context.dragging) return;

    const xConfig = getChannelConfig(context.colorSpace, context.xChannelKey);
    const yConfig = getChannelConfig(context.colorSpace, context.yChannelKey);
    if (!xConfig || !yConfig) return;

    let zChannel: string | undefined;
    let zMin: number | undefined;
    let zMax: number | undefined;
    if (context.isThreeChannel && context.zChannelKey !== undefined) {
      const zConfig = getChannelConfig(context.colorSpace, context.zChannelKey);
      if (zConfig) {
        zChannel = context.zChannelKey;
        zMin = zConfig.nativeMin ?? zConfig.min;
        zMax = zConfig.nativeMax ?? zConfig.max;
      }
    }

    const [v0, v1, v2] = context.vertices;
    const pixels = sampleTriangleGrid(
      withOverrides(context.color),
      context.colorSpace,
      context.xChannelKey,
      context.yChannelKey,
      xConfig.nativeMin ?? xConfig.min,
      xConfig.nativeMax ?? xConfig.max,
      yConfig.nativeMin ?? yConfig.min,
      yConfig.nativeMax ?? yConfig.max,
      v0,
      v1,
      v2,
      GRID,
      GRID,
      false,
      zChannel,
      zMin,
      zMax,
    );
    renderToCanvas({ canvas, pixels, sampleWidth: GRID, sampleHeight: GRID });
  }

  const paintCanvas = gradientAttachment(paint);
  const attachmentKey = createAttachmentKey();

  /**
   * Stable identity, so the attachment is not torn down on every render; it
   * still re-runs whenever the reactive state `paint` reads changes.
   */
  function canvasAttachment(node: HTMLCanvasElement): () => void {
    const cleanup = paintCanvas(node);
    return () => {
      cleanup();
      // WebGL contexts are a capped per-document resource; release ours.
      node.getContext("webgl")?.getExtension("WEBGL_lose_context")?.loseContext();
    };
  }

  // A barycentric sweep has no CSS equivalent, so there is nothing to resolve —
  // only the same warning the other gradients emit when asked for the impossible.
  $effect(() => {
    if (renderer === "css") warnNoCssRecipe("ColorTriangleGradient");
  });

  const canvasProps = $derived<ChildProps>({
    style: `position:absolute;inset:0;width:100%;height:100%;pointer-events:none;opacity:${canvasOpacity};`,
    [attachmentKey]: canvasAttachment,
  });

  const elementProps = $derived<ChildProps>({
    ...rest,
    class: className,
    // The caller's declarations come last so they win the cascade.
    style: `background:${CHECKERBOARD_BACKGROUND};${clipPath}${style ?? ""}`,
    [DATA_DISABLED]: context.disabled ? "" : undefined,
  });
</script>

<span {...elementProps}>
  {#if child}
    {@render child({ props: canvasProps })}
  {:else}
    <canvas {...canvasProps}></canvas>
  {/if}
  {@render children?.()}
</span>

// packages/angular/src/components/color-triangle/gradient/color-triangle-gradient.ts
import {
  afterNextRender,
  computed,
  DestroyRef,
  Directive,
  effect,
  ElementRef,
  inject,
  Injector,
  input,
} from "@angular/core";
import { Color } from "@urcolor/core";
import { CHECKERBOARD_BACKGROUND, DATA_DISABLED, getChannelConfig, renderToCanvas, sampleTriangleGrid } from "@urcolor/shared";
import { warnNoCssRecipe, type GradientRenderer } from "../../../shared/css-gradient";
import { ColorTriangleRoot } from "../root/color-triangle-root";

/** Both axes are sampled at this resolution and then smoothly upscaled. */
const GRID = 64;

/**
 * Channels locked to fixed values while the gradient is drawn, or `false` for
 * no overrides at all.
 */
export type ColorTriangleChannelOverrides = Record<string, number> | false;

/**
 * Paints the triangle's colour surface onto a `<canvas>` the consumer supplies.
 *
 * The transparency checkerboard is this element's CSS background, which the
 * canvas bitmap composites over — there is no separate `Checkerboard` part.
 *
 * The outline is cut here as well as on the root. `sampleTriangleGrid` clamps
 * its barycentric coordinates, so the bitmap is coloured out to its corners and
 * nothing translucent can show through the clip.
 */
@Directive({
  selector: "canvas[urcColorTriangleGradient]",
  exportAs: "urcColorTriangleGradient",
  host: {
    [`[attr.${DATA_DISABLED}]`]: "root.isDisabled() ? '' : null",
    "[style.position]": "'absolute'",
    "[style.inset]": "'0'",
    "[style.width]": "'100%'",
    "[style.height]": "'100%'",
    "[style.pointer-events]": "'none'",
    "[style.background]": "checkerboard",
    "[style.clip-path]": "clipPath()",
    "[style.opacity]": "canvasOpacity()",
  },
})
export class ColorTriangleGradient {
  /**
   * Which painter to use. A barycentric sweep has no CSS equivalent, so this
   * directive always paints into its canvas — the input exists for symmetry
   * with the other gradients, and `"css"` warns and falls back.
   */
  readonly renderer = input<GradientRenderer>("auto");

  /** Locked channels. Defaults to `{ alpha: 1 }`; pass `false` to disable. */
  readonly channelOverrides = input<ColorTriangleChannelOverrides>({ alpha: 1 });

  protected readonly checkerboard = CHECKERBOARD_BACKGROUND;

  protected readonly root = inject(ColorTriangleRoot);
  private readonly host = inject<ElementRef<HTMLCanvasElement>>(ElementRef);
  private readonly injector = inject(Injector);
  private readonly destroyRef = inject(DestroyRef);

  protected readonly canvasOpacity = computed(() => {
    const overrides = this.channelOverrides();
    if (overrides === false || overrides["alpha"] === undefined) return this.root.value().alpha;
    return 1;
  });

  protected readonly clipPath = computed(() => {
    const points = this.root
      .vertices()
      .map(point => `${(point.x * 100).toFixed(2)}% ${(point.y * 100).toFixed(2)}%`)
      .join(", ");
    return `polygon(${points})`;
  });

  constructor() {
    // A barycentric sweep has no CSS equivalent, so there is nothing to
    // resolve — only the same warning the other gradients emit when asked for
    // the impossible.
    effect(() => {
      if (this.renderer() === "css") warnNoCssRecipe("ColorTriangleGradient");
    });

    // Canvas work is deferred to `afterNextRender`: it never runs on the
    // server, where `OffscreenCanvas` and WebGL do not exist. The effect is
    // created here rather than as a field so that it, too, is browser-only.
    afterNextRender(() => {
      const canvas = this.host.nativeElement;

      effect(() => this.paint(canvas), { injector: this.injector });

      if (typeof ResizeObserver !== "undefined") {
        const observer = new ResizeObserver(() => this.paint(canvas));
        observer.observe(canvas);
        this.destroyRef.onDestroy(() => observer.disconnect());
      }

      this.destroyRef.onDestroy(() => {
        // WebGL contexts are a capped per-document resource; release ours.
        canvas.getContext("webgl")?.getExtension("WEBGL_lose_context")?.loseContext();
      });
    });
  }

  /** Applies the caller's fixed channel values on top of a base colour. */
  private withOverrides(base: Color): Color {
    const overrides = this.channelOverrides();
    if (overrides === false) return base;
    const colorSpace = this.root.colorSpace();
    const applicable: Record<string, number> = {};
    let result = base;
    for (const [key, value] of Object.entries(overrides)) {
      if (key === "alpha") result = result.withAlpha(value);
      else if (getChannelConfig(colorSpace, key)) applicable[key] = value;
    }
    if (Object.keys(applicable).length > 0) {
      result = result.with({ space: colorSpace, ...applicable });
    }
    return result;
  }

  private paint(canvas: HTMLCanvasElement): void {
    // Sampling a triangle is the most expensive of the five grids, and a drag
    // only moves the channels the surface already spans, so the pixels cannot
    // change while one is in flight.
    if (this.root.dragging()) return;

    const colorSpace = this.root.colorSpace();
    const xChannel = this.root.xChannelKey();
    const yChannel = this.root.yChannelKey();
    const xConfig = getChannelConfig(colorSpace, xChannel);
    const yConfig = getChannelConfig(colorSpace, yChannel);
    if (!xConfig || !yConfig) return;

    let zChannel: string | undefined;
    let zMin: number | undefined;
    let zMax: number | undefined;
    const rootZChannel = this.root.zChannelKey();
    if (this.root.isThreeChannel() && rootZChannel !== undefined) {
      const zConfig = getChannelConfig(colorSpace, rootZChannel);
      if (zConfig) {
        zChannel = rootZChannel;
        zMin = zConfig.nativeMin ?? zConfig.min;
        zMax = zConfig.nativeMax ?? zConfig.max;
      }
    }

    const [v0, v1, v2] = this.root.vertices();
    const pixels = sampleTriangleGrid(
      this.withOverrides(this.root.value()),
      colorSpace,
      xChannel,
      yChannel,
      xConfig.nativeMin ?? xConfig.min,
      xConfig.nativeMax ?? xConfig.max,
      yConfig.nativeMin ?? yConfig.min,
      yConfig.nativeMax ?? yConfig.max,
      v0,
      v1,
      v2,
      GRID,
      GRID,
      false,
      zChannel,
      zMin,
      zMax,
    );
    renderToCanvas({ canvas, pixels, sampleWidth: GRID, sampleHeight: GRID });
  }
}
