// packages/vue/src/components/ColorField/ColorFieldRoot.vue
<script lang="ts">
import type { Ref, Ref as VueRef } from "vue";
import type { PrimitiveProps } from "reka-ui";
import { createContext, Primitive, useForwardExpose, VisuallyHidden } from "reka-ui";
import "internationalized-color/css";
import { Color } from "internationalized-color";

export interface ColorFieldRootProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
  /** The controlled color value. v-model binding. */
  modelValue?: Color | string | null;
  /** The color space mode (e.g. 'hsl', 'oklch'). */
  colorSpace?: string;
  /** Which channel this field controls (e.g. 'h', 's', 'l'). */
  channel?: string;
  /** Channel display format. Auto-derived from colorSpace config if not set. */
  format?: "number" | "degree" | "percentage" | "hex";
  /** Minimum allowed value. Auto-derived from colorSpace config if not set. */
  min?: number;
  /** Maximum allowed value. Auto-derived from colorSpace config if not set. */
  max?: number;
  /** Step increment for arrow keys. Auto-derived from colorSpace config if not set. */
  step?: number;
  /** Whether the field is disabled. */
  disabled?: boolean;
  /** Whether the field is read-only. */
  readOnly?: boolean;
  /** Hidden input name for form submission. */
  name?: string;
  /** Whether required for form submission. */
  required?: boolean;
}

export type ColorFieldRootEmits = {
  "update:modelValue": [value: Color | undefined];
  "valueCommit": [value: Color];
};

export interface ColorFieldRootContext {
  modelValue: Ref<number | undefined>;
  displayValue: Ref<string>;
  disabled: Ref<boolean>;
  readOnly: Ref<boolean>;
  isDecreaseDisabled: Ref<boolean>;
  isIncreaseDisabled: Ref<boolean>;
  handleIncrease: (multiplier?: number) => void;
  handleDecrease: (multiplier?: number) => void;
  handleMinMaxValue: (type: "min" | "max") => void;
  commitValue: (val: number | undefined) => void;
  onInputChange: (text: string) => void;
  inputEl: Ref<HTMLInputElement | undefined>;
  onInputElement: (el: HTMLInputElement) => void;
  format: Ref<"number" | "degree" | "percentage" | "hex">;
}

export const [injectColorFieldRootContext, provideColorFieldRootContext]
  = createContext<ColorFieldRootContext>("ColorFieldRoot");
</script>

<script setup lang="ts">
import { computed, ref, shallowRef, toRefs, watch } from "vue";
import { getChannelConfig, displayToCulori, culoriToDisplay } from "@urcolor/core";
import { clamp, snapToStep, useFormControl } from "../ColorArea/utils";

const props = withDefaults(defineProps<ColorFieldRootProps>(), {
  as: "div",
  colorSpace: "hsl",
  channel: "h",
  disabled: false,
  readOnly: false,
  required: false,
});

const emit = defineEmits<ColorFieldRootEmits>();

const { disabled, readOnly } = toRefs(props);
const { forwardRef, currentElement } = useForwardExpose();
const isFormControl = useFormControl(currentElement);

function parseColor(v: Color | string | null | undefined): Color | undefined {
  if (!v) return undefined;
  if (v instanceof Color) return v;
  return Color.parse(v) ?? undefined;
}

const colorRef = shallowRef<Color | undefined>(parseColor(props.modelValue));

watch(() => props.modelValue, (val) => {
  const parsed = parseColor(val);
  if (parsed) colorRef.value = parsed;
});

const channelConfig = computed(() => getChannelConfig(props.colorSpace, props.channel));

// Resolve effective min/max/step/format from props or config
const effectiveMin = computed(() => props.min ?? channelConfig.value?.min ?? 0);
const effectiveMax = computed(() => props.max ?? channelConfig.value?.max ?? (isHexMode.value ? 0xFFFFFF : 100));
const effectiveStep = computed(() => props.step ?? channelConfig.value?.step ?? 1);
const effectiveFormat = computed<"number" | "degree" | "percentage" | "hex">(() => {
  return props.format ?? channelConfig.value?.format ?? "number";
});

const isHexMode = computed(() => effectiveFormat.value === "hex");

// Extract display value from Color
function getDisplayValue(): number | undefined {
  if (!colorRef.value) return undefined;
  if (isHexMode.value) {
    // Convert color to integer: 0xRRGGBB
    const hex = colorRef.value.toHex().replace(/^#/, "");
    return Number.parseInt(hex.slice(0, 6), 16);
  }
  if (!channelConfig.value) return undefined;
  const converted = colorRef.value.to(props.colorSpace);
  if (!converted) return undefined;
  const raw = converted.get(props.channel, 0);
  return culoriToDisplay(channelConfig.value, raw);
}

const numericValue = ref<number | undefined>(getDisplayValue());

watch(colorRef, () => {
  const v = getDisplayValue();
  if (v !== undefined && Math.abs((v ?? 0) - (numericValue.value ?? 0)) > 0.001) {
    numericValue.value = v;
  }
});

// Rebuild Color from numeric display value
function rebuildColor(displayVal: number): Color | undefined {
  if (!colorRef.value) return undefined;
  if (isHexMode.value) {
    const hexStr = `#${Math.round(clamp(displayVal, 0, 0xFFFFFF)).toString(16).padStart(6, "0")}`;
    return Color.parse(hexStr) ?? undefined;
  }
  if (!channelConfig.value) return undefined;
  const culoriVal = displayToCulori(channelConfig.value, displayVal);
  return colorRef.value.set({
    mode: props.colorSpace,
    [props.channel]: culoriVal,
  });
}

const inputEl = ref<HTMLInputElement>();

function formatValue(val: number | undefined): string {
  if (val === undefined) return "";
  switch (effectiveFormat.value) {
    case "degree":
      return `${val}deg`;
    case "percentage":
      return `${val}%`;
    case "hex":
      return `#${Math.round(val).toString(16).padStart(6, "0")}`;
    default:
      return String(val);
  }
}

function parseValue(text: string): number | undefined {
  const trimmed = text.trim();
  if (trimmed === "") return undefined;
  switch (effectiveFormat.value) {
    case "degree":
      return Number.parseFloat(trimmed.replace(/deg$/i, ""));
    case "percentage":
      return Number.parseFloat(trimmed.replace(/%$/, ""));
    case "hex": {
      const hex = trimmed.replace(/^#/, "");
      if (!/^[0-9a-f]*$/i.test(hex)) return undefined;
      return Number.parseInt(hex, 16);
    }
    default:
      return Number.parseFloat(trimmed);
  }
}

function clampValue(val: number): number {
  let clamped = clamp(val, effectiveMin.value, effectiveMax.value);
  clamped = snapToStep(clamped, effectiveMin.value, effectiveMax.value, effectiveStep.value);
  return clamped;
}

const displayValue = ref(formatValue(numericValue.value));

watch(numericValue, (val) => {
  displayValue.value = formatValue(val);
});

function emitColor(val: number) {
  const newColor = rebuildColor(val);
  if (newColor) {
    colorRef.value = newColor;
    emit("update:modelValue", newColor);
  }
  return newColor;
}

function commitValue(val: number | undefined) {
  if (val === undefined || Number.isNaN(val)) {
    numericValue.value = undefined;
    displayValue.value = "";
    return;
  }
  const clamped = isHexMode.value ? clamp(Math.round(val), effectiveMin.value, effectiveMax.value) : clampValue(val);
  numericValue.value = clamped;
  displayValue.value = formatValue(clamped);
  const newColor = emitColor(clamped);
  if (newColor) emit("valueCommit", newColor);
}

function onInputChange(text: string) {
  displayValue.value = text;
  const parsed = parseValue(text);
  if (parsed !== undefined && !Number.isNaN(parsed)) {
    numericValue.value = parsed;
    emitColor(parsed);
  }
}

function handleIncrease(multiplier = 1) {
  if (props.disabled || props.readOnly) return;
  const current = numericValue.value ?? 0;
  const next = clampValue(current + effectiveStep.value * multiplier);
  numericValue.value = next;
  displayValue.value = formatValue(next);
  const newColor = emitColor(next);
  if (newColor) emit("valueCommit", newColor);
}

function handleDecrease(multiplier = 1) {
  if (props.disabled || props.readOnly) return;
  const current = numericValue.value ?? 0;
  const next = clampValue(current - effectiveStep.value * multiplier);
  numericValue.value = next;
  displayValue.value = formatValue(next);
  const newColor = emitColor(next);
  if (newColor) emit("valueCommit", newColor);
}

function handleMinMaxValue(type: "min" | "max") {
  if (props.disabled || props.readOnly) return;
  const val = type === "min" ? effectiveMin.value : effectiveMax.value;
  numericValue.value = val;
  displayValue.value = formatValue(val);
  const newColor = emitColor(val);
  if (newColor) emit("valueCommit", newColor);
}

const isDecreaseDisabled = computed(() => {
  if (numericValue.value === undefined) return false;
  return clampValue(numericValue.value) <= effectiveMin.value;
});

const isIncreaseDisabled = computed(() => {
  if (numericValue.value === undefined) return false;
  return clampValue(numericValue.value) >= effectiveMax.value;
});

function onInputElement(el: HTMLInputElement) {
  inputEl.value = el;
}

provideColorFieldRootContext({
  modelValue: numericValue,
  displayValue,
  disabled,
  readOnly,
  isDecreaseDisabled,
  isIncreaseDisabled,
  handleIncrease,
  handleDecrease,
  handleMinMaxValue,
  commitValue,
  onInputChange,
  inputEl,
  onInputElement,
  format: effectiveFormat,
});
</script>

<template>
  <Primitive
    :ref="forwardRef"
    :as="as"
    :as-child="asChild"
    :dir="undefined"
    :data-disabled="disabled ? '' : undefined"
    :data-readonly="readOnly ? '' : undefined"
  >
    <slot />

    <VisuallyHidden
      v-if="isFormControl && name"
      as="input"
      type="hidden"
      :value="numericValue !== undefined ? numericValue : ''"
      :name="name"
      :required="required"
      :disabled="disabled"
    />
  </Primitive>
</template>

// packages/react/src/components/ColorField/ColorFieldRoot.tsx
import { forwardRef, useCallback, useMemo, useRef, useState } from "react";
import { Color } from "internationalized-color";
import { getChannelConfig, displayToCulori, culoriToDisplay, type ChannelConfig } from "@urcolor/core";
import { clamp, snapToStep } from "../../utils";
import { ColorFieldContext, type ColorFieldContextValue } from "./ColorFieldContext";

export interface ColorFieldRootProps {
  /** The controlled color value. */
  value?: Color | string | null;
  /** The default color value when uncontrolled. */
  defaultValue?: Color | string | null;
  /** The color space mode (e.g. 'hsl', 'oklch'). */
  colorSpace?: string;
  /** Which channel this field controls (e.g. 'h', 's', 'l'). */
  channel?: string;
  /** Channel display format. Auto-derived from colorSpace config if not set. */
  format?: "number" | "degree" | "percentage" | "hex";
  /** Minimum allowed value. */
  min?: number;
  /** Maximum allowed value. */
  max?: number;
  /** Step increment for arrow keys. */
  step?: number;
  /** Whether the field is disabled. */
  disabled?: boolean;
  /** Whether the field is read-only. */
  readOnly?: boolean;
  /** Callback fired when the color value changes. */
  onValueChange?: (color: Color) => void;
  /** Callback fired when the value changes at the end of an interaction. */
  onValueCommit?: (color: Color) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  as?: React.ElementType;
}

function parseColor(v: Color | string | null | undefined): Color | undefined {
  if (!v) return undefined;
  if (v instanceof Color) return v;
  return Color.parse(v) ?? undefined;
}

const ALPHA_CONFIG: ChannelConfig = { key: "alpha", label: "Alpha", min: 0, max: 100, step: 1, format: "percentage", culoriMin: 0, culoriMax: 1 };

export const ColorFieldRoot = forwardRef<HTMLDivElement, ColorFieldRootProps>(
  function ColorFieldRoot(props, ref) {
    const {
      value: valueProp,
      defaultValue: defaultValueProp,
      colorSpace = "hsl",
      channel = "h",
      format: formatProp,
      min: minProp,
      max: maxProp,
      step: stepProp,
      disabled = false,
      readOnly = false,
      onValueChange,
      onValueCommit,
      children,
      className,
      style,
      as: Component = "div",
    } = props;

    const isControlled = valueProp !== undefined;
    const [internalColor, setInternalColor] = useState<Color | undefined>(
      () => parseColor(valueProp) ?? parseColor(defaultValueProp),
    );

    const prevValueRef = useRef(valueProp);
    if (valueProp !== prevValueRef.current) {
      prevValueRef.current = valueProp;
      const parsed = parseColor(valueProp);
      if (parsed) setInternalColor(parsed);
    }

    const colorRef = isControlled ? (parseColor(valueProp) ?? internalColor) : internalColor;

    const isAlpha = channel === "alpha";
    const channelConfig = isAlpha ? ALPHA_CONFIG : getChannelConfig(colorSpace, channel);

    const effectiveFormat = formatProp ?? channelConfig?.format ?? "number";
    const isHexMode = effectiveFormat === "hex";
    const effectiveMin = minProp ?? channelConfig?.min ?? 0;
    const effectiveMax = maxProp ?? channelConfig?.max ?? (isHexMode ? 0xFFFFFF : 100);
    const effectiveStep = stepProp ?? channelConfig?.step ?? 1;

    function getDisplayValue(): number | undefined {
      if (!colorRef) return undefined;
      if (isHexMode) {
        const hex = colorRef.toHex()?.replace(/^#/, "");
        if (!hex) return undefined;
        return Number.parseInt(hex.slice(0, 6), 16);
      }
      if (!channelConfig) return undefined;
      if (isAlpha) return Math.round((colorRef.alpha ?? 1) * 100);
      const converted = colorRef.to(colorSpace);
      if (!converted) return undefined;
      const raw = converted.get(channel, 0);
      return culoriToDisplay(channelConfig, raw);
    }

    const [numericValue, setNumericValue] = useState<number | undefined>(() => getDisplayValue());

    // Sync from color changes
    const prevColorRef = useRef(colorRef);
    if (colorRef !== prevColorRef.current) {
      prevColorRef.current = colorRef;
      const v = getDisplayValue();
      if (v !== undefined && Math.abs((v ?? 0) - (numericValue ?? 0)) > 0.001) {
        setNumericValue(v);
      }
    }

    function formatValue(val: number | undefined): string {
      if (val === undefined) return "";
      switch (effectiveFormat) {
        case "degree": return `${val}\u00B0`;
        case "percentage": return `${val}%`;
        case "hex": return `#${Math.round(val).toString(16).padStart(6, "0")}`;
        default: return String(val);
      }
    }

    function parseValue(text: string): number | undefined {
      const trimmed = text.trim();
      if (trimmed === "") return undefined;
      switch (effectiveFormat) {
        case "degree": return Number.parseFloat(trimmed.replace(/[\u00B0]$|deg$/i, ""));
        case "percentage": return Number.parseFloat(trimmed.replace(/%$/, ""));
        case "hex": {
          const hex = trimmed.replace(/^#/, "");
          if (!/^[0-9a-f]*$/i.test(hex)) return undefined;
          return Number.parseInt(hex, 16);
        }
        default: return Number.parseFloat(trimmed);
      }
    }

    function clampValue(val: number): number {
      let clamped = clamp(val, effectiveMin, effectiveMax);
      clamped = snapToStep(clamped, effectiveMin, effectiveMax, effectiveStep);
      return clamped;
    }

    const [displayValue, setDisplayValue] = useState(() => formatValue(numericValue));

    // Keep display value in sync
    const prevNumericRef = useRef(numericValue);
    if (numericValue !== prevNumericRef.current) {
      prevNumericRef.current = numericValue;
      setDisplayValue(formatValue(numericValue));
    }

    function rebuildColor(displayVal: number): Color | undefined {
      if (!colorRef) return undefined;
      if (isHexMode) {
        const hexStr = `#${Math.round(clamp(displayVal, 0, 0xFFFFFF)).toString(16).padStart(6, "0")}`;
        return Color.parse(hexStr) ?? undefined;
      }
      if (!channelConfig) return undefined;
      if (isAlpha) return colorRef.set({ alpha: displayVal / 100 });
      const culoriVal = displayToCulori(channelConfig, displayVal);
      return colorRef.set({ mode: colorSpace, [channel]: culoriVal });
    }

    function emitColor(val: number): Color | undefined {
      const newColor = rebuildColor(val);
      if (newColor) {
        if (!isControlled) setInternalColor(newColor);
        onValueChange?.(newColor);
      }
      return newColor;
    }

    const inputRef = useRef<HTMLInputElement>(null);

    const commitValue = useCallback((val: number | undefined) => {
      if (val === undefined || Number.isNaN(val)) {
        setNumericValue(undefined);
        setDisplayValue("");
        return;
      }
      const clamped = isHexMode ? clamp(Math.round(val), effectiveMin, effectiveMax) : clampValue(val);
      setNumericValue(clamped);
      setDisplayValue(formatValue(clamped));
      const newColor = emitColor(clamped);
      if (newColor) onValueCommit?.(newColor);
    }, [isHexMode, effectiveMin, effectiveMax, effectiveStep, colorRef, channelConfig, isAlpha, colorSpace, channel, isControlled, onValueChange, onValueCommit]);

    const onInputChange = useCallback((text: string) => {
      setDisplayValue(text);
      const parsed = parseValue(text);
      if (parsed !== undefined && !Number.isNaN(parsed)) {
        setNumericValue(parsed);
        emitColor(parsed);
      }
    }, [colorRef, channelConfig, isAlpha, isHexMode, colorSpace, channel, isControlled, onValueChange]);

    const handleIncrease = useCallback((multiplier = 1) => {
      if (disabled || readOnly) return;
      const current = numericValue ?? 0;
      const next = clampValue(current + effectiveStep * multiplier);
      setNumericValue(next);
      setDisplayValue(formatValue(next));
      const newColor = emitColor(next);
      if (newColor) onValueCommit?.(newColor);
    }, [disabled, readOnly, numericValue, effectiveStep, effectiveMin, effectiveMax, colorRef, channelConfig, isAlpha, colorSpace, channel, isControlled, onValueChange, onValueCommit]);

    const handleDecrease = useCallback((multiplier = 1) => {
      if (disabled || readOnly) return;
      const current = numericValue ?? 0;
      const next = clampValue(current - effectiveStep * multiplier);
      setNumericValue(next);
      setDisplayValue(formatValue(next));
      const newColor = emitColor(next);
      if (newColor) onValueCommit?.(newColor);
    }, [disabled, readOnly, numericValue, effectiveStep, effectiveMin, effectiveMax, colorRef, channelConfig, isAlpha, colorSpace, channel, isControlled, onValueChange, onValueCommit]);

    const handleMinMaxValue = useCallback((type: "min" | "max") => {
      if (disabled || readOnly) return;
      const val = type === "min" ? effectiveMin : effectiveMax;
      setNumericValue(val);
      setDisplayValue(formatValue(val));
      const newColor = emitColor(val);
      if (newColor) onValueCommit?.(newColor);
    }, [disabled, readOnly, effectiveMin, effectiveMax, colorRef, channelConfig, isAlpha, colorSpace, channel, isControlled, onValueChange, onValueCommit]);

    const isDecreaseDisabled = numericValue !== undefined && clampValue(numericValue) <= effectiveMin;
    const isIncreaseDisabled = numericValue !== undefined && clampValue(numericValue) >= effectiveMax;

    const ctxValue = useMemo<ColorFieldContextValue>(() => ({
      modelValue: numericValue,
      displayValue,
      disabled,
      readOnly,
      isDecreaseDisabled,
      isIncreaseDisabled,
      handleIncrease,
      handleDecrease,
      handleMinMaxValue,
      commitValue,
      onInputChange,
      inputRef,
      format: effectiveFormat,
    }), [numericValue, displayValue, disabled, readOnly, isDecreaseDisabled, isIncreaseDisabled, handleIncrease, handleDecrease, handleMinMaxValue, commitValue, onInputChange, effectiveFormat]);

    return (
      <ColorFieldContext.Provider value={ctxValue}>
        <Component
          ref={ref}
          className={className}
          style={style}
          data-disabled={disabled ? "" : undefined}
          data-readonly={readOnly ? "" : undefined}
        >
          {children}
        </Component>
      </ColorFieldContext.Provider>
    );
  },
);
