// packages/react/src/components/ColorSwatchGroup/ColorSwatchGroupRoot.tsx
import { forwardRef, useCallback, useMemo, useRef, useState, type ComponentPropsWithoutRef } from "react";
import { ColorSwatchGroupContext, type ColorSwatchGroupContextValue, type SelectionType } from "./ColorSwatchGroupContext";

export interface ColorSwatchGroupRootProps extends ComponentPropsWithoutRef<"div"> {
  /** Whether to allow single or multiple selection. */
  type?: SelectionType;
  /** The controlled selected value(s). */
  value?: string[];
  /** The default selected value(s) when uncontrolled. */
  defaultValue?: string[];
  /** When true, prevents the user from interacting with the group. */
  disabled?: boolean;
  /** The orientation of the group for arrow key navigation. */
  orientation?: "horizontal" | "vertical";
  /** Callback fired when the selection changes. */
  onValueChange?: (value: string[]) => void;
}

export const ColorSwatchGroupRoot = forwardRef<HTMLDivElement, ColorSwatchGroupRootProps>(
  function ColorSwatchGroupRoot(props, ref) {
    const {
      type = "single",
      value: valueProp,
      defaultValue = [],
      disabled = false,
      orientation = "horizontal",
      onValueChange,
      children,
      ...rest
    } = props;

    const isControlled = valueProp !== undefined;
    const [internalValue, setInternalValue] = useState<string[]>(valueProp ?? defaultValue);

    const prevValueRef = useRef(valueProp);
    if (valueProp !== prevValueRef.current) {
      prevValueRef.current = valueProp;
      if (valueProp !== undefined) setInternalValue(valueProp);
    }

    const modelValue = isControlled ? (valueProp ?? internalValue) : internalValue;

    const changeModelValue = useCallback((value: string) => {
      let next: string[];
      if (type === "single") {
        next = modelValue.includes(value) ? [] : [value];
      } else {
        next = modelValue.includes(value)
          ? modelValue.filter(v => v !== value)
          : [...modelValue, value];
      }
      if (!isControlled) setInternalValue(next);
      onValueChange?.(next);
    }, [type, modelValue, isControlled, onValueChange]);

    const ctxValue = useMemo<ColorSwatchGroupContextValue>(() => ({
      modelValue,
      type,
      disabled,
      changeModelValue,
    }), [modelValue, type, disabled, changeModelValue]);

    return (
      <ColorSwatchGroupContext.Provider value={ctxValue}>
        <div
          ref={ref}
          role="group"
          data-orientation={orientation}
          {...rest}
        >
          {children}
        </div>
      </ColorSwatchGroupContext.Provider>
    );
  },
);

// packages/vue/src/components/ColorSwatchGroup/ColorSwatchGroupRoot.vue
<script lang="ts">
import type { Ref } from "vue";
import type { PrimitiveProps } from "reka-ui";
import { createContext } from "reka-ui";

export type SelectionType = "single" | "multiple";

export interface ColorSwatchGroupRootProps extends /* @vue-ignore */ PrimitiveProps {
  as?: string;
  asChild?: boolean;
  /** Whether to allow single or multiple selection. */
  type?: SelectionType;
  /** The controlled selected value(s). Can be bound as `v-model`. */
  modelValue?: string[];
  /** The default selected value(s) when uncontrolled. */
  defaultValue?: string[];
  /** When `true`, prevents the user from interacting with the group. */
  disabled?: boolean;
  /** The orientation of the group for arrow key navigation. */
  orientation?: "horizontal" | "vertical";
  /** Whether keyboard navigation should loop around. */
  loop?: boolean;
  /** Whether to use roving focus for keyboard navigation. */
  rovingFocus?: boolean;
  /** The reading direction. */
  dir?: "ltr" | "rtl";
}

export type ColorSwatchGroupRootEmits = {
  "update:modelValue": [value: string[]];
};

export interface ColorSwatchGroupContext {
  modelValue: Ref<string[]>;
  type: Ref<SelectionType>;
  disabled: Ref<boolean>;
  rovingFocus: Ref<boolean>;
  changeModelValue: (value: string) => void;
}

export const [injectColorSwatchGroupContext, provideColorSwatchGroupContext] =
  createContext<ColorSwatchGroupContext>("ColorSwatchGroupRoot");
</script>

<script setup lang="ts">
import { computed, ref, toRefs, watch } from "vue";
import { Primitive, useForwardExpose, useDirection, RovingFocusGroup } from "reka-ui";

const props = withDefaults(defineProps<ColorSwatchGroupRootProps>(), {
  as: "div",
  type: "single",
  defaultValue: () => [],
  disabled: false,
  orientation: "horizontal",
  loop: true,
  rovingFocus: true,
});

const emits = defineEmits<ColorSwatchGroupRootEmits>();
const { disabled, dir: propDir } = toRefs(props);
const dir = useDirection(propDir);
const { forwardRef } = useForwardExpose();

const internalValue = ref<string[]>(props.modelValue ?? props.defaultValue);

watch(
  () => props.modelValue,
  (val) => {
    if (val !== undefined) internalValue.value = val;
  },
);

function changeModelValue(value: string) {
  let next: string[];
  if (props.type === "single") {
    next = internalValue.value.includes(value) ? [] : [value];
  } else {
    next = internalValue.value.includes(value)
      ? internalValue.value.filter((v) => v !== value)
      : [...internalValue.value, value];
  }
  internalValue.value = next;
  emits("update:modelValue", next);
}

provideColorSwatchGroupContext({
  modelValue: internalValue,
  type: computed(() => props.type),
  disabled,
  rovingFocus: computed(() => props.rovingFocus),
  changeModelValue,
});
</script>

<template>
  <RovingFocusGroup
    v-if="rovingFocus"
    as-child
    :orientation="orientation"
    :dir="dir"
    :loop="loop"
  >
    <Primitive
      :ref="forwardRef"
      :as="as"
      :as-child="asChild"
      role="group"
      :dir="dir"
      :data-orientation="orientation"
    >
      <slot />
    </Primitive>
  </RovingFocusGroup>

  <Primitive
    v-else
    :ref="forwardRef"
    :as="as"
    :as-child="asChild"
    role="group"
    :dir="dir"
    :data-orientation="orientation"
  >
    <slot />
  </Primitive>
</template>
